#!/usr/bin/env python3
"""*** THE LANE REGISTRY: ONE DEFINITION OF EVERY ANDROID LANE, ITS REAL GRADLE TARGET, AND THE EVIDENCE IT EMITS. ***

*THE GAP THIS CLOSES, NAMED PLAINLY: the repo carrieth four committed iOS runners (foundation, UI, simulator) and ONE
Android runner (`run_android_lanes.sh`, four unit lanes). The plan's Android lane population is larger -- UNIT, UI
(the rendered-controls courts), SIMULATOR (the lab's launchable composition over the shared host platform) and the
PRODUCTION-SIMULATION lane (the LIGHT artifact built from the real Archive fixture and inspected as PACKAGED BYTES) --
and **the missing lanes were not merely unwritten: nothing NAMED them, so their absence reddened nothing.*** *A lane
that exists only in a developer's shell history is not evidence, and a lane nobody enumerates is a lane whose absence
reads as green.*

*** THE ONE LAW: A LANE'S VERDICT IS DERIVED FROM ITS OWN RAW PROCESS STATUS AND ITS OWN JUNIT OUTPUT -- NEVER
FABRICATED. *** *This module RUNS the real gradle target, CAPTURES the child's own exit status (never a pipeline's
last element), copies the JUnit XML the target really wrote into the lane's OWN evidence directory, and writeth a
report whose every field is a measurement.* **A report that claims PASSED while its counts, its digest, its class
roster or the inspector's verdict disagree is REFUSED by `verify_lane_report` -- so a report cannot be a claim its own
numbers refute, and the fake-green-vs-real-red trap is closed at the report's own boundary.**

*** AND EVERY PATH IS RESOLVED FROM THIS FILE'S OWN LOCATION. *** *The hosted checkout's cwd happens to be the
repository root today, but the four committed runners hard-code repository-relative paths.* **A runner invoked from a
foreign cwd (`/tmp`) must resolve the SAME tree -- so `REPO` is derived from `__file__`, and every subprocess cwd,
gradle project dir, artifact glob and digest input is anchored on it.**

*** AND THE FOUR HISTORICAL UNIT LANES ARE UNTOUCHED. *** *They keep their `build/test-results/<task>/` artifacts and
their `<lane>.sources.sha256` / `<lane>.pre.sha256` sidecars BYTE-IDENTICAL, because the workflow and
`ci/check_board1_manifest.py` already read them; this module emits those digests (so a caller need not re-derive them)
but never re-judges them.*

Usage:
    python3 tools/readiness/lane_registry.py --list [--json]
    python3 tools/readiness/lane_registry.py --check android:ui [--evidence-root ROOT]
    python3 tools/readiness/lane_registry.py --run android:ui [--evidence-root DIR] [--timeout S]
    python3 tools/readiness/lane_registry.py --selftest
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

#: *** THE REPOSITORY ROOT, RESOLVED FROM THIS FILE -- NEVER FROM THE CWD. ***
REPO = Path(__file__).resolve().parents[2]

LANE_SCHEMA = 1

#: The toolchain the android job uses; a caller may override through the environment.
DEFAULT_JAVA_HOME = "/opt/homebrew/opt/openjdk@17"
DEFAULT_ANDROID_HOME = str(Path.home() / "Library" / "Android" / "sdk")

#: The gradle wrapper, anchored on the repository root.
GRADLEW = REPO / "android" / "gradlew"

#: *** THE LANE POPULATION. EVERY FIELD IS CONSUMED BY THE RUNNER OR THE CHECKER. ***
#:
#: *`tasks` is the EXACT gradle argv tail (a lane whose report names a different target is refutable); `capture_globs`
#: names the directories the task really writes, whose XML is COPIED into the lane's own evidence directory under the
#: evidence root; `sources` is what the digest binds; `required_classes` is the population the lane exists for, checked
#: BY NAME so an omitted court cannot hide inside a green count.*
#:
#: **NO LANE FILTERS WITH `--tests`.** *A filtered run writeth its reports into a SIBLING task directory, which is the
#: exact pollution `check_lane_results` refuseth by name and which once inflated `android:mesh` to 1906 tests. So each
#: report lane runs a WHOLE task (whose directory is that task's own, regenerated by `--rerun-tasks`) and carries the
#: output to its own evidence root; the courts it exists for are then required BY NAME from the complete XML.*
LANE_SPECS: dict[str, dict] = {
    "android:app": {
        "kind": "unit",
        "module": ":app",
        "tasks": [":app:testLightDebugUnitTest"],
        "sources": ("android/app/src",),
        "results_glob": "android/app/build/test-results/testLightDebugUnitTest/*.xml",
        "sidecar": "android-app.sources.sha256",
        "pre_sidecar": "android-app.pre.sha256",
        "report": None,
        "log": None,
    },
    "android:core": {
        "kind": "unit",
        "module": ":core",
        "tasks": [":core:assembleDebug", ":core:testDebugUnitTest"],
        "sources": ("android/core/src",),
        "results_glob": "android/core/build/test-results/testDebugUnitTest/*.xml",
        "sidecar": "android-core.sources.sha256",
        "pre_sidecar": "android-core.pre.sha256",
        "report": None,
        "log": None,
    },
    "android:mesh": {
        "kind": "unit",
        "module": ":mesh",
        "tasks": [":mesh:testDebugUnitTest"],
        "sources": ("android/mesh/src",),
        "results_glob": "android/mesh/build/test-results/testDebugUnitTest/*.xml",
        "sidecar": "android-mesh.sources.sha256",
        "pre_sidecar": "android-mesh.pre.sha256",
        "report": None,
        "log": None,
    },
    "android:labmesh": {
        "kind": "unit",
        "module": ":labmesh",
        "tasks": [":labmesh:testDebugUnitTest"],
        "sources": ("android/labmesh/src",),
        "results_glob": "android/labmesh/build/test-results/testDebugUnitTest/*.xml",
        "sidecar": "android-labmesh.sources.sha256",
        "pre_sidecar": "android-labmesh.pre.sha256",
        "report": None,
        "log": None,
    },
    # *** THE UI LANE: THE RENDERED-CONTROLS COURTS, REQUIRED BY NAME. ***
    #
    # *The `:app` and `:labmesh` Compose courts (`createComposeRule` under Robolectric) are the only internal witnesses
    # that a control is really RENDERED -- that its semantics tree carries `contentDescription`/`stateDescription`/role
    # and that a returning reader lands at the reading anchor. They run INSIDE the unit lanes today, judged by the same
    # count census, so a rendered court that never executed was invisible among a thousand plain unit tests.* **This
    # lane runs the whole `:app` LIGHT-debug unit task and the whole `:labmesh` task, carries both task directories
    # into its own evidence root, and requirith each RENDERED court's own verdict BY NAME.**
    "android:ui": {
        "kind": "ui",
        "module": ":app+:labmesh",
        "tasks": [":app:testLightDebugUnitTest", ":labmesh:testDebugUnitTest"],
        "capture_globs": (
            "android/app/build/test-results/testLightDebugUnitTest/*.xml",
            "android/labmesh/build/test-results/testDebugUnitTest/*.xml",
        ),
        "sources": ("android/app/src", "android/labmesh/src", "android/mesh/src"),
        "results_glob": "android-ui-results/*.xml",
        "sidecar": "android-ui.sources.sha256",
        "pre_sidecar": "android-ui.pre.sha256",
        "report": "android-ui.lane.json",
        "log": "android-ui.log",
        "required_classes": (
            "GsFinal006RenderedReadingListTest",
            "GsFinal008TruthfulAvailabilityTest",
            "GsFinal006ReadingAnchorTest",
            "GsFinal006DocumentKeyPresenceTest",
            "ProbeEffectKeySemantics",
            "GsFinal009ProtectedDataGateTest",
            "GsFinal009TrustGateTest",
            "LabMeshJourneySemanticsTest",
            "LabMeshJourneyBoundTest",
            "LabMeshAppTest",
        ),
    },
    # *** THE SIMULATOR LANE: THE LAB'S LAUNCHABLE COMPOSITION, ON THE HOST JVM. ***
    #
    # *`android/labmesh` is the LAUNCHABLE application built from the SAME canonical `:core`/`:mesh` components (never
    # a lab twin), and `LabMeshApplication` composes `ProductionLabEstate` over a host platform that substitutes ONLY
    # the two doors a JVM lacks (the AndroidKeyStore identity factory and the SQLCipher native engine).* **This lane
    # drives that composition end to end -- application launch, journey, semantics -- and is the Android analogue of
    # the iOS simulator lane's "the app really runs" claim.** *It is NOT a device/emulator run, and the report SAYS so
    # -- a claim about a device this lane cannot make is never made.*
    "android:simulator": {
        "kind": "simulator",
        "module": ":labmesh",
        "tasks": [":labmesh:testDebugUnitTest"],
        "capture_globs": ("android/labmesh/build/test-results/testDebugUnitTest/*.xml",),
        "sources": ("android/labmesh/src", "android/mesh/src"),
        "results_glob": "android-simulator-results/*.xml",
        "sidecar": "android-simulator.sources.sha256",
        "pre_sidecar": "android-simulator.pre.sha256",
        "report": "android-simulator.lane.json",
        "log": "android-simulator.log",
        "device": None,          # deliberately not a device lane; the report states it
        "required_classes": ("LabMeshAppTest", "LabMeshJourneyBoundTest", "LabMeshJourneySemanticsTest"),
    },
    # *** THE PRODUCTION-SIMULATION LANE: THE LIGHT ARTIFACT, BUILT FROM THE REAL ARCHIVE AND INSPECTED AS BYTES. ***
    #
    # *MEASURED GAP: the workflow built `:app:assembleLightDebug` and ran the inspector INLINE -- with no lane
    # identity, no digest binding and no report -- so the ONE lane that reads the PACKAGED BYTES (the authority for
    # "the LIGHT release carrieth no model/:llm/cross-tier content and the true Archive") could not be re-derived by a
    # reader.*
    #
    # **THIS LANE SIMULATES THE PRODUCTION RUNTIME'S REAL BEHAVIOUR, NOT A STAND-IN:** it stages the Archive with the
    # repository's own `ci/archive_fixture.py` (THE integration the lane must hand its artifact to), builds the
    # SHIPPING variant (`:app:assembleLightDebug`), runs the production-estate courts over the real composition
    # (`:mesh:testDebugUnitTest`, whose `LabEstateSameEstateTest`/`LabWipeJourneyTest` drive the production estate over
    # the shared host platform), and finally inspects the BUILT APK with
    # `scripts/inspect_android_artifacts.py --expected-archive` -- **the packaged bytes are the authority, and the
    # expected Archive is the very file this lane staged for this build.**
    "android:production": {
        "kind": "production",
        "module": ":app",
        "tasks": [":app:assembleLightDebug", ":mesh:testDebugUnitTest"],
        "stages": ("stage-archive", "assemble", "courts", "inspect"),
        "capture_globs": ("android/mesh/build/test-results/testDebugUnitTest/*.xml",),
        "sources": ("android/app/src", "android/mesh/src", "ci/archive_fixture.py",
                    "scripts/inspect_android_artifacts.py"),
        "results_glob": "android-production-results/*.xml",
        "sidecar": "android-production.sources.sha256",
        "pre_sidecar": "android-production.pre.sha256",
        "report": "android-production.lane.json",
        "log": "android-production.log",
        "artifact_root": "android/app/build/outputs/apk/light/debug",
        "archive_path": "android/app/src/lightDebug/assets/archive_light.db",
        "required_classes": ("LabEstateSameEstateTest", "LabWipeJourneyTest"),
    },
}

#: *** THE LANES WHOSE VERDICT IS DERIVED FROM A REPORT (the three new ones). ***
REPORT_LANES: tuple[str, ...] = tuple(k for k, v in LANE_SPECS.items() if v.get("report"))

#: The lanes `run_android_lanes.sh` executes in order: the four unit lanes, then the three evidence lanes.
#: *The unit lanes run FIRST so their pre/post digests bind the same revision the report lanes then compile.*
RUN_ORDER: tuple[str, ...] = (
    "android:app", "android:core", "android:mesh", "android:labmesh",
    "android:ui", "android:simulator", "android:production",
)

UNIT_LANES: tuple[str, ...] = tuple(k for k, v in LANE_SPECS.items() if v["kind"] == "unit")


class LaneError(RuntimeError):
    """a lane could not be resolved, run, or its evidence could not be produced."""


# ---------------------------------------------------------------------------------------------------------------
# Sources and digests. ONE definition, consumed by the runner AND the checker's report verification.
# ---------------------------------------------------------------------------------------------------------------

def source_files(spec: dict) -> list[Path]:
    """The files a lane's digest is taken over: every source file under its trees, plus any named file.

    *Kept as a LIST OF PATHS so a caller can audit exactly which bytes the digest bound -- a digest alone is not
    evidence about WHICH sources it covered.* **RESOLVED FROM `REPO`, so a foreign cwd cannot change the answer.**
    """
    out: list[Path] = []
    for rel in spec.get("sources", ()):
        base = REPO / rel
        if base.is_file():
            out.append(base)
        elif base.is_dir():
            out.extend(sorted(p for p in base.rglob("*") if p.suffix in (".kt", ".kts", ".swift", ".py")))
    return sorted(set(out))


def source_digest(spec: dict) -> str:
    """The digest over a lane's sources, keyed by REPOSITORY-RELATIVE path so it is stable across checkouts."""
    h = hashlib.sha256()
    for path in source_files(spec):
        try:
            rel = str(path.relative_to(REPO))
        except ValueError:
            rel = str(path)
        h.update(rel.encode())
        h.update(b"\0")
        h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


# ---------------------------------------------------------------------------------------------------------------
# JUnit reading: the counts and the class population a report must reconcile against, read from the REAL XML.
# ---------------------------------------------------------------------------------------------------------------

def junit_totals(results_dir: Path) -> dict:
    """Parse every JUnit XML under `results_dir` and return the aggregate counts.

    *`tests=0` across a non-empty file set is the shape a broken build, a wrong filter or a truncated mirror all
    produce -- so the counts are returned verbatim and the CHECKER refuseth zero rather than this reader guessing.*
    """
    total = {"files": 0, "tests": 0, "failures": 0, "errors": 0, "skipped": 0}
    if not results_dir.is_dir():
        return total
    for path in sorted(results_dir.glob("*.xml")):
        if path.stat().st_size == 0:
            continue
        total["files"] += 1
        head = path.read_text(encoding="utf-8", errors="replace")[:4000]
        for key in ("tests", "failures", "errors", "skipped"):
            m = re.search(rf'(?<![\w-]){key}="(\d+)"', head)
            total[key] += int(m.group(1)) if m else 0
    return total


def junit_classes(results_dir: Path) -> dict[str, int]:
    """`{classname: verdicts}` for every `classname="..."` in the lane's real XML (last segment of an FQCN)."""
    seen: dict[str, int] = {}
    if not results_dir.is_dir():
        return seen
    for path in sorted(results_dir.glob("*.xml")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r'(?<![\w-])classname="([^"]+)"', text):
            cls = m.group(1).split(".")[-1]
            seen[cls] = seen.get(cls, 0) + 1
    return seen


# ---------------------------------------------------------------------------------------------------------------
# The runner: the REAL target, the child's OWN status, the evidence the lane emits.
# ---------------------------------------------------------------------------------------------------------------

def _gradle_environment(environ: dict | None = None) -> dict:
    env = dict(os.environ if environ is None else environ)
    env.setdefault("JAVA_HOME", DEFAULT_JAVA_HOME)
    env.setdefault("ANDROID_HOME", DEFAULT_ANDROID_HOME)
    return env


def _lane_dir(evidence_root: Path, spec: dict) -> Path:
    return Path(evidence_root) / Path(spec["results_glob"]).parent


def capture(dest: Path, globs: tuple[str, ...] | list[str]) -> list[str]:
    """Copy the lane's REAL build output into the lane's own evidence directory.

    *** A COPY IS NOT A FABRICATION, AND THE REPORT SAYETH WHICH IT IS. *** *The source is the directory the gradle
    target itself wrote (regenerated by `--rerun-tasks`, so the copy is that run's own generation); the copy's own
    sha256 is recorded beside it. The ALTERNATIVE -- a FILTERED run writing beside another lane's task directory -- is
    the exact pollution `check_lane_results` refuseth by name, which is why no lane here filters.*
    """
    dest.mkdir(parents=True, exist_ok=True)
    copied: list[str] = []
    for rel in globs:
        src = REPO / rel
        for path in sorted(src.parent.glob(src.name)):
            shutil.copyfile(path, dest / path.name)
            copied.append(path.name)
    return copied


def _gradle_argv(tasks: list[str]) -> list[str]:
    return [str(GRADLEW), "-p", str(REPO / "android"), *tasks, "--rerun-tasks", "--no-daemon", "--console=plain"]


def _spawn(argv: list[str], log_stream, env: dict, timeout: int, cwd: Path | None = None) -> int:
    """Run one child and return ITS OWN status -- never a pipeline's last element."""
    return subprocess.call(argv, cwd=str(cwd or REPO), env=env, stdout=log_stream,
                           stderr=subprocess.STDOUT, timeout=timeout)


def run_lane(lane: str, *, evidence_root: Path | str | None = None, log_dir: Path | str | None = None,
             timeout: int = 3600, environ: dict | None = None, runner=None,
             extra_args: tuple[str, ...] = ()) -> dict:
    """RUN one lane's REAL target, capture its own status and its real output, and write its report.

    *`runner` is an injection seam used ONLY by `--selftest` and the courts; production passeth None and the real
    `subprocess` runs.* **A non-zero child status is RECORDED, never raised: the runner produceth evidence and the
    checker decideth -- exactly the rule the three iOS runners already state.** *Only a run that could not produce its
    evidence at all raiseth `LaneError`.*
    """
    spec = LANE_SPECS.get(lane)
    if spec is None:
        raise LaneError(f"unknown lane {lane!r}; known: {', '.join(sorted(LANE_SPECS))}")
    if not GRADLEW.is_file():
        raise LaneError(f"the gradle wrapper is absent at {GRADLEW} -- a lane that cannot run is not a pass")
    if spec["kind"] == "unit":
        raise LaneError(f"{lane} is the historical unit lane; its evidence is produced by run_android_lanes.sh and "
                        f"judged by `ci/check_lane_results.py --scope android`")
    base = Path(evidence_root).resolve() if evidence_root is not None else REPO
    log_root = Path(log_dir).resolve() if log_dir is not None else base
    log_root.mkdir(parents=True, exist_ok=True)
    log_path = log_root / spec["log"]

    pre = source_digest(spec)
    env = _gradle_environment(environ)
    started = time.time()
    steps: list[dict] = []
    with log_path.open("w", encoding="utf-8") as stream:
        stream.write(f"== {lane} ==\n")
        stream.write(f"pre_source_digest={pre}\n\n")
        stream.flush()

        def step(name: str, argv: list[str]) -> int:
            stream.write(f"\n----- step: {name} -----\n$ {' '.join(argv)}\n")
            stream.flush()
            if runner is None:
                rc = _spawn(argv, stream, env, timeout)
            else:
                rc = int(runner(argv, str(REPO), str(log_path), stream))
            steps.append({"step": name, "argv": list(argv), "rc": int(rc)})
            stream.write(f"----- step {name}: rc={rc} -----\n")
            stream.flush()
            return int(rc)

        first_bad = 0
        if spec["kind"] == "production":
            # *** THE ARCHIVE IS STAGED FIRST, BY THE REPOSITORY'S OWN FIXTURE BUILDER. ***
            # *The production lane's packaged-bytes comparison is only meaningful against the bytes THIS build was
            # given, so the fixture is regenerated here and its digest recorded -- never assumed to be on disk.*
            archive = REPO / spec["archive_path"]
            rc = step("stage-archive", [sys.executable, "ci/archive_fixture.py", "--out", str(archive)])
            first_bad = rc or first_bad
            rc = step("assemble", _gradle_argv([spec["tasks"][0], *extra_args]))
            first_bad = first_bad or rc
            rc = step("courts", _gradle_argv([spec["tasks"][1], *extra_args]))
            first_bad = first_bad or rc
            # *** AND THE INSPECTOR RUNS OVER THE BUILT BYTES, WHATEVER THE EARLIER STEPS REPORTED. ***
            # *A build that failed leaves no APK and the inspector says so by name; running it anyway means the report
            # carrieth the inspector's OWN verdict rather than a verdict inferred from an earlier rc.*
            inspection_out = _lane_dir(base, spec) / "inspection"
            rc = step("inspect", [sys.executable, "scripts/inspect_android_artifacts.py",
                                  str(REPO / spec["artifact_root"]), str(inspection_out),
                                  "--expected-archive", str(archive)])
            first_bad = first_bad or rc
        else:
            for index, task in enumerate(spec["tasks"]):
                rc = step(f"gradle-{index}", _gradle_argv([task, *extra_args]))
                first_bad = first_bad or rc

    seconds = round(time.time() - started, 3)
    report = build_report(lane, spec, raw_rc=first_bad, pre=pre, post=source_digest(spec), log_path=log_path,
                          seconds=seconds, base=base, steps=steps)
    report_path = base / spec["report"]
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (base / spec["pre_sidecar"]).write_text(pre + "\n", encoding="utf-8")
    (base / spec["sidecar"]).write_text(report["post_digest"] + "\n", encoding="utf-8")
    return report


def build_report(lane: str, spec: dict, *, raw_rc: int, pre: str, post: str, log_path: Path,
                 seconds: float, base: Path, steps: list[dict] | None = None) -> dict:
    """Assemble the report from MEASUREMENTS ONLY.

    *Every field is read from the real build output, hashed from a real file, or is a child's own status. The
    `verdict` is DERIVED (never asserted), so a report cannot claim a pass its own numbers refute.*
    """
    dest = _lane_dir(base, spec)
    copied = capture(dest, spec.get("capture_globs", ()))
    totals = junit_totals(dest)
    classes = junit_classes(dest)
    report = {
        "schema": LANE_SCHEMA,
        "lane": lane,
        "kind": spec["kind"],
        "module": spec.get("module"),
        "gradle_tasks": list(spec["tasks"]),
        "stages": list(spec.get("stages", ())),
        "steps": list(steps or ()),
        "raw_rc": int(raw_rc),
        "seconds": seconds,
        "log": log_path.name,
        "pre_digest": pre,
        "post_digest": post,
        "digest": post,
        "drift": pre != post,
        "junit": totals,
        "classes": dict(sorted(classes.items())),
        "results": {"dir": str(Path(spec["results_glob"]).parent), "files": copied,
                    "sha256": {name: _sha256_file(dest / name) for name in copied}},
        "device": spec.get("device"),
        "simulation_not_device": spec["kind"] == "simulator",
        "produced_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    if spec["kind"] == "production":
        report.update(production_facts(spec, results_dir=dest))
    report["verdict"] = derive_verdict(report, spec)
    return report


def production_facts(spec: dict, *, results_dir: Path) -> dict:
    """The production lane's own measurements: the built APK, the staged Archive, and the inspector's verdict.

    *NOTHING IS ASSUMED. The Archive digest is the file this lane actually staged; the APK digest is the built product;
    the inspector's own report is READ VERBATIM from `results/inspection/approved-archive-presence.json`. A field that
    could not be measured is NAMED absent (`None`), never filled with a plausible value.*
    """
    facts: dict = {"apk": None, "apk_sha256": None, "archive": spec.get("archive_path"),
                   "archive_sha256": None, "inspection": None, "inspection_verdict": None,
                   "inspection_mode": None, "release_candidate": False}
    archive = REPO / str(spec.get("archive_path", ""))
    if archive.is_file():
        facts["archive_sha256"] = _sha256_file(archive)
    root = REPO / str(spec.get("artifact_root", ""))
    apks = sorted(root.glob("*.apk")) if root.is_dir() else []
    if len(apks) == 1:
        facts["apk"] = apks[0].name
        facts["apk_sha256"] = _sha256_file(apks[0])
    elif len(apks) > 1:
        # *TWO APKs IS NOT ONE ARTIFACT: naming either would be a guess, so the ambiguity is recorded as such.*
        facts["apk"] = "AMBIGUOUS: " + ", ".join(p.name for p in apks)
    inspection = results_dir / "inspection" / "approved-archive-presence.json"
    if inspection.is_file():
        try:
            doc = json.loads(inspection.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            facts["inspection_verdict"] = f"UNREADABLE: {exc}"
        else:
            facts["inspection"] = "inspection/approved-archive-presence.json"
            facts["inspection_verdict"] = doc.get("verdict")
            facts["inspection_mode"] = doc.get("evidence")
            facts["release_candidate"] = bool(doc.get("expected_sha256"))
    return facts


def derive_verdict(report: dict, spec: dict) -> str:
    """The verdict, DERIVED from the measurements -- `PASSED` only when every measurement supports it.

    *This is the ONE place a pass is minted for a report lane, and every condition is named here rather than in prose.
    `verify_lane_report` re-derives the same conditions from the evidence, so the report's own `verdict` is never
    trusted as a substitute for the numbers.*
    """
    junit = report.get("junit") or {}
    if report.get("drift"):
        return "FAILED: a lane input changed WHILE the lane ran (pre/post digests disagree)"
    if report.get("raw_rc") != 0:
        return f"FAILED: a pipeline step returned rc={report.get('raw_rc')}"
    if junit.get("files", 0) == 0:
        return "FAILED: the lane produced no JUnit result file (its courts did not run)"
    if junit.get("tests", 0) == 0:
        return ("FAILED: ZERO tests executed -- this is what a broken build, a wrong filter or a truncated "
                "mirror looks like")
    if junit.get("failures", 0) or junit.get("errors", 0):
        return f"FAILED: {junit.get('failures', 0)} failure(s) / {junit.get('errors', 0)} error(s)"
    if junit.get("skipped", 0):
        return f"FAILED: {junit.get('skipped', 0)} skipped arm(s) -- a skipped arm is not a green arm"
    for cls in spec.get("required_classes", ()):
        if not (report.get("classes") or {}).get(cls):
            return f"FAILED: no verdict for the source-declared class {cls}"
    if spec["kind"] == "production":
        if not report.get("apk_sha256"):
            return "FAILED: no unique built APK was found to inspect"
        if not report.get("archive_sha256"):
            return "FAILED: the expected Archive was not staged, so the packaged bytes were never compared"
        if report.get("inspection_verdict") != "pass":
            return f"FAILED: the packaged-bytes inspector's verdict is {report.get('inspection_verdict')!r}"
    return "PASSED"


# ---------------------------------------------------------------------------------------------------------------
# Verification: the checker's and the court's ONE derivation (no gradle).
# ---------------------------------------------------------------------------------------------------------------

def _load_report(base: Path, spec: dict) -> tuple[dict | None, list[str]]:
    path = base / spec["report"]
    if not path.is_file():
        return None, [f"{spec['report']} is absent -- *the lane produced no report, and AN UNRUN LANE IS NOT A PASS. "
                      f"Run `tools/readiness/run_android_lanes.sh --report-lanes-only`.*"]
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return None, [f"{spec['report']} is not readable JSON: {exc}"]
    if not isinstance(doc, dict):
        return None, [f"{spec['report']} is not a JSON object"]
    return doc, []


def verify_lane_report(lane: str, *, evidence_root: Path | str | None = None) -> list[str]:
    """*** THE LANE'S VERDICT, RE-DERIVED FROM ITS OWN REPORT, ITS OWN RESULTS AND THE REAL SOURCES. ***

    *Returns the list of problems; EMPTY means the lane carried a real, current, passing result.* **Nothing is taken
    on the report's word: the digest is recomputed from the tree, the counts are re-parsed from the copied XML, the
    class population is re-derived from the XML, the sidecars must exist and agree, and the gradle target named in the
    report must be the registry's own.** *A report that claims `PASSED` while any of those disagree is a REFUSAL -- the
    fake-green-vs-real-red trap this lane set exists to close.*
    """
    spec = LANE_SPECS.get(lane)
    if spec is None:
        return [f"{lane}: unknown lane -- *a lane name nobody declares cannot be judged.*"]
    if not spec.get("report"):
        return [f"{lane}: this lane's verdict is derived from its digest sidecars and result files, not a report "
                f"(see `ci/check_lane_results.py --scope android`)"]
    base = Path(evidence_root).resolve() if evidence_root is not None else REPO
    doc, problems = _load_report(base, spec)
    if doc is None:
        return problems

    if doc.get("lane") != lane:
        problems.append(f"{lane}: the report names lane {doc.get('lane')!r} -- *a report for another lane is not this "
                        f"lane's evidence.*")
    declared = list(spec["tasks"])
    recorded = list(doc.get("gradle_tasks") or [])
    if recorded != declared:
        problems.append(f"{lane}: the report's gradle target {recorded} is NOT the registry's {declared} -- *a lane "
                        f"report that names a different target is a claim about a target nobody ran.*")
    stages_declared = list(spec.get("stages", ()))
    if list(doc.get("stages") or []) != stages_declared:
        problems.append(f"{lane}: the report's stages {list(doc.get('stages') or [])} are NOT the registry's "
                        f"{stages_declared} -- *a production lane that dropped its archive-staging or inspection "
                        f"stage is a claim about bytes nobody compared.*")

    # THE DIGEST: recomputed from the REAL tree, and the pre/post pair must agree.
    current = source_digest(spec)
    if not doc.get("digest"):
        problems.append(f"{lane}: the report carrieth NO source digest -- *an undatable lane is not evidence about "
                        f"the current tree.*")
    elif doc["digest"] != current:
        problems.append(f"{lane}: STALE -- the report's digest {str(doc['digest'])[:16]}… does not match the tree's "
                        f"{current[:16]}… -- *the lane never saw these sources. Re-run the lane.*")
    if doc.get("pre_digest") and doc.get("post_digest") and doc["pre_digest"] != doc["post_digest"]:
        problems.append(f"{lane}: SOURCE SET CHANGED WHILE IT RAN: pre-run {str(doc['pre_digest'])[:16]}… does not "
                        f"match post-run {str(doc['post_digest'])[:16]}… -- *the results describe no single revision.*")

    # THE SIDECARS the report claims to have written must exist and AGREE -- a report alone is not the emission.
    for key in ("pre_sidecar", "sidecar"):
        name = spec[key]
        side = base / name
        if not side.is_file():
            problems.append(f"{lane}: the report's own sidecar {name} is absent -- *the runner emits both, and a "
                            f"report whose sidecars are missing describes evidence nobody can read.*")
        else:
            text = side.read_text(encoding="utf-8").strip()
            expected = doc.get("pre_digest") if key == "pre_sidecar" else doc.get("digest")
            if expected and text != expected:
                problems.append(f"{lane}: {name} carrieth {text[:16]}… but the report carrieth "
                                f"{str(expected)[:16]}… -- *two records of one digest disagree.*")

    # THE RAW STATUS: the child's own exit code, never a pipeline's.
    raw = doc.get("raw_rc")
    if raw is None:
        problems.append(f"{lane}: the report carrieth NO raw_rc -- *an absent status cannot be reconciled with a "
                        f"green.*")
    elif raw != 0:
        problems.append(f"{lane}: the raw status is {raw}, NOT zero (the report's own verdict: {doc.get('verdict')!r})"
                        f" -- *a non-zero process is a failure whatever the summary says.*")

    # THE REAL OUTPUT: the copied XML must be there and re-parse to the report's own counts.
    results_dir = base / Path(spec["results_glob"]).parent
    if not results_dir.is_dir() or not sorted(results_dir.glob("*.xml")):
        problems.append(f"{lane}: NO RESULT FILES under {Path(spec['results_glob']).parent}/ -- *the lane's own "
                        f"evidence directory is empty, so the target's output was never captured.*")
        return problems
    live = junit_totals(results_dir)
    recorded_junit = doc.get("junit") or {}
    if live != recorded_junit:
        problems.append(f"{lane}: the report's counts {recorded_junit} disagree with the XML's {live} -- *the report "
                        f"is not a measurement of the bytes it points to.*")
    if live["tests"] == 0:
        problems.append(f"{lane}: ZERO tests executed across {live['files']} result file(s) -- *a zero-test run has "
                        f"not measured anything and is NOT a pass.*")
    if live["failures"] or live["errors"]:
        problems.append(f"{lane}: {live['failures']} failure(s) / {live['errors']} error(s) in the real XML")
    if live["skipped"]:
        problems.append(f"{lane}: {live['skipped']} SKIPPED arm(s) -- *a skipped arm is not a green arm.*")

    # THE SOURCE-DECLARED CLASS POPULATION: every class the lane exists for must carry a verdict BY NAME.
    observed = junit_classes(results_dir)
    for cls in spec.get("required_classes", ()):
        if observed.get(cls, 0) == 0:
            problems.append(f"{lane}: the real XML carrieth NO verdict for the source-declared class {cls} -- *an "
                            f"omitted class cannot be absent from a green count.*")
    if observed and doc.get("classes") and dict(sorted(observed.items())) != dict(sorted(doc["classes"].items())):
        problems.append(f"{lane}: the report's class population {sorted(doc['classes'])} disagrees with the XML's "
                        f"{sorted(observed)}")

    # THE PRODUCTION LANE'S OWN FACTS: the built APK, the staged Archive and the inspector's verdict.
    if spec["kind"] == "production":
        problems.extend(_production_problems(doc))
    return problems


def _production_problems(doc: dict) -> list[str]:
    problems: list[str] = []
    if not doc.get("apk_sha256"):
        problems.append("android:production: the report carrieth no unique built APK digest -- *a production lane "
                        "that cannot name the artifact it built has nothing to inspect.*")
    if not doc.get("archive_sha256"):
        problems.append("android:production: the report carrieth no staged Archive digest -- *the packaged bytes "
                        "were never compared against a known-good Archive.*")
    verdict = doc.get("inspection_verdict")
    if verdict != "pass":
        problems.append(f"android:production: the packaged-bytes inspector's verdict is {verdict!r}, not 'pass' -- "
                        f"*the LIGHT APK was not proven free of model/:llm/cross-tier content, or the packaged "
                        f"Archive was not byte-true.*")
    if not isinstance(doc.get("release_candidate"), bool):
        problems.append("android:production: the report does not state whether the release-candidate (fixture "
                        "prohibition) mode ran -- *an unstated mode lets a dev fixture read as release proof.*")
    return problems


# ---------------------------------------------------------------------------------------------------------------
# The registry contract's own adversarial selftest (no gradle): every refusal must be observed.
# ---------------------------------------------------------------------------------------------------------------

def selftest() -> int:
    """*** ADVERSARIAL MUTATIONS OF `verify_lane_report`: EACH MUST BE REFUSED. ***

    *A control that has only ever been observed passing is not a control. Each case builds a SYNTHETIC evidence root
    whose report or XML is wrong in ONE way, and requirith that exact refusal -- while the first case proves a
    genuinely-green lane is ACCEPTED, so the refusals are not vacuous.*
    """
    passed = total = 0

    def record(ok: bool, desc: str, detail: str = "") -> None:
        nonlocal passed, total
        total += 1
        if ok:
            passed += 1
            print(f"   PASS: {desc}")
        else:
            print(f"   FAIL: {desc}{' -- ' + detail if detail else ''}")

    def good_root(td: Path, lane: str, *, failures: int = 0, skip_classes: tuple[str, ...] = (),
                  apk: bool = True, inspection: str = "pass", drop_class: str | None = None) -> Path:
        """A synthetic evidence root shaped like a real lane's, derived from the REAL sources and the REAL registry."""
        spec = LANE_SPECS[lane]
        digest = source_digest(spec)
        results = td / Path(spec["results_glob"]).parent
        results.mkdir(parents=True, exist_ok=True)
        arms = []
        for cls in spec.get("required_classes", ()):
            if cls == drop_class:
                continue
            for i in range(2):
                body = '<failure message="boom"/>' if failures and i == 0 else ""
                arms.append(f'<testcase classname="io.godstone.x.{cls}" name="t{i}">{body}</testcase>')
        (results / "TEST-green.xml").write_text(
            f'<?xml version="1.0"?><testsuite name="x" tests="{len(arms)}" skipped="0" '
            f'failures="{failures}" errors="0">{"".join(arms)}</testsuite>', encoding="utf-8")
        report = {
            "schema": LANE_SCHEMA, "lane": lane, "kind": spec["kind"], "module": spec.get("module"),
            "gradle_tasks": list(spec["tasks"]), "stages": list(spec.get("stages", ())),
            "raw_rc": 0, "seconds": 1.0, "log": spec["log"],
            "pre_digest": digest, "post_digest": digest, "digest": digest, "drift": False,
            "junit": junit_totals(results), "classes": junit_classes(results),
            "results": {"files": ["TEST-green.xml"]}, "verdict": "PASSED",
            "produced_utc": "1970-01-01T00:00:00Z",
        }
        if spec["kind"] == "production":
            report.update({"apk_sha256": "a" * 64 if apk else None, "archive_sha256": "b" * 64,
                           "inspection_verdict": inspection, "release_candidate": False})
        (td / spec["report"]).write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (td / spec["pre_sidecar"]).write_text(digest + "\n", encoding="utf-8")
        (td / spec["sidecar"]).write_text(digest + "\n", encoding="utf-8")
        return td

    def rewrite(root: Path, lane: str, **fields) -> None:
        path = root / LANE_SPECS[lane]["report"]
        doc = json.loads(path.read_text(encoding="utf-8"))
        doc.update(fields)
        path.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    with tempfile.TemporaryDirectory() as raw:
        tmp = Path(raw)
        for lane in ("android:ui", "android:simulator"):
            spec = LANE_SPECS[lane]
            # 1. THE GREEN CONTROL.
            root = good_root(tmp / f"green-{lane.replace(':', '-')}", lane)
            probs = verify_lane_report(lane, evidence_root=root)
            record(not probs, f"{lane}: a genuinely-green lane is ACCEPTED", f"refused: {probs}")

            # 2. AN ABSENT REPORT -- an unrun lane is not a pass.
            empty = tmp / f"empty-{lane.replace(':', '-')}"
            empty.mkdir()
            probs = verify_lane_report(lane, evidence_root=empty)
            record(bool(probs) and "absent" in probs[0], f"{lane}: an ABSENT report is REFUSED", f"got {probs}")

            # 3. A NON-ZERO RAW STATUS.
            root = good_root(tmp / f"rc-{lane.replace(':', '-')}", lane)
            rewrite(root, lane, raw_rc=1)
            probs = verify_lane_report(lane, evidence_root=root)
            record(bool(probs) and any("raw status is 1" in p for p in probs),
                   f"{lane}: a non-zero raw status is REFUSED", f"got {probs}")

            # 4. A STALE DIGEST -- the lane ran against other bytes.
            root = good_root(tmp / f"stale-{lane.replace(':', '-')}", lane)
            rewrite(root, lane, digest="0" * 64, post_digest="0" * 64)
            (root / spec["sidecar"]).write_text("0" * 64 + "\n", encoding="utf-8")
            probs = verify_lane_report(lane, evidence_root=root)
            record(bool(probs) and any("STALE" in p for p in probs),
                   f"{lane}: a stale (never-saw-these-sources) lane is REFUSED", f"got {probs}")

            # 5. MID-RUN DRIFT.
            root = good_root(tmp / f"drift-{lane.replace(':', '-')}", lane)
            rewrite(root, lane, pre_digest="1" * 64)
            probs = verify_lane_report(lane, evidence_root=root)
            record(bool(probs) and any("CHANGED WHILE IT RAN" in p for p in probs),
                   f"{lane}: a lane whose sources changed mid-run is REFUSED", f"got {probs}")

            # 6. ZERO TESTS -- the broken-build shape.
            root = good_root(tmp / f"zero-{lane.replace(':', '-')}", lane)
            results = root / Path(spec["results_glob"]).parent
            (results / "TEST-green.xml").write_text(
                '<?xml version="1.0"?><testsuite name="x" tests="0" skipped="0" failures="0" errors="0"></testsuite>',
                encoding="utf-8")
            rewrite(root, lane, junit=junit_totals(results), classes={})
            probs = verify_lane_report(lane, evidence_root=root)
            record(bool(probs) and any("ZERO tests" in p for p in probs),
                   f"{lane}: a zero-test lane is REFUSED", f"got {probs}")

            # 7. A FAILING ARM while the report still claims PASSED.
            root = good_root(tmp / f"fail-{lane.replace(':', '-')}", lane, failures=1)
            probs = verify_lane_report(lane, evidence_root=root)
            record(bool(probs) and any("failure(s)" in p for p in probs),
                   f"{lane}: a FAILING arm is refused even while the report claims PASSED", f"got {probs}")

            # 8. AN OMITTED SOURCE-DECLARED CLASS -- the count cannot see the substitution.
            root = good_root(tmp / f"omit-{lane.replace(':', '-')}", lane, drop_class=spec["required_classes"][0])
            probs = verify_lane_report(lane, evidence_root=root)
            record(bool(probs) and any("NO verdict for the source-declared class" in p for p in probs),
                   f"{lane}: an OMITTED source-declared class is REFUSED", f"got {probs}")

            # 9. A REPORT NAMING ANOTHER TARGET.
            root = good_root(tmp / f"target-{lane.replace(':', '-')}", lane)
            rewrite(root, lane, gradle_tasks=[":app:testDebugUnitTest"])
            probs = verify_lane_report(lane, evidence_root=root)
            record(bool(probs) and any("NOT the registry's" in p for p in probs),
                   f"{lane}: a report naming a DIFFERENT gradle target is REFUSED", f"got {probs}")

            # 10. A MISSING SIDECAR -- the emission is not the report alone.
            root = good_root(tmp / f"sidecar-{lane.replace(':', '-')}", lane)
            (root / spec["sidecar"]).unlink()
            probs = verify_lane_report(lane, evidence_root=root)
            record(bool(probs) and any("sidecar" in p for p in probs),
                   f"{lane}: a report whose sidecar is missing is REFUSED", f"got {probs}")

        # 11. THE PRODUCTION LANE: an inspector that did NOT pass is a failure whatever the counts say.
        root = good_root(tmp / "prod-rejected", "android:production", inspection="rejected")
        probs = verify_lane_report("android:production", evidence_root=root)
        record(bool(probs) and any("inspector's verdict" in p for p in probs),
               "android:production: a packaged-bytes inspector that did NOT pass is REFUSED", f"got {probs}")

        # 12. THE PRODUCTION LANE: no unique APK.
        root = good_root(tmp / "prod-noapk", "android:production", apk=False)
        probs = verify_lane_report("android:production", evidence_root=root)
        record(bool(probs) and any("no unique built APK" in p for p in probs),
               "android:production: a report with no built-APK digest is REFUSED", f"got {probs}")

        # 13. THE PRODUCTION LANE: a dropped archive-staging stage.
        root = good_root(tmp / "prod-stages", "android:production")
        rewrite(root, "android:production", stages=["assemble", "courts"])
        probs = verify_lane_report("android:production", evidence_root=root)
        record(bool(probs) and any("stages" in p for p in probs),
               "android:production: dropped archive-staging/inspection stages are REFUSED", f"got {probs}")

        # 14. A UNIT LANE IS NOT JUDGED HERE -- it must say so rather than pass by omission.
        probs = verify_lane_report("android:mesh", evidence_root=tmp)
        record(bool(probs) and "not a report" in probs[0],
               "a unit lane is NAMED as out of this verifier's scope, never silently passed", f"got {probs}")

    print(f"selftest: {passed}/{total} checks passed")
    return 0 if (passed == total and total > 0) else 1


# ---------------------------------------------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="the Android lane registry")
    ap.add_argument("--list", action="store_true", help="print every lane and its real gradle target")
    ap.add_argument("--json", action="store_true", help="with --list, emit JSON")
    ap.add_argument("--check", metavar="LANE", help="re-derive one report lane's verdict from its evidence")
    ap.add_argument("--run", metavar="LANE", help="RUN one report lane's real targets and write its report")
    ap.add_argument("--evidence-root", default=None)
    ap.add_argument("--log-dir", default=None)
    ap.add_argument("--timeout", type=int, default=3600)
    ap.add_argument("--extra-arg", action="append", default=None,
                    help="an extra gradle argument for --run (repeatable)")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)

    if args.selftest:
        return selftest()
    if args.list:
        if args.json:
            print(json.dumps({k: {"kind": v["kind"], "module": v.get("module"), "tasks": v["tasks"],
                                  "report": v.get("report")} for k, v in LANE_SPECS.items()},
                             indent=2, sort_keys=True))
        else:
            for lane in RUN_ORDER:
                spec = LANE_SPECS[lane]
                print(f"{lane:<20} {spec['kind']:<11} {' '.join(spec['tasks'])}")
        return 0
    if args.check:
        problems = verify_lane_report(args.check, evidence_root=args.evidence_root)
        if problems:
            print(f"LANE {args.check}: FAILED")
            for p in problems:
                print("  - " + p)
            return 1
        print(f"LANE {args.check}: PASSED (report, digests, sidecars, raw status, counts and class roster all agree)")
        return 0
    if args.run:
        try:
            report = run_lane(args.run, evidence_root=args.evidence_root, log_dir=args.log_dir,
                              timeout=args.timeout, extra_args=tuple(args.extra_arg or ()))
        except LaneError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 1
        print(f"lane {args.run}: raw_rc={report['raw_rc']} verdict={report['verdict']} "
              f"tests={report['junit'].get('tests', 0)} digest={str(report['digest'])[:16]}…")
        return 0 if str(report["verdict"]).startswith("PASSED") else 1
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
