package io.godstone.mesh

import io.godstone.mesh.router.ProofOfWork
import io.godstone.mesh.wire.v2.TypeV2
import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Recipient-side GMP/2.1 proof-of-work (ADR-001 §3, Stage 3 Phase C / C4).
 *
 * The nonce lives inside the sealed payload; the recipient verifies it after
 * SealedSender.open. This test exercises the mine/verify round-trip directly --
 * the router no longer gates on PoW at the relay (see RouterTest).
 *
 * CANONICAL PREIMAGE (pinned against crypto/gmp21_vectors.json, generated by
 * the independent Python reference crypto/gmp21.py):
 *
 *     BLAKE2s-256(pow_nonce[8] ‖ sender_node_id[16] ‖ created_at_le[4] ‖
 *                 type_code[1] ‖ plaintext)
 *
 * created_at is serialised LITTLE-ENDIAN -- the SAME canonical encoding used by
 * MessageId.derive (§3.3 `created_at_le`) and the sealed payload, so the three
 * derivations agree byte-for-byte across Python / Android / iOS. The KAT tests
 * below transcribe the locked (sender, created_at_le, type_code, plaintext,
 * nonce, blake2s_256) tuples verbatim and assert both the digest literal AND
 * the boolean verify(), which is true cross-platform byte-for-byte parity. The
 * iOS twin (ProofOfWorkTests.swift) transcribes the same literals.
 *
 * mine()/verify() take a targetBits parameter whose production default is 20
 * (ADR-pinned, ~1M BLAKE2s average). The round-trip tests pass an 8-bit target
 * so the mine/verify code path runs in milliseconds; production never calls with
 * a non-default target. mine() is CPU-bound, so the tests use runBlocking (NOT
 * runTest, whose virtual-time TestScheduler cannot track a real dispatcher loop
 * and reports UncompletedCoroutinesError).
 */
class ProofOfWorkTest {

    private val sender = ByteArray(16) { 0x0A }
    private val createdAt = byteArrayOf(1, 0, 0, 0)   // little-endian uint32 = epoch second 1
    private val plaintext = "hello".toByteArray()
    private val easyTarget = 8   // ~256 hashes average; exercises the path without a real search

    private fun hex(b: ByteArray): String =
        b.joinToString("") { "%02x".format(it) }

    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { i ->
            ((Character.digit(s[i * 2], 16) shl 4) or
                Character.digit(s[i * 2 + 1], 16)).toByte()
        }

    // --- locked KAT (crypto/gmp21_vectors.json pow cases) ---

    // pow_20bit_message_help: sender 00..0f, created_at_le = epoch 1, type MESSAGE,
    // plaintext "help", target 20 bits.
    private val katSender = hex("000102030405060708090a0b0c0d0e0f")
    private val katCreatedAtLe = byteArrayOf(1, 0, 0, 0)   // 01000000 = LE epoch 1
    private val katPlaintext = hex("68656c70")             // "help"
    private val katNonce20 = hex("00000000000a40d7")
    private val katDigest20 = "00000c2aa22402bcc4040a3fb91c95e54495c18f86c4eae5c37aef702e7f8963"

    // pow_8bit_message_help: same inputs, target 8 bits.
    private val katNonce8 = hex("0000000000000142")
    private val katDigest8 = "00513306e730855b5c2547a43ea20e4172f09622841ec34806feb96d69294e61"

    @Test
    fun `locked 20-bit KAT digest reproduces the Python reference`() {
        // The canonical preimage must hash to the locked BLAKE2s-256 literal.
        assertEquals(
            katDigest20,
            hex(ProofOfWork.digest(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)),
        )
    }

    @Test
    fun `locked 20-bit KAT nonce verifies at the production target`() {
        assertTrue(
            ProofOfWork.verify(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = ProofOfWork.TARGET_BITS),
        )
    }

    @Test
    fun `locked 8-bit KAT digest reproduces the Python reference`() {
        assertEquals(
            katDigest8,
            hex(ProofOfWork.digest(katNonce8, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)),
        )
    }

    @Test
    fun `locked 8-bit KAT nonce verifies at the 8-bit target and fails at 20-bit`() {
        assertTrue(
            ProofOfWork.verify(katNonce8, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = 8),
        )
        // Only the top 8 bits are zero; the 20-bit production target rejects it.
        assertFalse(
            ProofOfWork.verify(katNonce8, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = ProofOfWork.TARGET_BITS),
        )
    }

    // --- mine/verify round-trip (LE created_at) ---

    @Test
    fun `mined nonce is 8 bytes and verifies at the production target shape`() = runBlocking {
        // Cold-start mine at the easy target returns an 8-byte nonce that verifies.
        val nonce = ProofOfWork.mine(sender, createdAt, TypeV2.MESSAGE.code, plaintext, targetBits = easyTarget)
        assertEquals(ProofOfWork.NONCE_BYTES, nonce.size)
        assertTrue(ProofOfWork.verify(nonce, sender, createdAt, TypeV2.MESSAGE.code, plaintext, targetBits = easyTarget))
    }

    @Test
    fun `a zero nonce does not verify for fresh content`() {
        val zero = ByteArray(ProofOfWork.NONCE_BYTES)
        assertFalse(ProofOfWork.verify(zero, sender, createdAt, TypeV2.MESSAGE.code, plaintext, targetBits = easyTarget))
    }

    @Test
    fun `mined nonce bound to one plaintext does not verify a different one`() = runBlocking {
        val nonce = ProofOfWork.mine(sender, createdAt, TypeV2.MESSAGE.code, plaintext, targetBits = easyTarget)
        assertFalse(ProofOfWork.verify(nonce, sender, createdAt, TypeV2.MESSAGE.code, "world".toByteArray(), targetBits = easyTarget))
    }

    @Test
    fun `mined nonce bound to one type code does not verify a different type`() = runBlocking {
        val nonce = ProofOfWork.mine(sender, createdAt, TypeV2.MESSAGE.code, plaintext, targetBits = easyTarget)
        assertFalse(ProofOfWork.verify(nonce, sender, createdAt, TypeV2.SOS.code, plaintext, targetBits = easyTarget))
    }

    @Test
    fun `production 20-bit target rejects an 8-bit nonce`() = runBlocking {
        // An 8-bit-mined nonce has only its top 8 bits zero; the 20-bit production
        // target demands 20, so the same nonce must fail at the harder target.
        val nonce = ProofOfWork.mine(sender, createdAt, TypeV2.MESSAGE.code, plaintext, targetBits = easyTarget)
        assertFalse(ProofOfWork.verify(nonce, sender, createdAt, TypeV2.MESSAGE.code, plaintext, targetBits = ProofOfWork.TARGET_BITS))
    }
}