package io.godstone.mesh

import io.godstone.mesh.router.ProofOfWork
import io.godstone.mesh.wire.v2.TypeV2
import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * Recipient-side GMP/2.1 proof-of-work (ADR-001 §3, Stage 3 Phase C / C4).
 *
 * The nonce lives inside the sealed payload; the recipient verifies it after
 * SealedSender.open. This test pins the canonical preimage byte-for-byte against
 * crypto/gmp21_vectors.json (generated by the independent Python reference
 * crypto/gmp21.py, hashlib.blake2s):
 *
 *     BLAKE2s-256(pow_nonce[8] ‖ sender_node_id[16] ‖ created_at_le[4] ‖
 *                 type_code[1] ‖ plaintext)
 *
 * created_at is serialised LITTLE-ENDIAN -- the same canonical encoding used by
 * MessageId.derive (§3.3 created_at_le) and the sealed payload.
 *
 * DETERMINISM. Every assertion here is deterministic -- none rely on a weak
 * target coincidentally rejecting content (a 1/2^target coin flip that flakes
 * ~1/256 at the 8-bit test target, which the pre-Stage-3 form hit on iOS CI).
 * The KAT tests transcribe the locked tuples and assert the digest literal AND
 * verify(). The binding tests assert `digest(field=X) != digest(field=Y)` --
 * BLAKE2s collision resistance makes this certain and proves the field is part
 * of the preimage with no coin flip. The zero-nonce test uses the locked KAT
 * content: the Python mine is a deterministic big-endian increment from zero, so
 * the locked 20-bit solution 0x0a40d7 PROVES nonces 0..0x0a40d6 (including zero)
 * all fail at 20 bits. The iOS twin (ProofOfWorkTests.swift) is identical in
 * structure and transcribes the same literals.
 */
class ProofOfWorkTest {

    private fun hex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }
    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { i ->
            ((Character.digit(s[i * 2], 16) shl 4) or
                Character.digit(s[i * 2 + 1], 16)).toByte()
        }

    // --- locked KAT (crypto/gmp21_vectors.json pow cases) ---

    // pow_20bit_message_help: sender 00..0f, created_at_le = epoch 1, type MESSAGE,
    // plaintext "help", target 20 bits.
    private val katSender = hex("000102030405060708090a0b0c0d0e0f")
    private val katCreatedAtLe = byteArrayOf(1, 0, 0, 0)   // 01000000 = LE epoch 1
    private val katPlaintext = hex("68656c70")             // "help"
    private val katNonce20 = hex("00000000000a40d7")
    private val katDigest20 = "00000c2aa22402bcc4040a3fb91c95e54495c18f86c4eae5c37aef702e7f8963"

    // pow_8bit_message_help: same inputs, target 8 bits.
    private val katNonce8 = hex("0000000000000142")
    private val katDigest8 = "00513306e730855b5c2547a43ea20e4172f09622841ec34806feb96d69294e61"

    // A second sender / created_at / plaintext for the binding tests.
    private val altSender = hex("0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a")
    private val altCreatedAtLe = byteArrayOf(2, 0, 0, 0)   // 02000000 = LE epoch 2
    private val altPlaintext = hex("776f726c64")           // "world"

    private fun digest(nonce: ByteArray, sender: ByteArray, createdAt: ByteArray,
                       type: Byte, plain: ByteArray) =
        ProofOfWork.digest(nonce, sender, createdAt, type, plain)

    @Test
    fun `locked 20-bit KAT digest reproduces the Python reference`() {
        assertEquals(
            katDigest20,
            hex(digest(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)),
        )
    }

    @Test
    fun `locked 20-bit KAT nonce verifies at the production target`() {
        assertTrue(
            ProofOfWork.verify(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = ProofOfWork.TARGET_BITS),
        )
    }

    @Test
    fun `locked 8-bit KAT digest reproduces the Python reference`() {
        assertEquals(
            katDigest8,
            hex(digest(katNonce8, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)),
        )
    }

    @Test
    fun `locked 8-bit KAT nonce verifies at 8-bit and fails at 20-bit`() {
        assertTrue(
            ProofOfWork.verify(katNonce8, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = 8),
        )
        // The locked 8-bit digest is 00513306... -- top 8 bits zero, but bits
        // 8-19 (0x513...) are nonzero, so the 20-bit production target rejects
        // it. Deterministic: the digest literal fixes this.
        assertFalse(
            ProofOfWork.verify(katNonce8, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = ProofOfWork.TARGET_BITS),
        )
    }

    @Test
    fun `zero nonce fails at the production target for KAT content`() {
        // The Python mine is a deterministic big-endian increment from zero. The
        // locked 20-bit solution is 0x00000000000a40d7, which PROVES nonces
        // 0x0 .. 0x0a40d6 (including the all-zero nonce) all fail at 20 bits for
        // this content. So verify(zeroNonce, ..., 20) is deterministically false.
        val zero = ByteArray(ProofOfWork.NONCE_BYTES)
        assertFalse(
            ProofOfWork.verify(zero, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = ProofOfWork.TARGET_BITS),
        )
    }

    // --- binding (deterministic via digest inequality; no weak-target coin flip) ---

    @Test
    fun `digest binds the type code`() {
        val m = digest(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)
        val s = digest(katNonce20, katSender, katCreatedAtLe, TypeV2.SOS.code, katPlaintext)
        assertNotEquals(m.toList(), s.toList())
    }

    @Test
    fun `digest binds the plaintext`() {
        val a = digest(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)
        val b = digest(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, altPlaintext)
        assertNotEquals(a.toList(), b.toList())
    }

    @Test
    fun `digest binds the sender`() {
        val a = digest(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)
        val b = digest(katNonce20, altSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)
        assertNotEquals(a.toList(), b.toList())
    }

    @Test
    fun `digest binds created_at`() {
        val a = digest(katNonce20, katSender, katCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)
        val b = digest(katNonce20, katSender, altCreatedAtLe, TypeV2.MESSAGE.code, katPlaintext)
        assertNotEquals(a.toList(), b.toList())
    }

    // --- mine/verify round-trip (deterministic: mine guarantees verify) ---

    @Test
    fun `mined nonce is 8 bytes and verifies at the easy target`() = runBlocking {
        // mine() returns only when topBitsZero is true, so the returned nonce
        // verifies at the requested target by construction -- no coin flip.
        val nonce = ProofOfWork.mine(altSender, katCreatedAtLe, TypeV2.MESSAGE.code, altPlaintext, targetBits = 8)
        assertEquals(ProofOfWork.NONCE_BYTES, nonce.size)
        assertTrue(ProofOfWork.verify(nonce, altSender, katCreatedAtLe, TypeV2.MESSAGE.code, altPlaintext, targetBits = 8))
    }
}