package io.godstone.mesh

import io.godstone.mesh.router.ProofOfWork
import io.godstone.mesh.wire.v2.TypeV2
import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * Recipient-side GMP/2.1 proof-of-work (ADR-001 §3, C6.7.1).
 *
 * The nonce lives inside the sealed payload; the recipient verifies it after
 * SealedSender.open and msg_id verification. This test pins the canonical preimage
 * byte-for-byte against crypto/gmp21_vectors.json (generated by the independent
 * Python reference crypto/gmp21.py, hashlib.blake2s):
 *
 *     BLAKE2s-256(ASCII("GMP2-POW") ‖ pow_nonce[8] ‖ sender_node_id[16] ‖ created_at_le[4] ‖
 *                 message_nonce[16] ‖ type_code[1] ‖ plaintext)
 *
 * created_at is serialised LITTLE-ENDIAN -- the same canonical encoding used by
 * MessageId.derive (§3.3 created_at_le) and the sealed payload.
 *
 * message_nonce is bound to prevent PoW reuse across distinct logical message sends.
 */
class ProofOfWorkTest {

    private fun hex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }
    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { i ->
            ((Character.digit(s[i * 2], 16) shl 4) or
                Character.digit(s[i * 2 + 1], 16)).toByte()
        }

    // --- locked KAT (crypto/gmp21_vectors.json pow cases) ---

    // pow_20bit_message_help_group: sender 00..0f, created_at_le = epoch 1, priority GROUP (2),
    // type MESSAGE, message_nonce 0101...01, plaintext "help", target 20 bits.
    private val katSender = hex("000102030405060708090a0b0c0d0e0f")
    private val katCreatedAtLe = byteArrayOf(1, 0, 0, 0)   // 01000000 = LE epoch 1
    private val katMessageNonce = hex("01010101010101010101010101010101")
    private val katPlaintext = hex("68656c70")             // "help"
    private val katPriorityGroup: Byte = 2                 // GROUP
    private val katNonce20 = hex("00000000000fe48c")
    private val katDigest20 = "00000f3615a49552df8cb9941dc1a7316ba5de36a79089b84a4d26d9a8036cea"

    // pow_8bit_message_help_group: same inputs, target 8 bits.
    private val katNonce8 = hex("00000000000000c2")
    private val katDigest8 = "00737167d06eef12d0bab941a4ac8529b91ed7768408527f5d47d02c229fec51"

    // Mutated nonces, priorities, and second values for binding tests.
    private val altPriorityBroadcast: Byte = 3             // BROADCAST
    private val altPriorityDirect: Byte = 1                // DIRECT
    private val altMessageNonce = hex("00000000000000000000000000000000")
    private val altSender = hex("0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a")
    private val altCreatedAtLe = byteArrayOf(2, 0, 0, 0)   // 02000000 = LE epoch 2
    private val altPlaintext = hex("776f726c64")           // "world"

    private fun digest(
        nonce: ByteArray, sender: ByteArray, createdAt: ByteArray,
        msgNonce: ByteArray, priority: Byte, type: Byte, plain: ByteArray
    ) = ProofOfWork.digest(nonce, sender, createdAt, msgNonce, priority, type, plain)

    @Test
    fun `locked 20-bit KAT digest reproduces the Python reference`() {
        assertEquals(
            katDigest20,
            hex(digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)),
        )
    }

    @Test
    fun `locked 20-bit KAT nonce verifies at the production target`() {
        assertTrue(
            ProofOfWork.verify(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = ProofOfWork.TARGET_BITS),
        )
    }

    @Test
    fun `locked 8-bit KAT digest reproduces the Python reference`() {
        assertEquals(
            katDigest8,
            hex(digest(katNonce8, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)),
        )
    }

    @Test
    fun `locked 8-bit KAT nonce verifies at 8-bit and fails at 20-bit`() {
        assertTrue(
            ProofOfWork.verify(katNonce8, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = 8),
        )
        assertFalse(
            ProofOfWork.verify(katNonce8, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = ProofOfWork.TARGET_BITS),
        )
    }

    @Test
    fun `zero nonce fails at the production target for KAT content`() {
        val zero = ByteArray(ProofOfWork.NONCE_BYTES)
        assertFalse(
            ProofOfWork.verify(zero, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext,
                targetBits = ProofOfWork.TARGET_BITS),
        )
    }

    /**
     * LOAD-BEARING: PoW mined for message_nonce A MUST fail verification when tested against message_nonce B.
     */
    @Test
    fun `pow nonce mined for message_nonce A fails verification when evaluated against message_nonce B`() {
        // katNonce20 is valid for katMessageNonce at 20 bits
        assertTrue(
            ProofOfWork.verify(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext, 20)
        )
        // With altMessageNonce (zero), verification MUST fail
        assertFalse(
            ProofOfWork.verify(katNonce20, katSender, katCreatedAtLe, altMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext, 20)
        )
    }

    /**
     * LOAD-BEARING: PoW mined for GROUP priority MUST fail verification when evaluated against BROADCAST or DIRECT.
     */
    @Test
    fun `pow nonce mined for GROUP priority fails verification when evaluated against BROADCAST or DIRECT priority`() {
        // katNonce20 is valid for katPriorityGroup at 20 bits
        assertTrue(
            ProofOfWork.verify(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext, 20)
        )
        // With altPriorityBroadcast (3), verification MUST fail
        assertFalse(
            ProofOfWork.verify(katNonce20, katSender, katCreatedAtLe, katMessageNonce, altPriorityBroadcast, TypeV2.MESSAGE.code, katPlaintext, 20)
        )
        // With altPriorityDirect (1), verification MUST fail
        assertFalse(
            ProofOfWork.verify(katNonce20, katSender, katCreatedAtLe, katMessageNonce, altPriorityDirect, TypeV2.MESSAGE.code, katPlaintext, 20)
        )
    }

    // --- binding (deterministic via digest inequality) ---

    @Test
    fun `digest binds the message_nonce`() {
        val a = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        val b = digest(katNonce20, katSender, katCreatedAtLe, altMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        assertNotEquals(a.toList(), b.toList())
    }

    @Test
    fun `digest binds the priorityCode`() {
        val g = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        val bc = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, altPriorityBroadcast, TypeV2.MESSAGE.code, katPlaintext)
        val d = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, altPriorityDirect, TypeV2.MESSAGE.code, katPlaintext)
        assertNotEquals(g.toList(), bc.toList())
        assertNotEquals(g.toList(), d.toList())
    }

    @Test
    fun `digest binds the type code`() {
        val m = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        val s = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.SOS.code, katPlaintext)
        assertNotEquals(m.toList(), s.toList())
    }

    @Test
    fun `digest binds the plaintext`() {
        val a = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        val b = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, altPlaintext)
        assertNotEquals(a.toList(), b.toList())
    }

    @Test
    fun `digest binds the sender`() {
        val a = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        val b = digest(katNonce20, altSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        assertNotEquals(a.toList(), b.toList())
    }

    @Test
    fun `digest binds created_at`() {
        val a = digest(katNonce20, katSender, katCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        val b = digest(katNonce20, katSender, altCreatedAtLe, katMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, katPlaintext)
        assertNotEquals(a.toList(), b.toList())
    }

    // --- mine/verify round-trip ---

    @Test
    fun `mined nonce is 8 bytes and verifies at the easy target`() = runBlocking {
        val nonce = ProofOfWork.mine(altSender, katCreatedAtLe, altMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, altPlaintext, targetBits = 8)
        assertEquals(ProofOfWork.NONCE_BYTES, nonce.size)
        assertTrue(ProofOfWork.verify(nonce, altSender, katCreatedAtLe, altMessageNonce, katPriorityGroup, TypeV2.MESSAGE.code, altPlaintext, targetBits = 8))
    }
}