import Foundation

// Hand-written runtime helper -- NOT a codegen artifact. The Swift twin of
// android/.../router/BloomDigest.kt. Stage 3 Phase C pins both runtimes to the
// locked crypto/gmp21_vectors.json fixture (generated by crypto/gmp21.py) so
// the 512-byte filter and 20-byte shortDigest are byte-identical across
// platforms.

/// Bloom filter of held msg_ids, exchanged so two peers can determine what the
/// other is missing without enumerating everything they hold.
///
/// 4096 bits, 4 hashes, roughly 0.9% false-positive rate at 2000 messages.
/// A false positive means we fail to offer a message the peer actually lacks;
/// the next encounter, or a different carrier, corrects it. That is acceptable
/// in an epidemic protocol and far cheaper than exchanging full id lists.
///
/// GMP/2.1 (ADR-001 §3.4): the hash input is the full 16-byte msg_id
/// concatenated with the round index as a big-endian uint32 (20 bytes total),
/// hashed with BLAKE2s-64 (8-byte digest) and reduced mod 4096. Four rounds.
/// The 20-byte shortDigest (first 20 bytes of the 512-byte filter) is carried
/// in the BLE advertisement.
///
/// The msg_id is a 16-byte content-derived BLOB (MessageId.derive). This is
/// the byte-for-byte twin of Android `BloomDigest`; parity is pinned by
/// BloomDigestTests against crypto/gmp21_vectors.json. (The pre-Stage-3 iOS
/// form hashed `id ‖ UInt8(round)` = 17 bytes, which could never agree with
/// Android's 20-byte input -- fixed here.)
public final class BloomDigest {

    public static let sizeBits = 4096
    public static let sizeBytes = sizeBits / 8   // 512
    public static let shortBytes = 20
    public static let hashes = 4

    private var bits: [UInt8]

    public init(_ bytes: [UInt8] = [UInt8](repeating: 0, count: BloomDigest.sizeBytes)) {
        precondition(bytes.count == BloomDigest.sizeBytes, "bad digest size \(bytes.count)")
        self.bits = bytes
    }

    public func add(_ msgId: Data) {
        precondition(msgId.count == 16, "msg_id must be 16 bytes")
        for r in 0..<BloomDigest.hashes {
            let idx = BloomDigest.index(msgId, r)
            bits[idx >> 3] |= UInt8(1 << (idx & 7))
        }
    }

    public func mightContain(_ msgId: Data) -> Bool {
        precondition(msgId.count == 16, "msg_id must be 16 bytes")
        for r in 0..<BloomDigest.hashes {
            let idx = BloomDigest.index(msgId, r)
            if bits[idx >> 3] & UInt8(1 << (idx & 7)) == 0 { return false }
        }
        return true
    }

    public func toBytes() -> Data { Data(bits) }

    /// 20-byte truncation carried in the BLE advertisement (ADR-001 §3.4).
    public func shortDigest() -> Data { Data(bits.prefix(BloomDigest.shortBytes)) }

    /// Build a 512-byte digest from a list of message ids (convenience used by
    /// Router.bloomDigest()).
    public static func build(from ids: [Data]) -> Data {
        let bloom = BloomDigest()
        for id in ids { bloom.add(id) }
        return bloom.toBytes()
    }

    public static func fromBytes(_ b: Data) -> BloomDigest {
        precondition(b.count == sizeBytes, "bad digest size \(b.count)")
        return BloomDigest([UInt8](b))
    }

    /// §3.4: BLAKE2s-64(msg_id[16] ‖ uint32_be(round)) mod 4096.
    ///
    /// The 8-byte digest is read big-endian, shifted unsigned right by 1,
    /// masked to Int32.max (bit 31 clear) and reduced mod 4096 -- identical to
    /// Android BloomDigest.index.
    static func index(_ msgId: Data, _ round: Int) -> Int {
        var input = Data(capacity: 16 + 4)
        input.append(msgId)
        // uint32_be(round): big-endian round index.
        input.append(UInt8((round >> 24) & 0xFF))
        input.append(UInt8((round >> 16) & 0xFF))
        input.append(UInt8((round >> 8) & 0xFF))
        input.append(UInt8(round & 0xFF))
        let digest = Blake2s.hash(input, digestLength: 8)
        let value = digest.withUnsafeBytes { ptr -> UInt64 in
            ptr.load(as: UInt64.self).bigEndian
        }
        return Int((value >> 1) & UInt64(Int32.max)) % sizeBits
    }
}