package io.godstone.mesh.router

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * GMP/2.1 Bloom byte-parity (ADR-001 §3.4, Stage 3 Phase C / C3).
 *
 * The expected per-round indices and 20-byte shortDigest are transcribed
 * verbatim from crypto/gmp21_vectors.json, generated by the independent Python
 * reference crypto/gmp21.py (hashlib.blake2s, RFC 7693). The full 512-byte
 * filter is NOT transcribed as a 1024-char literal (too fragile); instead the
 * expected filter is reconstructed from the locked indices -- set exactly
 * those bits and no others -- and compared to the built filter, which proves
 * the runtime sets exactly the locked bits. Together with the locked
 * shortDigest and the per-round index checks, this is byte-for-byte parity
 * with the Python reference and the iOS twin (BloomDigestTests.swift). The
 * msg_ids here are the outputs of the locked msg_id vectors (MessageIdTest),
 * so the whole content-derived chain is pinned end-to-end.
 */
class BloomDigestTest {

    private fun hex(b: String): ByteArray =
        ByteArray(b.length / 2) { i ->
            ((Character.digit(b[i * 2], 16) shl 4) or
                Character.digit(b[i * 2 + 1], 16)).toByte()
        }

    private fun String.toBytes() = hex(this)

    /** Build the expected 512-byte filter from locked indices: set exactly
     *  those bits, no others. */
    private fun filterFromIndices(indices: List<List<Int>>): ByteArray {
        val bits = ByteArray(BloomDigest.SIZE_BYTES)
        for (rounds in indices) {
            for (idx in rounds) {
                bits[idx ushr 3] = (bits[idx ushr 3].toInt() or (1 shl (idx and 7))).toByte()
            }
        }
        return bits
    }

    // msg_ids transcribed from crypto/gmp21_vectors.json msg_id.cases.
    private val mid1 = "fe9c55924a94692c6721d13c3d06ca5a".toBytes()
    private val mid2 = "b0fcd6858d4a0e24b434dfcf273ff20c".toBytes()
    private val mid3 = "ea5260efb0ab65829f02042a7237a2cb".toBytes()

    // locked round indices from crypto/gmp21_vectors.json bloom.cases.
    private val mid2Indices = listOf(2523, 2404, 87, 3945)
    private val mid1Indices = listOf(1382, 2642, 146, 1866)
    private val mid3Indices = listOf(1899, 3452, 3561, 2086)

    // --- single-id case (bloom.cases[0]) ---

    @Test
    fun `single id round indices reproduce locked vector`() {
        assertEquals(mid2Indices, (0 until BloomDigest.HASHES).map { idx(mid2, it) })
    }

    @Test
    fun `single id filter reproduces locked indices`() {
        val bloom = BloomDigest().apply { add(mid2) }
        assertEquals(
            filterFromIndices(listOf(mid2Indices)).toList(),
            bloom.toBytes().toList(),
        )
    }

    @Test
    fun `single id short digest reproduces locked vector`() {
        val bloom = BloomDigest().apply { add(mid2) }
        assertEquals(
            "0000000000000000000080000000000000000000",
            bloom.shortDigest().joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `single id might contain is true for member and false for non member`() {
        val bloom = BloomDigest().apply { add(mid2) }
        assertTrue(bloom.mightContain(mid2))
        // mid1's indices [1382,2642,146,1866] do not collide with mid2's, so it
        // must report absent (proves no stray bits were set).
        assertFalse(bloom.mightContain(mid1))
    }

    // --- three-id case (bloom.cases[1]) ---

    @Test
    fun `three id round indices reproduce locked vector`() {
        assertEquals(mid1Indices, (0 until BloomDigest.HASHES).map { idx(mid1, it) })
        assertEquals(mid2Indices, (0 until BloomDigest.HASHES).map { idx(mid2, it) })
        assertEquals(mid3Indices, (0 until BloomDigest.HASHES).map { idx(mid3, it) })
    }

    @Test
    fun `three id filter reproduces locked indices`() {
        val bloom = BloomDigest().apply { add(mid1); add(mid2); add(mid3) }
        assertEquals(
            filterFromIndices(listOf(mid1Indices, mid2Indices, mid3Indices)).toList(),
            bloom.toBytes().toList(),
        )
    }

    @Test
    fun `three id short digest reproduces locked vector`() {
        val bloom = BloomDigest().apply { add(mid1); add(mid2); add(mid3) }
        assertEquals(
            "0000000000000000000080000000000000000400",
            bloom.shortDigest().joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `three id might contain is true for all members`() {
        val bloom = BloomDigest().apply { add(mid1); add(mid2); add(mid3) }
        assertTrue(bloom.mightContain(mid1))
        assertTrue(bloom.mightContain(mid2))
        assertTrue(bloom.mightContain(mid3))
    }

    @Test
    fun `fromBytes round trips a built filter`() {
        val built = BloomDigest().apply { add(mid2) }.toBytes()
        val restored = BloomDigest.fromBytes(built)
        assertTrue(restored.mightContain(mid2))
        assertFalse(restored.mightContain(mid1))
    }

    /** Independent re-derivation of the §3.4 reduction, to pin the per-round
     *  index against the locked Python values without relying on the class
     *  internals. The full-filter and shortDigest checks anchor the class
     *  itself; this names the exact round that diverges if one ever does. */
    private fun idx(msgId: ByteArray, round: Int): Int {
        val d = org.bouncycastle.crypto.digests.Blake2sDigest(null, 8, null, null)
        d.update(msgId, 0, msgId.size)
        val rb = java.nio.ByteBuffer.allocate(4).putInt(round).array()
        d.update(rb, 0, 4)
        val out = ByteArray(8)
        d.doFinal(out, 0)
        val v = java.nio.ByteBuffer.wrap(out).getLong()
        return ((v ushr 1).toInt() and Int.MAX_VALUE) % BloomDigest.SIZE_BITS
    }
}