import XCTest
@testable import GodstoneMesh
@testable import GodstoneCore

/// GMP/2.1 Bloom byte-parity (ADR-001 §3.4, Stage 3 Phase C / C3).
///
/// The expected per-round indices and 20-byte shortDigest are transcribed
/// verbatim from crypto/gmp21_vectors.json, generated by the independent Python
/// reference crypto/gmp21.py (hashlib.blake2s, RFC 7693). The full 512-byte
/// filter is reconstructed from the locked indices (set exactly those bits, no
/// others) and compared to the built filter, which proves the runtime sets
/// exactly the locked bits without a fragile 1024-char literal. Together with
/// the locked shortDigest and per-round index checks, this is byte-for-byte
/// parity with the Python reference and the Android twin (BloomDigestTest.kt).
/// The pre-Stage-3 iOS form hashed `id ‖ UInt8(round)` = 17 bytes and could
/// never agree -- fixed in BloomDigest.swift.
final class BloomDigestTests: XCTestCase {

    private func data(fromHex hex: String) -> Data {
        var bytes = [UInt8]()
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            bytes.append(UInt8(hex[index..<next], radix: 16)!)
            index = next
        }
        return Data(bytes)
    }

    private func hex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    /// Build the expected 512-byte filter from locked indices: set exactly
    /// those bits, no others.
    private func filterFromIndices(_ indexGroups: [[Int]]) -> Data {
        var bits = [UInt8](repeating: 0, count: BloomDigest.sizeBytes)
        for rounds in indexGroups {
            for idx in rounds {
                bits[idx >> 3] |= UInt8(1 << (idx & 7))
            }
        }
        return Data(bits)
    }

    // msg_ids transcribed from crypto/gmp21_vectors.json msg_id.cases.
    private var mid1: Data { data(fromHex: "fe9c55924a94692c6721d13c3d06ca5a") }
    private var mid2: Data { data(fromHex: "b0fcd6858d4a0e24b434dfcf273ff20c") }
    private var mid3: Data { data(fromHex: "ea5260efb0ab65829f02042a7237a2cb") }

    // locked round indices from crypto/gmp21_vectors.json bloom.cases.
    private let mid1Indices = [1382, 2642, 146, 1866]
    private let mid2Indices = [2523, 2404, 87, 3945]
    private let mid3Indices = [1899, 3452, 3561, 2086]

    // --- single-id case (bloom.cases[0]) ---

    func testSingleIdRoundIndices() {
        let got = (0..<BloomDigest.hashes).map { BloomDigest.index(mid2, $0) }
        XCTAssertEqual(mid2Indices, got)
    }

    func testSingleIdFilter() {
        let bloom = BloomDigest()
        bloom.add(mid2)
        XCTAssertEqual(filterFromIndices([mid2Indices]), bloom.toBytes())
    }

    func testSingleIdShortDigest() {
        let bloom = BloomDigest()
        bloom.add(mid2)
        XCTAssertEqual("0000000000000000000080000000000000000000",
                       hex(bloom.shortDigest()))
    }

    func testSingleIdMightContain() {
        let bloom = BloomDigest()
        bloom.add(mid2)
        XCTAssertTrue(bloom.mightContain(mid2))
        // mid1's indices do not collide with mid2's, so it must report absent.
        XCTAssertFalse(bloom.mightContain(mid1))
    }

    // --- three-id case (bloom.cases[1]) ---

    func testThreeIdRoundIndices() {
        XCTAssertEqual(mid1Indices,
                       (0..<BloomDigest.hashes).map { BloomDigest.index(mid1, $0) })
        XCTAssertEqual(mid2Indices,
                       (0..<BloomDigest.hashes).map { BloomDigest.index(mid2, $0) })
        XCTAssertEqual(mid3Indices,
                       (0..<BloomDigest.hashes).map { BloomDigest.index(mid3, $0) })
    }

    func testThreeIdFilter() {
        let bloom = BloomDigest()
        bloom.add(mid1); bloom.add(mid2); bloom.add(mid3)
        XCTAssertEqual(filterFromIndices([mid1Indices, mid2Indices, mid3Indices]),
                       bloom.toBytes())
    }

    func testThreeIdShortDigest() {
        let bloom = BloomDigest()
        bloom.add(mid1); bloom.add(mid2); bloom.add(mid3)
        XCTAssertEqual("0000000000000000000080000000000000000400",
                       hex(bloom.shortDigest()))
    }

    func testThreeIdMightContainAllMembers() {
        let bloom = BloomDigest()
        bloom.add(mid1); bloom.add(mid2); bloom.add(mid3)
        XCTAssertTrue(bloom.mightContain(mid1))
        XCTAssertTrue(bloom.mightContain(mid2))
        XCTAssertTrue(bloom.mightContain(mid3))
    }

    func testFromBytesRoundTrips() {
        let bloom = BloomDigest()
        bloom.add(mid2)
        let restored = BloomDigest.fromBytes(bloom.toBytes())
        XCTAssertTrue(restored.mightContain(mid2))
        XCTAssertFalse(restored.mightContain(mid1))
    }

    func testRouterBloomDigestBuilds512Bytes() {
        // Router.bloomDigest() must still produce a 512-byte filter via the
        // rewritten BloomDigest.build(from:).
        XCTAssertEqual(512, BloomDigest.build(from: [mid2, mid3]).count)
    }
}