import XCTest
@testable import GodstoneMesh
import GodstoneCore

/// GMP/2.1 msg_id byte-parity (ADR-001 §3.3, Stage 3 Phase C / C2).
///
/// The expected `msg_id` hex literals below are transcribed verbatim from
/// crypto/gmp21_vectors.json, generated by the independent Python reference
/// crypto/gmp21.py (hashlib.blake2s, RFC 7693). A byte-identical Swift
/// `MessageId.derive` proves iOS agrees with the pinned spec spelling
/// `msg_id = BLAKE2s-128(sender ‖ created_at_le ‖ payload)` -- little-endian
/// created_at -- and with the Android twin (MessageIdTest.kt). The mutation
/// case proves the byte order is the discriminator: big-endian created_at
/// yields a different digest (e10707c3...), so a regression that flips
/// `uint32Le` back to `uint32Be` fails the positive cases AND is named here.
final class MessageIdTests: XCTestCase {

    private func data(fromHex hex: String) -> Data {
        var bytes = [UInt8]()
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            bytes.append(UInt8(hex[index..<next], radix: 16)!)
            index = next
        }
        return Data(bytes)
    }

    private func hex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    private let senderA = Data((0..<16).map { UInt8($0) })          // 000102...0f
    private let senderB = Data(repeating: 0xAA, count: 16)          // aaaa...aa

    // --- transcribed from crypto/gmp21_vectors.json msg_id.cases ---

    func testMsgIdEmptyPayloadZeroTime() {
        XCTAssertEqual(
            "fe9c55924a94692c6721d13c3d06ca5a",
            hex(MessageId.derive(senderNodeId: senderA,
                                 createdAtEpochSeconds: 0,
                                 payload: Data())))
    }

    func testMsgIdHelpEpoch1() {
        XCTAssertEqual(
            "b0fcd6858d4a0e24b434dfcf273ff20c",
            hex(MessageId.derive(senderNodeId: senderA,
                                 createdAtEpochSeconds: 1,
                                 payload: Data("help".utf8))))
    }

    func testMsgIdSosPayloadRealEpoch() {
        XCTAssertEqual(
            "ea5260efb0ab65829f02042a7237a2cb",
            hex(MessageId.derive(senderNodeId: senderB,
                                 createdAtEpochSeconds: 1700000000,
                                 payload: Data("SOS payload".utf8))))
    }

    func testMsgIdIs16Bytes() {
        XCTAssertEqual(16, MessageId.derive(senderNodeId: senderA,
                                            createdAtEpochSeconds: 1,
                                            payload: Data("help".utf8)).count)
    }

    /// Mutation: created_at encoded BIG-endian must produce the locked BE digest
    /// e10707c3..., which differs from the LE digest b0fcd685...
    func testBigEndianCreatedAtProducesDifferentLockedDigest() {
        let beInput = senderA + MessageId.uint32Be(1) + Data("help".utf8)
        let beDigest = Blake2s.hash(beInput, digestLength: 16)
        XCTAssertEqual("e10707c3ca4f77761420396d83b2a367", hex(beDigest))
        XCTAssertNotEqual("b0fcd6858d4a0e24b434dfcf273ff20c", hex(beDigest))
    }
}