import XCTest
@testable import GodstoneMesh
import GodstoneCore

/// GMP/2.1 msg_id byte-parity and logical message identity (ADR-001 §3.3, C6.7).
///
/// The expected `msg_id` hex literals below are transcribed verbatim from
/// crypto/gmp21_vectors.json, generated by the independent Python reference
/// crypto/gmp21.py (hashlib.blake2s, RFC 7693). A byte-identical Swift
/// `MessageId.derive` proves iOS agrees with the pinned spec spelling:
///     msg_id = BLAKE2s-128(b"GMP2-MSGID" ‖ sender ‖ created_at_le ‖ message_nonce ‖ plaintext)
/// and with the Android twin (MessageIdTest.kt).
final class MessageIdTests: XCTestCase {

    private func data(fromHex hex: String) -> Data {
        var bytes = [UInt8]()
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            bytes.append(UInt8(hex[index..<next], radix: 16)!)
            index = next
        }
        return Data(bytes)
    }

    private func hex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    private let senderA = Data((0..<16).map { UInt8($0) })          // 000102...0f
    private let senderB = Data(repeating: 0xAA, count: 16)          // aaaa...aa
    private let nonceZero = Data(repeating: 0x00, count: 16)
    private let nonceOnes = Data(repeating: 0x01, count: 16)
    private lazy var nonceKat = data(fromHex: "00112233445566778899aabbccddeeff")

    // --- transcribed from crypto/gmp21_vectors.json msg_id.cases ---

    func testMsgIdEmptyPayloadZeroTimeZeroNonce() {
        XCTAssertEqual(
            "0cd32fa4ac79a506b3f04008fed71e59",
            hex(MessageId.derive(senderNodeId: senderA,
                                 createdAtEpochSeconds: 0,
                                 messageNonce: nonceZero,
                                 plaintext: Data())))
    }

    func testMsgIdHelpEpoch1NonceAllOnes() {
        XCTAssertEqual(
            "b288201494ca28ee63da7c49433abcbe",
            hex(MessageId.derive(senderNodeId: senderA,
                                 createdAtEpochSeconds: 1,
                                 messageNonce: nonceOnes,
                                 plaintext: Data("help".utf8))))
    }

    func testMsgIdSosPayloadRealEpochKatNonce() {
        XCTAssertEqual(
            "6e16a5bf98f03ed1320281a55cd490ae",
            hex(MessageId.derive(senderNodeId: senderB,
                                 createdAtEpochSeconds: 1700000000,
                                 messageNonce: nonceKat,
                                 plaintext: Data("SOS payload".utf8))))
    }

    func testMsgIdIs16Bytes() {
        XCTAssertEqual(16, MessageId.derive(senderNodeId: senderA,
                                            createdAtEpochSeconds: 1,
                                            messageNonce: nonceOnes,
                                            plaintext: Data("help".utf8)).count)
    }

    /// Mutation: created_at encoded BIG-endian must produce the locked BE digest
    /// 65a85cef..., which differs from the LE digest b2882014...
    func testBigEndianCreatedAtProducesDifferentLockedDigest() {
        let beInput = MessageId.domain + senderA + MessageId.uint32Be(1) + nonceOnes + Data("help".utf8)
        let beDigest = Blake2s.hash(beInput, digestLength: 16)
        XCTAssertEqual("65a85cef9612f20bdcd938bc416b27f8", hex(beDigest))
        XCTAssertNotEqual("b288201494ca28ee63da7c49433abcbe", hex(beDigest))
    }

    /// Distinct nonces for identical content, time, and sender MUST yield distinct msg_ids.
    func testDistinctNoncesForIdenticalContentTimeProduceDistinctMsgIds() {
        let id1 = MessageId.derive(senderNodeId: senderA, createdAtEpochSeconds: 1, messageNonce: nonceOnes, plaintext: Data("help".utf8))
        let id2 = MessageId.derive(senderNodeId: senderA, createdAtEpochSeconds: 1, messageNonce: nonceZero, plaintext: Data("help".utf8))
        XCTAssertEqual("ca00c29df07276c186b57ac028a3d31c", hex(id2))
        XCTAssertNotEqual(id1, id2)
    }

    /// Missing domain separator produces a different digest.
    func testMissingDomainSeparatorProducesDifferentDigest() {
        let noDomainInput = senderA + MessageId.uint32Le(1) + nonceOnes + Data("help".utf8)
        let noDomainDigest = Blake2s.hash(noDomainInput, digestLength: 16)
        let withDomain = MessageId.derive(senderNodeId: senderA, createdAtEpochSeconds: 1, messageNonce: nonceOnes, plaintext: Data("help".utf8))
        XCTAssertNotEqual(withDomain, noDomainDigest)
    }

    /// C6.7.8: Retry stability - 100 re-derivations with the same parameters yield the exact same msg_id.
    func testRetryStabilityPreservesExactSameMsgId() {
        let content = Data("same message content".utf8)
        let baseline = MessageId.derive(senderNodeId: senderA, createdAtEpochSeconds: 123456789, messageNonce: nonceKat, plaintext: content)
        for i in 1...100 {
            let retry = MessageId.derive(senderNodeId: senderA, createdAtEpochSeconds: 123456789, messageNonce: nonceKat, plaintext: content)
            XCTAssertEqual(baseline, retry, "Retry \(i) diverged from baseline msg_id")
        }
    }

    /// C6.7.10: Alice vs Bob concurrent sends at same timestamp with same content receive distinct msg_ids.
    func testAliceVsBobConcurrentSendsAtSameSecondReceiveDistinctMsgIds() {
        let timestamp: Int64 = 1710000000
        let content = Data("meet at medical station".utf8)
        let nonceForAlice = MessageId.generateNonce()
        let nonceForBob = MessageId.generateNonce()
        XCTAssertNotEqual(nonceForAlice, nonceForBob)

        let msgIdForAlice = MessageId.derive(senderNodeId: senderA, createdAtEpochSeconds: timestamp, messageNonce: nonceForAlice, plaintext: content)
        let msgIdForBob = MessageId.derive(senderNodeId: senderA, createdAtEpochSeconds: timestamp, messageNonce: nonceForBob, plaintext: content)

        XCTAssertNotEqual(msgIdForAlice, msgIdForBob)
    }
}