import XCTest
import Foundation
import CryptoKit
@testable import GodstoneMesh
import GodstoneCore

// T38 readiness court (iOS isle) -- the twin of ReadinessT38Test.kt.
//
// One signed SOS envelope: keep the outer SOS code and required flags and the
// canonical signature rule (section 15). The vectors of
// crypto/sos_v1_vectors.json (schema 1, generated by
// crypto/gen_sos_v1_vectors.py) are the single source of truth for BOTH
// isles: this court reads the very same file at runtime (walking parents up
// from #filePath until a crypto/ sibling appears, so the canonical
// ios/Godstone and the mirrored ios/Packages layouts both resolve). The
// loader is deliberately minimal and fail-closed: the fixture is this
// repository's own artifact in the generator's known two-space layout; any
// vector missing a required member fails the witness at once.
//
// Randomized-signing doctrine (the T83 finding): the host Ed25519 layer here
// signs RANDOMIZED. So this court never byte-pins a freshly authored
// signature. What it does pin: the deterministic msg_id derivation over the
// unsigned span, the structural octets, the cross-isle golden bytes of the
// JVM-produced vectors (which the iOS verifier must ACCEPT), and the pinned
// signatures' cryptographic VALIDITY via isValidSignature over the exact
// transcript. The authorship leg proves structure and verifier acceptance;
// the signature slot must not be all zero and two out of one key must be
// distinct -- the oracle of genuine randomness, not a bug.

// ------------------------------------------------------------------ helpers

private func t38U(_ d: Data) -> [UInt8] { [UInt8](d) }
private func t38D(_ b: [UInt8]) -> Data { Data(b) }

private func t38HexVal(_ u: UInt8) -> Int {
    if u >= 0x61 { return Int(u) - 0x57 }
    if u >= 0x41 { return Int(u) - 0x37 }
    return Int(u) - 0x30
}

private func t38Hx(_ s: String) -> Data {
    let b = Array(s.utf8)
    var bytes: [UInt8] = []
    bytes.reserveCapacity(b.count / 2)
    var i = 0
    while i + 1 < b.count {
        bytes.append(UInt8((t38HexVal(b[i]) << 4) | t38HexVal(b[i + 1])))
        i += 2
    }
    return Data(bytes)
}

private func t38Ascii(_ s: String) -> Data { Data(s.utf8) }

private func t38Flipped(_ source: Data, _ at: Int) -> Data {
    var b = t38U(source)
    b[at] ^= 0x01
    return Data(b)
}

private func t38Frame(_ type: TypeV2, _ flags: Int, _ msgId: Data, _ payload: Data) -> FrameV2 {
    return FrameV2(
        type: type,
        msgId: msgId,
        routingTag: Data(repeating: 0, count: 4),
        ttl: FrameV2.maxTtl,
        hopCount: 0,
        flags: UInt16(flags),
        payload: payload)
}

private func t38Quality(_ code: Int) -> TimeQuality {
    switch code {
    case 1: return .userConfirmed
    case 2: return .authenticatedSource
    default: return .unknown
    }
}

/// One vector of the table, fields as written by the generator.
private struct T38Vec {
    let kind: String
    let name: String
    let fields: [String: String]

    func must(_ key: String) -> String {
        if let v = fields[key], v != "null" { return v }
        XCTFail("vector " + name + " lacks " + key)
        return ""
    }
    func opt(_ key: String) -> String? {
        guard let v = fields[key], v != "null" else { return nil }
        return v
    }

    var generation: UInt32 { UInt32(must("generation")) ?? 0 }
    var created: Int64 { Int64(must("created_at")) ?? -1 }
    var timeQuality: Int { Int(must("time_quality")) ?? -1 }
    var seed: Data { t38Hx(must("ed25519_seed_hex")) }
    var signPub: Data { t38Hx(must("signing_public_key")) }
    var dhPub: Data { t38Hx(must("static_dh_public_key")) }
    var node: Data { t38Hx(must("node_id")) }
    var nonce: Data { t38Hx(must("nonce_hex")) }
    var body: Data { t38Hx(must("body_hex")) }
    var binding: Data { t38Hx(must("binding_hex")) }
    var unsigned: Data { t38Hx(must("unsigned_hex")) }
    var msgId: Data { t38Hx(must("msg_id_hex")) }
    var signature: Data { t38Hx(must("signature_hex")) }
    var payload: Data { t38Hx(must("frame_payload_hex")) }
    var reason: String { must("expected_reason") }
    var headerType: Int { Int(must("header.type")) ?? -1 }
    var headerFlags: Int { Int(must("header.flags")) ?? -1 }
}

/// The witness class. One case per named card requirement; the eleven
/// witnesses mirror the android isle one for one.
final class ReadinessT38Tests: XCTestCase {

    // ---------------------------------------------------------- the fixture loader

    private static var table: [T38Vec]? = nil

    private func vectors() -> [T38Vec] {
        if let t = ReadinessT38Tests.table { return t }
        // walk parents up from this source file until crypto/sos_v1_vectors.json
        // comes into view -- resolves both the canonical and the mirrored layout
        var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        var loaded: [T38Vec] = []
        for _ in 0..<12 {
            let candidate = dir
                .appendingPathComponent("crypto")
                .appendingPathComponent("sos_v1_vectors.json")
            if let raw = try? Data(contentsOf: candidate),
               let text = String(bytes: raw, encoding: .utf8) {
                loaded = Self.scan(text)
                break
            }
            dir = dir.deletingLastPathComponent()
        }
        XCTAssertEqual(loaded.count, 16, "the table must hold sixteen vectors")
        XCTAssertEqual(loaded.filter { $0.kind == "accept" }.count, 3,
            "three accept vectors")
        XCTAssertEqual(loaded.filter { $0.kind == "reject" }.count, 13,
            "thirteen reject vectors")
        ReadinessT38Tests.table = loaded
        return loaded
    }

    /// A minimal, fail-closed scanner over the generator's known two-space
    /// layout (the fixture is this repository's own artifact). Records begin
    /// at "kind"; the nested header object's keys take a "header." prefix.
    private static func scan(_ text: String) -> [T38Vec] {
        var out: [T38Vec] = []
        var fields: [String: String] = [:]
        var kind: String? = nil
        var name: String? = nil
        var depthKey = ""
        for raw in text.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = raw.trimmingCharacters(in: CharacterSet.whitespaces)
            if line.hasPrefix("\"header\":") { depthKey = "header."; continue }
            if line == "}" || line == "}," { depthKey = ""; continue }
            if line.hasPrefix("\"kind\":") {
                if let k = kind, let n = name { out.append(T38Vec(kind: k, name: n, fields: fields)) }
                fields = [:]
                kind = valueOf(line)
                name = nil
                depthKey = ""
                continue
            }
            guard kind != nil else { continue }
            if line.hasPrefix("\"name\":"), name == nil {
                name = valueOf(line)
                continue
            }
            guard line.hasPrefix("\""), let at = line.range(of: "\": ") else { continue }
            let key = String(line[line.index(after: line.startIndex)..<at.lowerBound])
            fields[depthKey + key] = valueOf(line)
        }
        if let k = kind, let n = name { out.append(T38Vec(kind: k, name: n, fields: fields)) }
        return out
    }

    private static func valueOf(_ line: String) -> String {
        guard let at = line.range(of: "\": ") else { return "" }
        var v = String(line[at.upperBound...])
        v = v.trimmingCharacters(in: CharacterSet.whitespaces)
        if v.hasSuffix(",") { v = String(v.dropLast(1)) }
        if v.count >= 2, v.hasPrefix("\""), v.hasSuffix("\"") {
            v = String(v.dropFirst(1).dropLast(1))
        }
        return v
    }

    private func vec(_ name: String) -> T38Vec {
        guard let v = vectors().first(where: { $0.name == name }) else {
            XCTFail("no vector named " + name)
            return T38Vec(kind: "missing", name: name, fields: [:])
        }
        return v
    }

    private func unauthReason(_ result: SosAuthResult) -> SosReason? {
        if case .unauthenticated(let reason, _) = result { return reason }
        return nil
    }

    private func viewOf(_ result: SosAuthResult) -> VerifiedSos? {
        if case .authenticated(let view) = result { return view }
        return nil
    }

    private func expectRefusal(_ result: SosAuthResult, _ expected: SosReason, _ label: String) {
        guard let reason = unauthReason(result) else {
            XCTFail(label + ": the receiver must refuse")
            return
        }
        XCTAssertEqual(reason, expected, label + ": named reason")
    }

    // ---------------------------------------------------------- fixtures

    private final class FakeAuthority: SosSigningAuthority, @unchecked Sendable {
        private let seedV: Data
        private let dhV: Data
        private let generationV: UInt32
        private let clockV: Int64
        private let nonceV: Data
        var calls: Int = 0
        init(seed: Data, dhPub: Data, generation: UInt32, clock: Int64, nonce: Data) {
            self.seedV = seed; self.dhV = dhPub; self.generationV = generation
            self.clockV = clock; self.nonceV = nonce
        }
        func currentNonce() -> Data { calls += 1; return nonceV }
        func currentSigningSeed() -> Data? { seedV }
        func currentStaticDhPublicKey() -> Data? { dhV }
        func currentGeneration() -> UInt32 { generationV }
        func currentTimeEpochSeconds() -> Int64 { clockV }
    }

    private final class Watcher: SosObserver, @unchecked Sendable {
        var authenticated: Int = 0
        var unauthenticated: Int = 0
        var lastReason: SosReason?
        var lastView: VerifiedSos?
        func onSosAuthenticated(view: VerifiedSos) {
            authenticated += 1
            lastView = view
        }
        func onSosUnauthenticated(frame: FrameV2, reason: SosReason) {
            unauthenticated += 1
            lastReason = reason
        }
    }

    /// The never-exercised delivery repository of the T24 integration recipe:
    /// an inbound SOS must not reach the tracker; a call is a crash, loudly.
    private final class DeadDeliveryRepository: DeliveryRepository, @unchecked Sendable {
        func get(_ msgId: Data) -> DeliveryLookup { fatalError("the tracker path is closed to these witnesses") }
        func enqueue(_ msgId: Data, ackMode: AckMode, expectedRecipient: Data?) -> EnqueueResult {
            fatalError("the tracker path is closed to these witnesses")
        }
        func transition(_ msgId: Data, _ transition: DeliveryTransition) -> TransitionResult {
            fatalError("the tracker path is closed to these witnesses")
        }
        func acknowledgeBoundAndRetire(_ msgId: Data, expectedRecipient: Data) -> AckResult {
            fatalError("the tracker path is closed to these witnesses")
        }
        func clear(_ msgId: Data) -> ClearResult { fatalError("the tracker path is closed to these witnesses") }
    }

    /// The live ledger of the C6 sender leg (a faithful miniature of the
    /// sealed T24 in-memory journal, store-side paths pruned).
    private final class T38Journal: DeliveryRepository, @unchecked Sendable {
        var records: [Data: DeliveryRecord] = [:]
        func get(_ msgId: Data) -> DeliveryLookup {
            guard msgId.count == 16 else { return .invalidArgument }
            guard let rec = records[msgId] else { return .notFound }
            return .found(rec)
        }
        func enqueue(_ msgId: Data, ackMode: AckMode, expectedRecipient: Data?) -> EnqueueResult {
            guard msgId.count == 16 else { return .invalidArgument }
            if let old = records[msgId] {
                if old.ackMode == ackMode, old.expectedRecipientNodeId == expectedRecipient {
                    return .alreadyQueuedSameBinding
                }
                return .conflictRecipient
            }
            records[msgId] = DeliveryRecord(msgId: msgId, state: .queuedDurably,
                                            ackMode: ackMode, expectedRecipientNodeId: expectedRecipient)
            return .created
        }
        func transition(_ msgId: Data, _ transition: DeliveryTransition) -> TransitionResult {
            guard msgId.count == 16 else { return .invalidArgument }
            guard let rec = records[msgId] else { return .unknownMessage }
            var target: DeliveryState
            var validFroms: Set<DeliveryState>
            switch transition {
            case .markHanded:
                target = .handedToRelay
                validFroms = [.queuedDurably]
            case .expire:
                target = .expired
                validFroms = [.queuedDurably, .handedToRelay]
            case .cancel:
                target = .cancelledLocally
                validFroms = [.queuedDurably, .handedToRelay]
            }
            if rec.state == target { return .alreadyInTarget }
            guard validFroms.contains(rec.state) else { return .rejectedState }
            records[msgId] = DeliveryRecord(msgId: rec.msgId, state: target,
                                            ackMode: rec.ackMode,
                                            expectedRecipientNodeId: rec.expectedRecipientNodeId)
            return .applied
        }
        func acknowledgeBoundAndRetire(_ msgId: Data, expectedRecipient: Data) -> AckResult {
            guard msgId.count == 16, expectedRecipient.count == 16 else { return .invalidArgument }
            guard let rec = records[msgId] else { return .unknownMessage }
            guard rec.ackMode == .singleRecipient,
                  rec.expectedRecipientNodeId == expectedRecipient else { return .unknownMessage }
            if rec.state == .acknowledgedByRecipient { return .duplicateAuthenticatedAck }
            records[msgId] = DeliveryRecord(msgId: rec.msgId, state: .acknowledgedByRecipient,
                                            ackMode: rec.ackMode,
                                            expectedRecipientNodeId: rec.expectedRecipientNodeId)
            return .applied
        }
        func clear(_ msgId: Data) -> ClearResult {
            guard msgId.count == 16 else { return .invalidArgument }
            return records.removeValue(forKey: msgId) != nil ? .cleared : .alreadyAbsent
        }
    }

    private func newIdentity(_ seedByte: UInt8, _ xByte: UInt8) throws -> MeshIdentity {
        let state = try LocalIdentityStateV1(generation: 0,
            ed25519Seed: Data(repeating: seedByte, count: 32),
            x25519PrivateKey: Data(repeating: xByte, count: 32))
        let kc = InMemoryKeychain()
        kc.storage[MeshIdentity.v1Tag] = state.encode()
        return try MeshIdentity.loadFromKeychain(keychain: kc)
    }

    private func composingNode(_ store: InMemoryMessageStore, _ observer: Watcher?,
                                repo: DeliveryRepository) throws -> MeshNode {
        let node = MeshNode(
            identity: try newIdentity(0xB1, 0xD7),
            store: store,
            deliveryTracker: DeliveryTracker(
                repo: repo,
                authenticator: Ed25519AckAuthenticator(resolver: UnresolvedRecipientKeyResolver())))
        node.sosObserver = observer
        return node
    }

    // ---------------------------------------------------------- W1 golden vectors

    /** W1 -- author/verify across the isles: the pinned msg_id re-derives
     *  byte for byte over the unsigned span (the frozen formula), the pinned
     *  signature VERIFIES cryptographically over msg_id || "SOS1" || unsigned
     *  (the JVM-struck seal stands under the iOS verifier), a freshly
     *  authored envelope carries the fixed outer fields, keeps its msg_id
     *  deterministic, shows a live (non-zero, distinct) signature slot --
     *  randomized signing, proven -- and authenticates under the node its
     *  key binds to. */
    func testAuthorProducesVerifiableSignatureAcrossIsles() throws {
        for v in vectors().filter({ $0.kind == "accept" }) {
            let unsigned = try XCTUnwrap(
                SignedSosV1.unsignedPayload(binding: v.binding, createdAtEpochSeconds: v.created,
                                            timeQuality: t38Quality(v.timeQuality),
                                            messageNonce: v.nonce, bodyUtf8: v.body),
                "unsigned payload assembles")
            XCTAssertEqual(unsigned, v.unsigned, v.name + ": unsigned payload octet-for-octet")
            let mid = SignedSosV1.deriveMessageId(senderNodeId: v.node,
                createdAtEpochSeconds: v.created, messageNonce: v.nonce, unsigned: unsigned)
            XCTAssertEqual(mid, v.msgId, v.name + ": msg_id is the frozen formula over the unsigned span")
            let transcript = SignedSosV1.signatureTranscript(messageId: mid, unsigned: unsigned)
            XCTAssertEqual(transcript.count, mid.count + 4 + unsigned.count,
                v.name + ": transcript is msg_id || SOS1 || unsigned")
            XCTAssertEqual(Array(transcript.prefix(20).suffix(4)),
                [0x53, 0x4F, 0x53, 0x31], v.name + ": the magic rides mid the transcript")
            // the pinned, cross-isle signature must VERIFY under the embedded key
            let pinnedKey = try XCTUnwrap(
                Curve25519.Signing.PublicKey(rawRepresentation: v.signPub),
                v.name + ": pinned signing key parses")
            XCTAssertTrue(pinnedKey.isValidSignature(v.signature, for: transcript),
                v.name + ": the JVM-struck signature verifies on this isle")
            // fresh authorship: structure and acceptance, not byte equality
            let frame = try XCTUnwrap(try? SignedSosV1.author(
                signingSeed: v.seed, staticDhPublicKey: v.dhPub, generation: v.generation,
                createdAtEpochSeconds: v.created, timeQuality: t38Quality(v.timeQuality),
                messageNonce: v.nonce, bodyUtf8: v.body), v.name + ": authoring succeeds")
            let p = t38U(frame.payload)
            XCTAssertEqual(frame.type, .sos, v.name + ": outer type kept")
            XCTAssertEqual(Int(frame.flags), 0x0030, v.name + ": required flags kept")
            XCTAssertEqual(frame.ttl, FrameV2.maxTtl, v.name + ": ttl at the flood ceiling")
            XCTAssertEqual(frame.hopCount, 0, v.name + ": hop born at zero")
            XCTAssertEqual(t38U(frame.routingTag), [UInt8](repeating: 0, count: 4),
                v.name + ": the broadcast tag is not a hint")
            XCTAssertEqual(p.count, 4 + 64 + v.unsigned.count, v.name + ": envelope shape")
            XCTAssertEqual(Array(p[0..<4]), [0x53, 0x4F, 0x53, 0x31], v.name + ": magic leads")
            XCTAssertNotEqual(t38D(Array(p[4..<68])), Data(repeating: 0, count: 64),
                v.name + ": the signature slot is live")
            // the fresh frame's span equals its OWN authored unsigned; it may
            // differ from the pinned one only inside the 64-byte binding seal,
            // which this isle strikes randomized -- everything outside the seal
            // is fixed by the vector and must match byte for byte.
            XCTAssertEqual(t38D(Array(p[68..<69])),
                t38D(Array(unsigned.subdata(in: 0..<1))),
                v.name + ": the version octet is fixed")
            let tailLen = v.unsigned.count - 134
            XCTAssertEqual(t38D(Array(p[(p.count - tailLen) ..< p.count])),
                t38D(Array(unsigned.subdata(in: (unsigned.count - tailLen) ..< unsigned.count))),
                v.name + ": everything after the binding region is fixed")
            XCTAssertNotEqual(t38D(Array(p[4..<68])), v.signature,
                v.name + ": this isle signs randomized -- fresh seal differs from the pinned one")
            XCTAssertEqual(Array(p[4..<68]).count, 64, v.name + ": the seal slot is full-width")
            let verdict = SignedSosV1.verify(frame, expectedNodeId: v.node)
            let seen = try XCTUnwrap(viewOf(verdict), v.name + ": the receiver must accept")
            XCTAssertEqual(seen.senderNodeId, v.node, v.name + ": resolved sender")
            XCTAssertEqual(seen.signingPublicKey, v.signPub, v.name + ": resolved signing key")
            XCTAssertEqual(seen.staticDhPublicKey, v.dhPub, v.name + ": resolved dh key")
            XCTAssertEqual(seen.generation, v.generation, v.name + ": resolved generation")
            XCTAssertEqual(seen.createdAtEpochSeconds, v.created, v.name + ": resolved clock")
            XCTAssertEqual(seen.timeQuality, t38Quality(v.timeQuality), v.name + ": resolved quality")
            XCTAssertEqual(seen.messageNonce, v.nonce, v.name + ": resolved nonce")
            XCTAssertEqual(seen.bodyUtf8, v.body, v.name + ": resolved body")
            XCTAssertEqual(seen.unsignedPayload, t38D(Array(p[68...])),
                v.name + ": verifier and codec see the same span")
            XCTAssertEqual(seen.unsignedPayload.count, v.unsigned.count,
                v.name + ": the span keeps the vector's measure")
            XCTAssertEqual(frame.msgId, SignedSosV1.deriveMessageId(
                senderNodeId: seen.senderNodeId, createdAtEpochSeconds: v.created,
                messageNonce: seen.messageNonce, unsigned: seen.unsignedPayload),
                v.name + ": the header msg_id re-derives over the authenticated span")
            let round = try XCTUnwrap(FrameV2.decode(frame.encode()),
                v.name + ": the codec round-trips the signed envelope")
            XCTAssertEqual(round.payload, frame.payload,
                v.name + ": the codec carries the signature whole")
        }
    }

    // ---------------------------------------------------------- W2 zero signature

    /** W2 -- the structural golden shape with the all-zero signature slot is
     *  a STRUCTURAL fixture (section 15 keeps it): the validator passes it,
     *  runtime authentication refuses it by the named reason. */
    func testRuntimeRejectsZeroSignatureStructuralFixture() throws {
        let v = vec("accept_signed_ok_min")
        var zeroed = t38U(v.payload)
        for k in 4..<68 { zeroed[k] = 0 }
        let frame = t38Frame(.sos, 0x0030, v.msgId, Data(zeroed))
        XCTAssertEqual(SosFrameValidator.validate(frame), .ok,
            "the structural gate must not be the one that speaks")
        expectRefusal(SignedSosV1.verify(frame, expectedNodeId: nil), .signature,
            "the all-zero signature slot authenticates against no key")
        let fromTable = vec("reject_zero_signature_structural_only")
        XCTAssertEqual(fromTable.payload, Data(zeroed),
            "the pinned zero-signature vector matches the spliced shape")
        guard let wantW2 = SosReason(rawValue: fromTable.reason) else {
            XCTFail("no such reason word in the table: " + fromTable.reason); return
        }
        expectRefusal(SignedSosV1.verify(
            t38Frame(.sos, 0x0030, v.msgId, fromTable.payload), expectedNodeId: nil),
            wantW2, "table vector " + fromTable.name)
    }

    // ---------------------------------------------------------- W3 changed key/body/msgID

    /** W3 -- changed key, changed body, changed msgID all break
     *  authentication, with the reason table naming each gate; the same frame
     *  checked against a person it was not bound to is refused apart. */
    func testChangesToKeyBodyOrMsgIdBreakAuthentication() throws {
        for n in ["reject_signature_bit_flip", "reject_body_bit_flip", "reject_msg_id_bit_flip"] {
            let v = vec(n)
            let mid = n == "reject_msg_id_bit_flip" ? t38Flipped(v.msgId, 0) : v.msgId
            guard let wantW3 = SosReason(rawValue: v.reason) else {
                XCTFail("no such reason word in the table: " + v.reason); return
            }
            expectRefusal(SignedSosV1.verify(
                t38Frame(.sos, 0x0030, mid, v.payload), expectedNodeId: nil),
                wantW3, "table vector " + n)
        }
        let base = vec("accept_signed_ok_min")
        let honest = SignedSosV1.verify(
            t38Frame(.sos, 0x0030, base.msgId, base.payload), expectedNodeId: nil)
        XCTAssertNotNil(viewOf(honest), "the untouched frame authenticates")
        // verified person separation: right frame, wrong claimed person
        let wrongPerson = t38Flipped(base.node, 15)
        expectRefusal(SignedSosV1.verify(
            t38Frame(.sos, 0x0030, base.msgId, base.payload), expectedNodeId: wrongPerson),
            .identityBinding, "the frame checked against a person it was not bound to")
    }

    // ---------------------------------------------------------- W4 one bit away

    /** W4 -- a fake SOS by a one-bit type change: the renumbering is such
     *  that no assigned type sits one bit from SOS; the codec fails closed
     *  on the unassigned neighbour; a MESSAGE wearing SOS clothing is
     *  refused by the type gate before any magic or signature is consulted. */
    func testFakeSosByOneBitTypeChangeRefused() throws {
        // audit the frozen table itself: derive the assigned codes from the enum
        var assigned: [UInt8] = []
        for raw in 0...255 {
            if TypeV2(rawValue: UInt8(raw)) != nil { assigned.append(UInt8(raw)) }
        }
        XCTAssertTrue(assigned.contains(0xF0), "SOS is assigned")
        for code in assigned where code != 0xF0 {
            var diff = Int(code ^ 0xF0)
            var bits = 0
            while diff != 0 { bits += diff & 1; diff >>= 1 }
            XCTAssertNotEqual(bits, 1, "no assigned type sits one bit from SOS: 0x" + String(code, radix: 16))
        }
        let v = vec("accept_signed_ok_min")
        var raw = t38U(t38Frame(.sos, 0x0030, v.msgId, v.payload).encode())
        raw[3] ^= 0x10 // 0xF0 -> 0xE0, one bit
        let crc = FrameV2.crc16(raw)
        raw[30] = UInt8((crc >> 8) & 0xFF)
        raw[31] = UInt8(crc & 0xFF)
        XCTAssertNil(FrameV2.decode(Data(raw)),
            "the codec refuses the promoted neighbour outright")
        let promo = vec("reject_one_bit_type_promotion")
        XCTAssertEqual(promo.headerType, 0xE0, "the table keeps the promoted type octet")
        let asMessage = t38Frame(.message, 0x0030, v.msgId, v.payload)
        XCTAssertEqual(SosFrameValidator.validate(asMessage), .wrongType,
            "the type gate precedes the magic gate")
        expectRefusal(SignedSosV1.verify(asMessage, expectedNodeId: nil), .wrongType,
            "a MESSAGE wearing SOS clothing is refused")
    }

    // ---------------------------------------------------------- W5 malformed bindings

    /** W5 -- malformed bindings: truncated shapes, a lying version byte, a
     *  stranger's seal upon the victim's declaration, and a key that does
     *  not hash to the claimed node all refuse by name; the same
     *  self-consistent stranger frame authenticates as the stranger's own
     *  distress when no person is claimed. */
    func testMalformedIdentityBindingRefused() throws {
        for n in ["reject_truncated_binding", "reject_bad_payload_version"] {
            let v = vec(n)
            guard let wantW5 = SosReason(rawValue: v.reason) else {
                XCTFail("no such reason word in the table: " + v.reason); return
            }
            expectRefusal(SignedSosV1.verify(
                t38Frame(.sos, 0x0030, v.msgId, v.payload), expectedNodeId: nil),
                wantW5, "table vector " + n + " (shape gates speak in order)")
        }
        let strangerSealed = vec("reject_stranger_key_in_binding")
        expectRefusal(SignedSosV1.verify(
            t38Frame(.sos, 0x0030, strangerSealed.msgId, strangerSealed.payload),
            expectedNodeId: nil), .identityBinding,
            "a stranger's seal cannot certify the victim")
        let underived = vec("reject_underived_node_claim")
        expectRefusal(SignedSosV1.verify(
            t38Frame(.sos, 0x0030, underived.msgId, underived.payload),
            expectedNodeId: underived.node), .identityBinding,
            "the claim must be derived, never trusted")
        let own = SignedSosV1.verify(
            t38Frame(.sos, 0x0030, underived.msgId, underived.payload), expectedNodeId: nil)
        let ownView = try XCTUnwrap(viewOf(own),
            "the same frame is the stranger's own honest distress")
        XCTAssertEqual(ownView.senderNodeId,
            SignedSosV1.nodeIdOfSigningKey(ownView.signingPublicKey),
            "its key hashes to the node it names")
        // the binding parser itself is fail-closed: the court slices the
        // 133-byte binding field out of the frame's own unsigned span and
        // hands the parser one byte short -- the parse must be refused.
        // IdentityBindingV1.parse refuses a truncated serialization
        XCTAssertThrowsError(try IdentityBindingV1.parse(
            underived.payload.subdata(in: 69..<201)))
        XCTAssertEqual(underived.payload.subdata(in: 69..<202).count, 133,
            "the field the court sliced is the pinned binding")
    }

    // ---------------------------------------------------------- W6 the binding equation

    /** W6 -- the local public key is bound to the identity binding: every
     *  octet of the 133-byte serialization sits where the table says, the
     *  node id IS the hash of the embedded key, and the authenticated key
     *  is distinguished from the verified person -- the printed form keeps
     *  key material redacted. */
    func testBindsLocalPublicKeyToIdentityBinding() throws {
        let v = vec("accept_signed_ok_min")
        let b = t38U(v.binding)
        XCTAssertEqual(b.count, 133, "binding length")
        XCTAssertEqual(b[0], 0x01, "binding version")
        for k in 0..<4 {
            XCTAssertEqual(b[1 + k], UInt8((v.generation >> UInt32(24 - 8 * k)) & 0xFF),
                "generation octet " + String(k) + " rides big-endian")
        }
        XCTAssertEqual(t38D(Array(b[5..<37])), v.signPub, "embedded signing key")
        XCTAssertEqual(t38D(Array(b[37..<69])), v.dhPub, "embedded dh key")
        XCTAssertEqual(Array(b[69..<133]).count, 64, "binding seal length")
        XCTAssertEqual(SignedSosV1.nodeIdOfSigningKey(v.signPub), v.node,
            "the node id IS the hash of the embedded key")
        let verdict = SignedSosV1.verify(
            t38Frame(.sos, 0x0030, v.msgId, v.payload), expectedNodeId: v.node)
        let seen = try XCTUnwrap(viewOf(verdict), "the bound key authenticates against the claim")
        XCTAssertEqual(seen.signingPublicKey, v.signPub, "the resolved key is the local key")
        XCTAssertEqual(seen.senderNodeId, v.node, "the resolved node is the derivation")
        let printed = String(describing: seen)
        var longestRun = 0
        var run = 0
        for u in Array(printed.utf8) {
            let isHexDigit = (0x30...0x39).contains(u) || (0x61...0x66).contains(u)
                || (0x41...0x46).contains(u)
            if isHexDigit { run += 1; if run > longestRun { longestRun = run } } else { run = 0 }
        }
        XCTAssertLessThan(longestRun, 32,
            "the printed form never bleeds whole key material into prose")
    }

    // ---------------------------------------------------------- W7 body bounds

    /** W7 -- the UTF-8 body is bound: it is carried whole into the hash,
     *  the budget is 400, malformed sequences are refused by the author
     *  before any signature is struck, and a lying length field is caught
     *  by the length gate BEFORE the signature gate may speak. */
    func testUtf8BodyIsBoundAndBudgeted() throws {
        let v = vec("accept_signed_ok_max_body")
        XCTAssertEqual(v.body.count, 398, "the pinned body is 398 bytes of multibyte text")
        let frame = try XCTUnwrap(try? SignedSosV1.author(
            signingSeed: v.seed, staticDhPublicKey: v.dhPub, generation: v.generation,
            createdAtEpochSeconds: v.created, timeQuality: t38Quality(v.timeQuality),
            messageNonce: v.nonce, bodyUtf8: v.body), "max-body authoring succeeds")
        XCTAssertEqual(frame.payload.count, 4 + 64 + 157 + 398,
            "the envelope carries magic, seal and the whole body")
        let verdict = SignedSosV1.verify(frame, expectedNodeId: v.node)
        XCTAssertEqual(viewOf(verdict)?.bodyUtf8, v.body,
            "the body survives the round trip whole")
        let badBodies: [Data] = [
            Data([0x80]), Data([0xC0, 0x80]), Data([0xE0, 0x80, 0x80]),
            Data([0xED, 0xA0, 0x80]), Data([0xF0, 0x80, 0x80, 0x80]),
            Data([0xF5, 0x80, 0x80, 0x80]),
            Data(repeating: 0x61, count: 401),
        ]
        for bad in badBodies {
            // the author refuses to strike a non-canonical body
            XCTAssertThrowsError(try SignedSosV1.author(
                signingSeed: v.seed, staticDhPublicKey: v.dhPub, generation: v.generation,
                createdAtEpochSeconds: 1700000201, timeQuality: .userConfirmed,
                messageNonce: v.nonce, bodyUtf8: bad))
        }
        let liar = vec("reject_body_length_liar")
        expectRefusal(SignedSosV1.verify(
            t38Frame(.sos, 0x0030, liar.msgId, liar.payload), expectedNodeId: nil),
            .bodyLength, "the length gate speaks before the signature")
    }

    // ---------------------------------------------------------- W8 duplicate resend

    /** W8 -- a duplicate logical SOS: the same immutable identity re-sent
     *  yields the same msg_id (the signature itself is randomized on this
     *  isle and must differ -- that is the oracle of liveness, not drift);
     *  the composing node's seen cache governs repetition: the store holds
     *  the message once while the observer hook reports each observation,
     *  authentication idempotent per view. */
    func testDuplicateLogicalSosResentIdempotent() throws {
        let v = vec("accept_signed_ok_min")
        let first = try XCTUnwrap(try? SignedSosV1.author(
            signingSeed: v.seed, staticDhPublicKey: v.dhPub, generation: v.generation,
            createdAtEpochSeconds: v.created, timeQuality: t38Quality(v.timeQuality),
            messageNonce: v.nonce, bodyUtf8: v.body), "first authoring")
        let second = try XCTUnwrap(try? SignedSosV1.author(
            signingSeed: v.seed, staticDhPublicKey: v.dhPub, generation: v.generation,
            createdAtEpochSeconds: v.created, timeQuality: t38Quality(v.timeQuality),
            messageNonce: v.nonce, bodyUtf8: v.body), "second authoring")
        // Two hand-offs of one logical distress under this isle's randomized
        // signer carry distinct seals -- and, since the msg_id hashes the
        // binding which bears the seal, distinct msg_ids too. That is the
        // oracle of liveness, not drift: the DUPLICATE the seen cache speaks
        // of is the retransmission of the SAME envelope (identical octets),
        // which is what the ingest leg below re-feeds.
        XCTAssertNotEqual(Array(t38U(first.payload)[4..<68]),
            Array(t38U(second.payload)[4..<68]),
            "two out of one key are distinct seals: randomized signing proven")
        XCTAssertNotEqual(first.msgId, second.msgId,
            "the seal rides inside the msg_id: distinct seals, distinct ids")
        let store = InMemoryMessageStore()
        let observer = Watcher()
        let node = try composingNode(store, observer, repo: DeadDeliveryRepository())
        let hop = Data(repeating: 0x5A, count: 16)
        XCTAssertTrue(node.handleInboundFrame(first, receivedFrom: hop),
            "the novel frame is relayed")
        XCTAssertTrue(node.handleInboundFrame(second, receivedFrom: hop),
            "a distinct msg_id is no duplicate: the cache judges by identity")
        XCTAssertFalse(node.handleInboundFrame(first, receivedFrom: hop),
            "the retransmitted envelope is deduped by the seen cache")
        XCTAssertEqual(observer.authenticated, 3,
            "the honest bytes authenticate again, idempotently")
        XCTAssertEqual(observer.unauthenticated, 0, "no refusal was recorded")
        XCTAssertEqual(store.allHeldMsgIds().count, 2,
            "the cache governs repetition: two distinct ids held, the retransmission not thrice")
    }

    // ---------------------------------------------------------- W9 unknown-time pairing

    /** W9 -- the unknown-time rule binds the clock and the quality together:
     *  zero with a claimed quality, or a running clock with UNKNOWN, are
     *  authoring errors and reception refusals alike; the honest pairing
     *  verifies. */
    func testUnknownTimeQualityPairingEnforced() throws {
        let v = vec("accept_signed_ok_min")
        // zero clock with a claimed quality is not stricken
        XCTAssertThrowsError(try SignedSosV1.author(
            signingSeed: v.seed, staticDhPublicKey: v.dhPub, generation: v.generation,
            createdAtEpochSeconds: 0, timeQuality: .userConfirmed,
            messageNonce: v.nonce, bodyUtf8: v.body))
        // a running clock with UNKNOWN is not stricken
        XCTAssertThrowsError(try SignedSosV1.author(
            signingSeed: v.seed, staticDhPublicKey: v.dhPub, generation: v.generation,
            createdAtEpochSeconds: 1700000201, timeQuality: .unknown,
            messageNonce: v.nonce, bodyUtf8: v.body))
        let unpaired = vec("reject_unknown_time_pairing")
        expectRefusal(SignedSosV1.verify(
            t38Frame(.sos, 0x0030, unpaired.msgId, unpaired.payload), expectedNodeId: nil),
            .unknownTimePairing, "broken pairing is refused at reception too")
        let rogue = vec("reject_unknown_time_quality")
        expectRefusal(SignedSosV1.verify(
            t38Frame(.sos, 0x0030, rogue.msgId, rogue.payload), expectedNodeId: nil),
            .timeQuality, "no quality beyond the closed table")
        let honest = vec("accept_unknown_time_zero_clock")
        let verdict = SignedSosV1.verify(
            t38Frame(.sos, 0x0030, honest.msgId, honest.payload), expectedNodeId: nil)
        XCTAssertEqual(viewOf(verdict)?.timeQuality, .unknown,
            "the honest pairing of zero clock with UNKNOWN verifies")
    }

    // ---------------------------------------------------------- W10 composed authorship

    /** W10 -- composed authorship: with the authority wired, MeshNode's SOS
     *  dispatch persists a frame that authenticates under the node's own
     *  bound key and carries the user's body whole; the C6 ledger records
     *  one mode-none obligation with no recipient bound -- a none-mode
     *  message can never be acknowledged; without the authority the node
     *  still emits the legacy structural shape, which the receiving runtime
     *  refuses. */
    func testComposedNodeAuthorsSignedDistress() throws {
        let v = vec("accept_signed_ok_min")
        let store = InMemoryMessageStore()
        let journal = T38Journal()
        let node = try composingNode(store, nil, repo: journal)
        let authority = FakeAuthority(seed: v.seed, dhPub: v.dhPub, generation: v.generation,
                                     clock: v.created, nonce: v.nonce)
        node.sosAuthority = authority
        let result = node.dispatchSos(payload: t38Ascii("mayday-mayday")) { _, _ in true }
        switch result {
        case .queuedDurably: break // zero connected peers: durably held, reaches on encounter
        default: XCTFail("the distress was queued")
        }
        let held = store.allHeldOrderedByPriority()
        XCTAssertEqual(held.count, 1, "the node holds what it sent")
        let frame = try XCTUnwrap(held.first, "the held frame")
        let verdict = SignedSosV1.verify(frame, expectedNodeId: v.node)
        let seen = try XCTUnwrap(viewOf(verdict),
            "the composed node's frame authenticates under the bound key")
        XCTAssertEqual(seen.bodyUtf8, t38Ascii("mayday-mayday"), "the body was carried whole")
        XCTAssertEqual(seen.senderNodeId, v.node, "the sender is the node that holds the key")
        XCTAssertEqual(seen.generation, v.generation, "the generation is the authority's")
        XCTAssertEqual(authority.calls, 1, "the authority was consulted once")
        XCTAssertEqual(journal.records.count, 1, "one delivery record")
        let rec = try XCTUnwrap(journal.records[frame.msgId],
            "the record is keyed by the authored msg_id")
        XCTAssertEqual(rec.ackMode, AckMode.none, "the distress is broadcast: mode none")
        XCTAssertNil(rec.expectedRecipientNodeId, "none-mode binds no recipient")
        XCTAssertEqual(rec.state, DeliveryState.queuedDurably,
            "zero peers: the leg stays queued until an encounter (the mirror of the android handedToRelay arm, which had a peer)")
        // the legacy arm: unwired authority, the structural shape still goes
        // out (documented) and the receiver refuses it by name.
        let bareJournal = T38Journal()
        let bare = try composingNode(InMemoryMessageStore(), nil, repo: bareJournal)
        let legacyResult = bare.dispatchSos(payload: t38Ascii("old-style")) { _, _ in true }
        switch legacyResult {
        case .queuedDurably: break
        default: XCTFail("the legacy arm still queues")
        }
        let legacyFrame = try XCTUnwrap(
            bare.store.allHeldOrderedByPriority().first, "the legacy frame is held")
        XCTAssertEqual(SosFrameValidator.validate(legacyFrame), .ok,
            "the structural gate passes it")
        expectRefusal(SignedSosV1.verify(legacyFrame, expectedNodeId: nil), .malformed,
            "the legacy structural shape is refused before the seal is weighed")
        XCTAssertEqual(bareJournal.records.count, 1,
            "the legacy arm also keeps the C6 ledger")
        XCTAssertEqual(bareJournal.records.values.first?.ackMode, AckMode.none,
            "broadcast remains mode none on every arm")
    }

    // ---------------------------------------------------------- W11 inbound relay truth

    /** W11 -- the relay decides first and on its own; authentication rides
     *  beside it. An unauthenticated frame is never promoted to the
     *  observer, a forgery is refused by the named gate, the delivery
     *  tracker is never reached by an inbound SOS, and no ACK is ever
     *  issued for a mode-none distress. */
    func testInboundRelayTruthUntouchedAndUnauthenticatedNeverPromoted() throws {
        let store = InMemoryMessageStore()
        let observer = Watcher()
        let node = try composingNode(store, observer, repo: DeadDeliveryRepository())
        let hop = Data(repeating: 0x67, count: 16)
        let honest = vec("accept_signed_ok_min")
        let honestFrame = t38Frame(.sos, 0x0030, honest.msgId, honest.payload)
        XCTAssertTrue(node.handleInboundFrame(honestFrame, receivedFrom: hop),
            "the honest frame is relayed on its own merits")
        XCTAssertEqual(observer.authenticated, 1,
            "the observer saw the authenticated indication")
        XCTAssertEqual(observer.unauthenticated, 0, "no refusal for the honest one")
        // a forgery on the honest identity: same msg_id, one bit flipped in
        // the signature region. The seen cache guards repetition (the relay
        // returns false and nothing persists twice), yet the observer hook
        // still runs and the signature gate names the refusal.
        let forgedPayload = t38Flipped(honest.payload, 9)
        XCTAssertFalse(node.handleInboundFrame(
            t38Frame(.sos, 0x0030, honest.msgId, forgedPayload), receivedFrom: hop),
            "the forgery shares the held msg_id: deduped at the cache")
        XCTAssertEqual(observer.authenticated, 1,
            "the forgery was never announced as authenticated")
        XCTAssertEqual(observer.unauthenticated, 1, "the refusal was recorded once")
        XCTAssertEqual(observer.lastReason, .signature, "by the named gate")
        // no ACK was ever issued for a mode-none distress: the outbox stays
        // empty and the tracker's dead methods would have crashed loudly.
        XCTAssertTrue(node.drainAckOutboxForLink(4).isEmpty,
            "no ack rows for a broadcast")
        XCTAssertEqual(store.allHeldMsgIds().count, 1,
            "the held set is exactly the one honest frame")
        // the resend of the honest frame: deduped at the cache, yet the hook
        // re-authenticates the same honest bytes -- authentication is
        // idempotent per observation.
        XCTAssertFalse(node.handleInboundFrame(honestFrame, receivedFrom: hop),
            "the resend is deduped")
        XCTAssertEqual(observer.authenticated, 2,
            "the honest bytes authenticate again, idempotently")
        XCTAssertEqual(observer.unauthenticated, 1, "and the refusal count stays at one")
    }
}
