import XCTest
@testable import GodstoneMesh

/// Golden wire-vector conformance for the generated GMP/2.1 `FrameV2` codec.
///
/// These vectors are pinned from `wire/golden_vectors.json`, which is GENERATED by
/// `wire/codegen.py` from `wire/wire_v2.yaml` using the independent Python
/// reference codec (`wire/gen/wire_v2_codec.py`). The expected `encoded` bytes
/// and the negative `frame` bytes below are NOT self-generated from the Swift
/// codec under test — they are the Python-reference output, transcribed as hex
/// literals (mirroring the inline-literal style of `PortVectorTests`). A
/// byte-identical Swift `encode()` (positive) and a fail-closed `decode()` /
/// `SosFrameValidator` refusal (negative) prove the two codecs agree with the
/// spec, not just with themselves.
///
/// This is ADR-008 patch 15 (frame-validation-and-vectors) and satisfies ADR-001
/// acceptance criterion 3 (cross-platform golden vectors) on iOS. The Android
/// mirror is `android/mesh/src/test/java/io/godstone/mesh/wire/v2/WireV2VectorTest.kt`.
///
/// NOTE: execution verification of this iOS target is deferred to patch 21
/// (cross-platform-conformance), which runs `xcodebuild test` as a gate. The
/// Android mirror is execution-verified by `scripts/verify_android_phase0.sh`
/// (`:mesh:testDebugUnitTest`) in this patch. The literals are identical across
/// both mirrors and pinned from the same `wire/golden_vectors.json`.
final class WireV2VectorTests: XCTestCase {

    private func data(fromHex hex: String) -> Data {
        var d = Data()
        var i = hex.startIndex
        while i < hex.endIndex {
            let j = hex.index(i, offsetBy: 2)
            d.append(UInt8(hex[i..<j], radix: 16)!)
            i = j
        }
        return d
    }

    private func hex(_ d: Data) -> String {
        d.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - positive: encode() reproduces the pinned Python-reference bytes

    func testEncodeHelloReproducesGoldenVector() {
        let f = FrameV2(type: .hello,
                         msgId: data(fromHex: "000102030405060708090a0b0c0d0e0f"),
                         routingTag: data(fromHex: "deadbeef"),
                         ttl: 12, hopCount: 0, flags: FrameV2.Flags.sealed,
                         payload: data(fromHex: "7061796c6f61642d48454c4c4f"))
        XCTAssertEqual(
            "47530211000102030405060708090a0b0c0d0e0fdeadbeef0c000001000d5cbf7061796c6f61642d48454c4c4f",
            hex(f.encode()))
    }

    func testEncodeMessageReproducesGoldenVector() {
        let f = FrameV2(type: .message,
                         msgId: data(fromHex: "000102030405060708090a0b0c0d0e0f"),
                         routingTag: data(fromHex: "deadbeef"),
                         ttl: 12, hopCount: 0, flags: FrameV2.Flags.sealed,
                         payload: data(fromHex: "7061796c6f61642d4d455353414745"))
        XCTAssertEqual(
            "47530218000102030405060708090a0b0c0d0e0fdeadbeef0c000001000fc2ab7061796c6f61642d4d455353414745",
            hex(f.encode()))
    }

    func testEncodeDigestReproducesGoldenVector() {
        let f = FrameV2(type: .digest,
                         msgId: data(fromHex: "000102030405060708090a0b0c0d0e0f"),
                         routingTag: data(fromHex: "deadbeef"),
                         ttl: 12, hopCount: 0, flags: FrameV2.Flags.sealed,
                         payload: data(fromHex: "7061796c6f61642d444947455354"))
        XCTAssertEqual(
            "47530212000102030405060708090a0b0c0d0e0fdeadbeef0c000001000e53767061796c6f61642d444947455354",
            hex(f.encode()))
    }

    func testEncodeSosReproducesGoldenVector() {
        // SOS payload shape: "SOS1" + 64-byte signature slot (zero placeholder) + "help".
        let f = FrameV2(type: .sos,
                         msgId: data(fromHex: "000102030405060708090a0b0c0d0e0f"),
                         routingTag: data(fromHex: "deadbeef"),
                         ttl: 12, hopCount: 0,
                         flags: FrameV2.Flags.ack_req | FrameV2.Flags.relay_ok,
                         payload: data(fromHex: "534f5331" + String(repeating: "00", count: 64) + "68656c70"))
        XCTAssertEqual(
            "475302f0000102030405060708090a0b0c0d0e0fdeadbeef0c000030004834c0534f5331"
                + String(repeating: "00", count: 64) + "68656c70",
            hex(f.encode()))
    }

    // MARK: - round-trip: decode() inverts encode() for each positive case

    func testDecodeRoundTripsEveryPositiveGoldenVector() {
        let vectors: [(TypeV2, UInt16, String)] = [
            (.hello, 1, "47530211000102030405060708090a0b0c0d0e0fdeadbeef0c000001000d5cbf7061796c6f61642d48454c4c4f"),
            (.message, 1, "47530218000102030405060708090a0b0c0d0e0fdeadbeef0c000001000fc2ab7061796c6f61642d4d455353414745"),
            (.digest, 1, "47530212000102030405060708090a0b0c0d0e0fdeadbeef0c000001000e53767061796c6f61642d444947455354"),
            (.sos, 0x30, "475302f0000102030405060708090a0b0c0d0e0fdeadbeef0c000030004834c0"
                + "534f5331" + String(repeating: "00", count: 64) + "68656c70"),
        ]
        for (type, flags, hexStr) in vectors {
            guard let f = FrameV2.decode(data(fromHex: hexStr)) else {
                XCTFail("decode returned nil for \(type) golden vector"); continue
            }
            XCTAssertEqual(type, f.type, "type mismatch for \(type)")
            XCTAssertEqual(flags, f.flags, "flags mismatch for \(type)")
            XCTAssertEqual(hexStr, hex(f.encode()), "round-trip not byte-identical for \(type)")
        }
    }

    // MARK: - negative: wire-level decode rejects malformed headers (decode==nil)

    func testRejectLegacyType0x02IsRejectedAtWireLayer() {
        XCTAssertNil(FrameV2.decode(data(fromHex:
            "47530202000102030405060708090a0b0c0d0e0fdeadbeef0c000001000d25547061796c6f61642d48454c4c4f")))
    }

    func testRejectV1FrameIsRejectedAtWireLayer() {
        XCTAssertNil(FrameV2.decode(data(fromHex:
            "47530111000102030405060708090a0b0c0d0e0fdeadbeef0c000001000d31037061796c6f61642d48454c4c4f")))
    }

    func testRejectBadCrcIsRejectedAtWireLayer() {
        XCTAssertNil(FrameV2.decode(data(fromHex:
            "47530211000102030405f90708090a0b0c0d0e0fdeadbeef0c000001000d5cbf7061796c6f61642d48454c4c4f")))
    }

    func testRejectHopCountOverMaxIsRejectedAtWireLayer() {
        XCTAssertNil(FrameV2.decode(data(fromHex:
            "47530211000102030405060708090a0b0c0d0e0fdeadbeef0c110001000df2b47061796c6f61642d48454c4c4f")))
    }

    // MARK: - negative: SOS structural rejection (decode!=nil, validator refuses)

    func testRejectSosMissingPayloadMagicParsesButIsRefusedByValidator() {
        let f = FrameV2.decode(data(fromHex:
            "475302f0000102030405060708090a0b0c0d0e0fdeadbeef0c0000300004bd8868656c70"))
        XCTAssertNotNil(f, "well-formed frame must parse at the wire layer; the SOS gate is structural, not parse-level")
        XCTAssertEqual(SosFrameValidator.Verdict.payloadTooShort, SosFrameValidator.validate(f!))
    }

    func testRejectSosMissingFlagsParsesButIsRefusedByValidator() {
        let f = FrameV2.decode(data(fromHex:
            "475302f0000102030405060708090a0b0c0d0e0fdeadbeef0c0000000048f165"
            + "534f5331" + String(repeating: "00", count: 64) + "68656c70"))
        XCTAssertNotNil(f, "well-formed frame must parse at the wire layer")
        XCTAssertEqual(SosFrameValidator.Verdict.missingRequiredFlags, SosFrameValidator.validate(f!))
    }

    // MARK: - positive SOS validator

    func testSosValidatorAcceptsGoldenSosVector() {
        let f = FrameV2(type: .sos,
                         msgId: data(fromHex: "000102030405060708090a0b0c0d0e0f"),
                         routingTag: data(fromHex: "deadbeef"),
                         ttl: 12, hopCount: 0,
                         flags: FrameV2.Flags.ack_req | FrameV2.Flags.relay_ok,
                         payload: data(fromHex: "534f5331" + String(repeating: "00", count: 64) + "68656c70"))
        XCTAssertEqual(SosFrameValidator.Verdict.ok, SosFrameValidator.validate(f))
    }

    func testSosValidatorRejectsNonSosType() {
        let f = FrameV2(type: .hello,
                         msgId: data(fromHex: "000102030405060708090a0b0c0d0e0f"),
                         routingTag: data(fromHex: "deadbeef"),
                         ttl: 12, hopCount: 0,
                         flags: FrameV2.Flags.ack_req | FrameV2.Flags.relay_ok,
                         payload: data(fromHex: "534f5331" + String(repeating: "00", count: 64) + "68656c70"))
        XCTAssertEqual(SosFrameValidator.Verdict.wrongType, SosFrameValidator.validate(f))
    }
}