import Foundation
import CryptoKit
import GodstoneCore

/// Noise_XX_25519_ChaChaPoly_BLAKE2s.
///
/// V4 REWRITE. The V3 implementation was not merely unreachable -- it was
/// wire-non-conformant and could not have completed a handshake against
/// noise-java even with every call site wired. Measured against the repository's
/// own pinned vectors:
///
///     pinned spec message sizes : [32, 96, 64]
///     V3 NoiseSession.swift     : [32, 80, 48]
///
/// Three defects, all fixed here:
///
///  (a) MESSAGES 2 AND 3 OMITTED THEIR PAYLOAD. XX message 2 is `e, ee, s, es`
///      followed by an encrypted payload; V3 returned `e + encryptedStatic` and
///      stopped. Message 3 is `s, se` plus a payload; V3 returned the static
///      only. Hence 80 and 48 instead of 96 and 64.
///
///  (b) MESSAGE 2 WAS PARSED AS ONE CIPHERTEXT. `decryptAndHash(msg2.suffix(from: 32))`
///      handed 64 bytes to a single AEAD open, yielding a 48-byte "static key".
///      X25519 requires 32, so the parse threw before any DH occurred.
///
///  (c) THE HANDSHAKE NONCE WAS PINNED TO ZERO. Both encryptAndHash and
///      decryptAndHash built `ChaChaPoly.Nonce(data: Data(count: 12))`. In Noise
///      the handshake nonce resets to 0 on MixKey and otherwise INCREMENTS. In
///      message 3 the initiator encrypts `s` under the `es` key at n = 1,
///      because message 2's payload decrypt already consumed n = 0.
///
/// None of this was visible to Invariant D, which validates the PYTHON
/// reference against a fixture generated by that same reference and never
/// executes Swift. See docs/adr/ADR-002 and ci/mutations.py.
///
/// The prologue binds the handshake to the protocol name and both node hints,
/// which kills downgrade and cross-protocol attacks before they start.
public final class NoiseSession {

    public enum Role { case initiator, responder }

    /// Handshake cipher. `n` resets to zero on every MixKey and increments on
    /// every use -- that increment is defect (c) above.
    private struct CipherState {
        var k: SymmetricKey?
        var n: UInt64 = 0

        /// Noise s.12.3: 32 bits of zeros then LITTLE-endian n.
        func nonce() throws -> ChaChaPoly.Nonce {
            var v = n.littleEndian
            return try ChaChaPoly.Nonce(data: Data(count: 4) + Data(bytes: &v, count: 8))
        }
    }

    private let role: Role
    private let staticKey: Curve25519.KeyAgreement.PrivateKey
    private var ephemeral: Curve25519.KeyAgreement.PrivateKey

    private var chainingKey: Data
    private var handshakeHash: Data
    private var cipher = CipherState()

    private var sendKey: SymmetricKey?
    private var receiveKey: SymmetricKey?
    private var sendNonce: UInt64 = 0
    private var receiveNonce: UInt64 = 0

    private var messagesSinceRekey: UInt64 = 0
    private var sessionStart = Date()

    private var remoteEphemeral: Data?
    public private(set) var remoteStaticKey: Data?
    public private(set) var isEstablished = false

    private static let protocolName = "Noise_XX_25519_ChaChaPoly_BLAKE2s"
    private static let tagLen = 16
    private static let dhLen = 32
    private static let rekeyMessageLimit: UInt64 = 1 << 20
    private static let rekeyTimeLimit: TimeInterval = 30 * 60

    public init(role: Role,
                staticKey: Curve25519.KeyAgreement.PrivateKey,
                localHint: Data,
                remoteHint: Data) {
        self.role = role
        self.staticKey = staticKey
        self.ephemeral = Curve25519.KeyAgreement.PrivateKey()

        var prologue = Data("GMP2".utf8)
        // Canonical ordering: initiator hint first, both sides agree.
        if role == .initiator {
            prologue.append(localHint); prologue.append(remoteHint)
        } else {
            prologue.append(remoteHint); prologue.append(localHint)
        }

        // InitializeSymmetric(protocol_name): pad to HASHLEN, else hash.
        let name = Data(NoiseSession.protocolName.utf8)
        let h0: Data = name.count <= 32
            ? name + Data(count: 32 - name.count)
            : Blake2s.hash(name, digestLength: 32)
        self.chainingKey = h0
        self.handshakeHash = Blake2s.hash(h0 + prologue, digestLength: 32)
    }

    // MARK: - Symmetric state

    private func mixHash(_ data: Data) {
        handshakeHash = Blake2s.hash(handshakeHash + data, digestLength: 32)
    }

    private func mixKey(_ secret: SharedSecret) {
        let material = secret.withUnsafeBytes { Data($0) }
        let (ck, k) = Hkdf.split(chainingKey: chainingKey, material: material)
        chainingKey = ck
        // n RESETS here. This is the whole of defect (c).
        cipher = CipherState(k: SymmetricKey(data: k), n: 0)
    }

    private func encryptAndHash(_ plaintext: Data) throws -> Data {
        guard let k = cipher.k else {
            mixHash(plaintext)
            return plaintext
        }
        let box = try ChaChaPoly.seal(plaintext, using: k,
                                      nonce: cipher.nonce(),
                                      authenticating: handshakeHash)
        cipher.n += 1
        let out = box.ciphertext + box.tag
        mixHash(out)
        return out
    }

    private func decryptAndHash(_ ciphertext: Data) throws -> Data {
        guard let k = cipher.k else {
            mixHash(ciphertext)
            return ciphertext
        }
        guard ciphertext.count >= NoiseSession.tagLen else {
            throw MeshError.handshakeFailed
        }
        // AAD is h BEFORE this ciphertext is mixed in.
        let aad = handshakeHash
        let box = try ChaChaPoly.SealedBox(
            nonce: cipher.nonce(),
            ciphertext: ciphertext.dropLast(NoiseSession.tagLen),
            tag: ciphertext.suffix(NoiseSession.tagLen))
        let plain = try ChaChaPoly.open(box, using: k, authenticating: aad)
        cipher.n += 1
        mixHash(ciphertext)
        return plain
    }

    /// Writer-relative DH resolution. Getting es/se backwards is silent: both
    /// sides still produce 32 bytes, they just disagree, and the failure only
    /// surfaces as a tag mismatch one message later.
    private func dhEE() throws -> SharedSecret {
        try ephemeral.sharedSecretFromKeyAgreement(
            with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteEphemeral!))
    }
    private func dhES() throws -> SharedSecret {
        role == .initiator
            ? try ephemeral.sharedSecretFromKeyAgreement(
                with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteStaticKey!))
            : try staticKey.sharedSecretFromKeyAgreement(
                with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteEphemeral!))
    }
    private func dhSE() throws -> SharedSecret {
        role == .initiator
            ? try staticKey.sharedSecretFromKeyAgreement(
                with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteEphemeral!))
            : try ephemeral.sharedSecretFromKeyAgreement(
                with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteStaticKey!))
    }

    // MARK: - Handshake  (XX:  -> e   <- e, ee, s, es   -> s, se)

    /// Message 1, initiator: `-> e`  (32 bytes with an empty payload)
    public func writeMessage1(payload: Data = Data()) throws -> Data {
        var out = ephemeral.publicKey.rawRepresentation
        mixHash(out)
        out += try encryptAndHash(payload)
        return out
    }

    /// Message 2, responder: reads `e`, writes `e, ee, s, es` + payload.
    /// 96 bytes with empty payloads. V3 produced 80.
    public func readMessage1AndWrite2(_ msg1: Data,
                                      payload: Data = Data()) throws -> Data {
        // Normalise: a sliced Data carries a non-zero startIndex, and
        // subdata(in:) uses ABSOLUTE indices. Copying makes every offset below
        // zero-based regardless of what the transport handed us.
        let m = Data(msg1)
        guard m.count >= NoiseSession.dhLen else { throw MeshError.handshakeFailed }

        remoteEphemeral = m.prefix(NoiseSession.dhLen)
        mixHash(remoteEphemeral!)
        _ = try decryptAndHash(m.suffix(from: NoiseSession.dhLen))

        var out = ephemeral.publicKey.rawRepresentation
        mixHash(out)
        mixKey(try dhEE())                                             // ee
        out += try encryptAndHash(staticKey.publicKey.rawRepresentation) // s
        mixKey(try dhES())                                             // es
        out += try encryptAndHash(payload)                             // payload
        return out
    }

    /// Message 3, initiator: reads message 2, writes `s, se` + payload.
    /// 64 bytes with an empty payload. V3 produced 48.
    public func readMessage2AndWrite3(_ msg2: Data,
                                      payload: Data = Data()) throws -> Data {
        let m = Data(msg2)
        let encStaticLen = NoiseSession.dhLen + NoiseSession.tagLen   // 48
        guard m.count >= NoiseSession.dhLen + encStaticLen else {
            throw MeshError.handshakeFailed
        }

        remoteEphemeral = m.prefix(NoiseSession.dhLen)
        mixHash(remoteEphemeral!)
        mixKey(try dhEE())                                             // ee

        // Split the encrypted static from the encrypted payload. V3 fed BOTH
        // to one AEAD open and derived a 48-byte "X25519 key".
        let encStatic = m.subdata(in: NoiseSession.dhLen ..< (NoiseSession.dhLen + encStaticLen))
        remoteStaticKey = try decryptAndHash(encStatic)                // s
        guard remoteStaticKey?.count == NoiseSession.dhLen else {
            throw MeshError.handshakeFailed
        }
        mixKey(try dhES())                                             // es
        _ = try decryptAndHash(m.suffix(from: NoiseSession.dhLen + encStaticLen))

        // n is now 1 under the es key. encryptAndHash carries that forward.
        var out = try encryptAndHash(staticKey.publicKey.rawRepresentation)  // s
        mixKey(try dhSE())                                             // se
        out += try encryptAndHash(payload)                             // payload
        split()
        return out
    }

    /// Message 3, responder side.
    public func readMessage3(_ msg3: Data) throws {
        let m = Data(msg3)
        let encStaticLen = NoiseSession.dhLen + NoiseSession.tagLen
        guard m.count >= encStaticLen else { throw MeshError.handshakeFailed }

        remoteStaticKey = try decryptAndHash(m.prefix(encStaticLen))   // s
        guard remoteStaticKey?.count == NoiseSession.dhLen else {
            throw MeshError.handshakeFailed
        }
        mixKey(try dhSE())                                             // se
        _ = try decryptAndHash(m.suffix(from: encStaticLen))
        split()
    }

    private func split() {
        let (k1, k2) = Hkdf.split(chainingKey: chainingKey, material: Data())
        // Never the same key in both directions: that makes nonce reuse fatal.
        sendKey    = SymmetricKey(data: role == .initiator ? k1 : k2)
        receiveKey = SymmetricKey(data: role == .initiator ? k2 : k1)
        sendNonce = 0
        receiveNonce = 0
        messagesSinceRekey = 0
        sessionStart = Date()
        isEstablished = true
    }

    /// Handshake hash, equal on both sides once the handshake completes.
    /// Exposed so the port-vector test can assert it.
    public var transcriptHash: Data { handshakeHash }

    // MARK: - Transport

    private static func transportNonce(_ n: UInt64) throws -> ChaChaPoly.Nonce {
        var v = n.littleEndian
        return try ChaChaPoly.Nonce(data: Data(count: 4) + Data(bytes: &v, count: 8))
    }

    public func encrypt(_ plaintext: Data) throws -> Data {
        guard let key = sendKey else { throw MeshError.handshakeFailed }
        rekeyIfNeeded()
        let box = try ChaChaPoly.seal(plaintext, using: key,
                                      nonce: NoiseSession.transportNonce(sendNonce))
        sendNonce += 1
        messagesSinceRekey += 1
        return box.ciphertext + box.tag
    }

    public func decrypt(_ ciphertext: Data) throws -> Data {
        guard let key = receiveKey,
              ciphertext.count > NoiseSession.tagLen else {
            throw MeshError.handshakeFailed
        }
        let box = try ChaChaPoly.SealedBox(
            nonce: NoiseSession.transportNonce(receiveNonce),
            ciphertext: ciphertext.dropLast(NoiseSession.tagLen),
            tag: ciphertext.suffix(NoiseSession.tagLen))
        let plain = try ChaChaPoly.open(box, using: key)
        receiveNonce += 1
        return plain
    }

    private func rekeyIfNeeded() {
        let expired = Date().timeIntervalSince(sessionStart) > NoiseSession.rekeyTimeLimit
        guard messagesSinceRekey >= NoiseSession.rekeyMessageLimit || expired else { return }
        if let k = sendKey {
            sendKey = SymmetricKey(data: Blake2s.hash(
                k.withUnsafeBytes { Data($0) }, digestLength: 32))
        }
        if let k = receiveKey {
            receiveKey = SymmetricKey(data: Blake2s.hash(
                k.withUnsafeBytes { Data($0) }, digestLength: 32))
        }
        sendNonce = 0
        receiveNonce = 0
        messagesSinceRekey = 0
        sessionStart = Date()
    }
}
