import Foundation
import CryptoKit
import GodstoneCore

// T38 (section 15): the one signed SOS envelope -- iOS twin of SignedSosV1.kt.
//
// ```text
// frame payload   = ASCII("SOS1") || signature(64) || unsigned payload
// unsigned payload = version(1)=0x01 || identityBinding(133)
//                  || created_at_le(4) || time_quality(1) || nonce(16)
//                  || body_len_be(2) || utf8 body (<= 400, strict)
// msg_id   = BLAKE2s-128("GMP2-MSGID" || node_id || created_at_le || nonce || unsigned)
// signature = Ed25519(signing seed, msg_id || ASCII("SOS1") || unsigned)
// ```
//
// The outer SOS code and the required flags stand forever as the frozen tables
// record them (wire_v2.yaml: type 0xF0, ACK_REQ | RELAY_OK); this file only
// sets them, never reads them into new meaning. The identity binding is the
// T13 IdentityBindingV1 reused verbatim -- serialized 133 = version ||
// generation_be || signing_pub || static_dh_pub || binding_signature, its
// 80-byte preimage under the GMP2-IDBIND domain, and node_id =
// BLAKE2s-128(signing_pub) is the ONLY honest node identity: the receiver
// DERIVES it from the embedded key and never trusts a claim. The structural
// gate is DELEGATED, not duplicated: SosFrameValidator keeps its patch-15
// scope and the cryptographic gate composes behind it -- the section-15 split
// under which the structural golden fixtures (zero signature slots) pass the
// validator while runtime authentication refuses them by name.
//
// The receiver distinguishes the authenticated KEY from the verified PERSON:
// verification alone announces key material; a caller holding a peer
// directory may pass the claimed node id as expectedNodeId and the equation
// is checked against it. An absent directory (nil) fabricates no trust
// decision either way, and no approval state moves on this path. Nothing
// here ever throws out of the receiver loop: every refusal is a typed
// SosAuthResult.unauthenticated with a reason from the table.
//
// The vectors of crypto/sos_v1_vectors.json (generated by
// crypto/gen_sos_v1_vectors.py) are the single source of truth for BOTH
// isles. On this isle the host Ed25519 layer signs randomized (the T83
// finding), so the court verifies the pinned signatures and re-derives the
// pinned msg_ids, but never byte-pins a freshly authored signature; the
// authorship legs here assert canonical STRUCTURE and verifier acceptance.

/// The table of named refusals; the court and the roster match on these raw
/// values, identical across the isles.
public enum SosReason: String {
    case wrongType = "wrong_type"
    case missingRequiredFlags = "missing_required_flags"
    case malformed = "malformed"
    case bodyLength = "body_length"
    case timeQuality = "time_quality"
    case unknownTimePairing = "unknown_time_pairing"
    case messageIdMismatch = "message_id_mismatch"
    case identityBinding = "identity_binding"
    case signature = "signature"
}

/// The resolved, authenticated distress call. Value semantics; the arrays are
/// copies taken at resolution, and the printed form keeps key material
/// redacted (section-5 privacy: never a whole key, never the body).
public struct VerifiedSos {
    public let senderNodeId: Data
    public let signingPublicKey: Data
    public let staticDhPublicKey: Data
    public let generation: UInt32
    public let createdAtEpochSeconds: Int64
    public let timeQuality: TimeQuality
    public let messageNonce: Data
    public let bodyUtf8: Data
    public let unsignedPayload: Data
    public let frame: FrameV2
}

extension VerifiedSos: CustomStringConvertible {
    /// Section-5 privacy: the printed form carries redacted heads of key
    /// material and byte counts only -- never a whole key, never the body.
    public var description: String {
        return "VerifiedSos(sender=" + sosRedact(senderNodeId) +
            ",key=" + sosRedact(signingPublicKey) +
            ",dh=" + sosRedact(staticDhPublicKey) +
            ",gen=" + String(generation) +
            ",t=" + String(createdAtEpochSeconds) +
            ",tq=" + String(timeQuality.rawValue) +
            ",nonce=" + sosRedact(messageNonce) +
            ",body=" + String(bodyUtf8.count) + "B," +
            "unsigned=" + String(unsignedPayload.count) + "B)"
    }
}

/// Result of the signed-SOS receiving path: authenticated or refused by name.
public enum SosAuthResult {
    case authenticated(VerifiedSos)
    case unauthenticated(reason: SosReason, detail: String?)

    /// Refusal constructor with an optional redacted-narrative detail.
    public static func refuse(_ reason: SosReason, _ detail: String? = nil) -> SosAuthResult {
        return .unauthenticated(reason: reason, detail: detail)
    }
}

/// The signing authority the composition root wires for the SOS path (T54 lab
/// graph binds it to the durable identity; the courts bind fixed vectors).
public protocol SosSigningAuthority: AnyObject {
    /// A fresh 16-byte nonce per authorship (payload-independent freshness).
    func currentNonce() -> Data
    /// The 32-byte Ed25519 seed, or nil while the node holds no signing key.
    func currentSigningSeed() -> Data?
    /// The 32-byte static DH public key pairing with the seed.
    func currentStaticDhPublicKey() -> Data?
    /// The durable generation counter the binding is struck under.
    func currentGeneration() -> UInt32
    /// Wall clock in whole epoch seconds; 0 announces the unknown-time rule.
    func currentTimeEpochSeconds() -> Int64
}

/// Consumers of authenticated distress indications ONLY. An unauthenticated
/// frame never reaches an observer; no trust or approval state moves here.
public protocol SosObserver: AnyObject {
    func onSosAuthenticated(view: VerifiedSos)
    func onSosUnauthenticated(frame: FrameV2, reason: SosReason)
}

/// Refusal of the authoring path: the author refuses to strike what the
/// receiver would have to refuse. Throws carry the same table as the names.
public struct SosAuthorError: Error {
    public let reason: String
    public init(_ reason: String) { self.reason = reason }
}

private let sosHexDigits: [UInt8] = Array("0123456789ABCDEF".utf8)

private func sosHexAll(_ bytes: [UInt8]) -> String {
    var hexes: [UInt8] = []
    hexes.reserveCapacity(bytes.count * 2)
    for b in bytes {
        hexes.append(sosHexDigits[Int(b >> 4)])
        hexes.append(sosHexDigits[Int(b & 0x0F)])
    }
    return String(bytes: hexes, encoding: .ascii) ?? "-"
}

private func sosRedact(_ bytes: Data) -> String {
    let b = [UInt8](bytes)
    if b.isEmpty { return "-" }
    if b.count <= 8 { return sosHexAll(b) }
    return sosHexAll(Array(b[0..<4])) + ".." + sosHexAll(Array(b[(b.count - 4)..<b.count]))
}

public enum SignedSosV1 {
    /// The four magic bytes; equal to SosFrameValidator.payloadMagic by law.
    public static let magic: [UInt8] = [0x53, 0x4F, 0x53, 0x31] // "SOS1"
    public static let payloadVersion: UInt8 = 0x01
    public static let signatureBytes: Int = 64
    public static let nonceBytes: Int = 16
    public static let bodyBudgetMax: Int = 400

    /// offsets in the unsigned payload, counted in bytes
    public static let offVersion: Int = 0
    public static let offBinding: Int = 1
    public static let offCreatedLe: Int = 134   // offBinding + 133
    public static let offTimeQuality: Int = 138 // offCreatedLe + 4
    public static let offNonce: Int = 139       // offTimeQuality + 1
    public static let offBodyLen: Int = 155     // offNonce + 16
    public static let offBody: Int = 157        // offBodyLen + 2
    public static let unsignedMin: Int = 157

    private static func writeU32Le(_ data: inout Data, _ value: UInt32) {
        data.append(UInt8(value & 0xFF))
        data.append(UInt8((value >> 8) & 0xFF))
        data.append(UInt8((value >> 16) & 0xFF))
        data.append(UInt8((value >> 24) & 0xFF))
    }

    private static func readU32Le(_ b: [UInt8], _ at: Int) -> UInt32 {
        return UInt32(b[at]) | (UInt32(b[at + 1]) << 8) | (UInt32(b[at + 2]) << 16) |
            (UInt32(b[at + 3]) << 24)
    }

    private static func readU16Be(_ b: [UInt8], _ at: Int) -> Int {
        return (Int(b[at]) << 8) | Int(b[at + 1])
    }

    // ------------------------------------------------------------------ builders

    /// Assemble the unsigned payload; nil on any non-canonical input -- the
    /// author refuses to emit what the receiver would have to refuse.
    public static func unsignedPayload(binding: Data, createdAtEpochSeconds: Int64,
                                       timeQuality: TimeQuality, messageNonce: Data,
                                       bodyUtf8: Data) -> Data? {
        guard binding.count == identityBindingSerializedLength,
              messageNonce.count == nonceBytes,
              bodyUtf8.count <= bodyBudgetMax,
              createdAtEpochSeconds >= 0, createdAtEpochSeconds <= Int64(UInt32.max),
              SignedMessageV1.isWellFormedUtf8([UInt8](bodyUtf8))
        else { return nil }
        // the unknown-time rule: the clock and the quality stand and fall together
        if !((createdAtEpochSeconds == 0) == (timeQuality == .unknown)) { return nil }
        var out = Data(capacity: unsignedMin + bodyUtf8.count)
        out.append(payloadVersion)
        out.append(binding)
        writeU32Le(&out, UInt32(createdAtEpochSeconds))
        out.append(UInt8(timeQuality.rawValue))
        out.append(messageNonce)
        out.append(UInt8((bodyUtf8.count >> 8) & 0xFF))
        out.append(UInt8(bodyUtf8.count & 0xFF))
        out.append(bodyUtf8)
        return out
    }

    /// The section-15 transcript: msg_id || ASCII("SOS1") || unsigned payload.
    public static func signatureTranscript(messageId: Data, unsigned: Data) -> Data {
        var out = Data(capacity: messageId.count + magic.count + unsigned.count)
        out.append(messageId)
        out.append(contentsOf: magic)
        out.append(unsigned)
        return out
    }

    /// The frozen MessageId formula, taken here over the UNSIGNED span.
    public static func deriveMessageId(senderNodeId: Data, createdAtEpochSeconds: Int64,
                                       messageNonce: Data, unsigned: Data) -> Data {
        return MessageId.derive(senderNodeId: senderNodeId,
                                createdAtEpochSeconds: createdAtEpochSeconds,
                                messageNonce: messageNonce,
                                payload: unsigned)
    }

    // ------------------------------------------------------------------ author

    /// Sign one distress call end to end: strike the identity binding under
    /// the local key (the T13 equation, reused not rewritten), assemble the
    /// unsigned payload, derive msg_id over it, sign the transcript, and set
    /// the outer fields exactly as the frozen tables record them.
    public static func author(signingSeed: Data, staticDhPublicKey: Data,
                              generation: UInt32, createdAtEpochSeconds: Int64,
                              timeQuality: TimeQuality, messageNonce: Data,
                              bodyUtf8: Data) throws -> FrameV2 {
        guard signingSeed.count == identityBindingSigningKeyLength,
              staticDhPublicKey.count == identityBindingStaticDhKeyLength,
              messageNonce.count == nonceBytes,
              bodyUtf8.count <= bodyBudgetMax,
              createdAtEpochSeconds >= 0, createdAtEpochSeconds <= Int64(UInt32.max)
        else { throw SosAuthorError("authoritative material or fixed field out of range") }
        guard SignedMessageV1.isWellFormedUtf8([UInt8](bodyUtf8)) else {
            throw SosAuthorError("body must be well-formed UTF-8")
        }
        guard (createdAtEpochSeconds == 0) == (timeQuality == .unknown) else {
            throw SosAuthorError("unknown time binds createdAt 0 with timeQuality UNKNOWN; the two stand and fall together")
        }
        guard let pair = try? Curve25519.Signing.PrivateKey(rawRepresentation: signingSeed),
              pair.rawRepresentation.count == identityBindingSigningKeyLength
        else { throw SosAuthorError("signing seed is not a usable Ed25519 key") }
        let signingPublicKey = pair.publicKey.rawRepresentation
        guard signingPublicKey.count == identityBindingSigningKeyLength else {
            throw SosAuthorError("derived signing public key is not 32 bytes")
        }
        let binding = IdentityBindingV1(
            version: identityBindingVersion,
            generation: generation,
            signingPublicKey: signingPublicKey,
            staticDhPublicKey: staticDhPublicKey,
            signature: try pair.signature(for: IdentityBindingV1.signaturePreimage(
                generation: generation,
                signingPublicKey: signingPublicKey,
                staticDhPublicKey: staticDhPublicKey)))
        guard let unsigned = unsignedPayload(binding: binding.encode(),
                                             createdAtEpochSeconds: createdAtEpochSeconds,
                                             timeQuality: timeQuality,
                                             messageNonce: messageNonce,
                                             bodyUtf8: bodyUtf8) else {
            throw SosAuthorError("unsigned payload is not canonical")
        }
        let senderNodeId = IdentityBindingV1.deriveNodeId(signingPublicKey: signingPublicKey)
        let msgId = deriveMessageId(senderNodeId: senderNodeId,
                                    createdAtEpochSeconds: createdAtEpochSeconds,
                                    messageNonce: messageNonce, unsigned: unsigned)
        let signature = try pair.signature(for: signatureTranscript(messageId: msgId, unsigned: unsigned))
        guard signature.count == signatureBytes else {
            throw SosAuthorError("Ed25519 must produce a 64-byte signature")
        }
        var sealed = Data(capacity: magic.count + signatureBytes + unsigned.count)
        sealed.append(contentsOf: magic)
        sealed.append(signature)
        sealed.append(unsigned)
        return FrameV2(
            type: .sos,
            msgId: msgId,
            routingTag: Data(repeating: 0, count: 4), // broadcast: no destination hint
            ttl: FrameV2.maxTtl,
            hopCount: 0,
            flags: UInt16(FrameV2.Flags.ack_req | FrameV2.Flags.relay_ok),
            payload: sealed)
    }

    // ------------------------------------------------------------------ receiver

    /// Authenticate one received SOS frame. Gate order is the validator order:
    /// structural (delegated to SosFrameValidator), then shape, then time,
    /// then the identity equation, then the hash binding, then the signature.
    /// Never throws: every refusal is a named reason.
    public static func verify(_ frame: FrameV2, expectedNodeId: Data? = nil) -> SosAuthResult {
        // -- structural gate, delegated (the patch-15 split of concerns) ------
        switch SosFrameValidator.validate(frame) {
        case .ok: break
        case .wrongType: return .refuse(.wrongType)
        case .missingRequiredFlags: return .refuse(.missingRequiredFlags)
        default: return .refuse(.malformed, "envelope")
        }
        if let claim = expectedNodeId, claim.count != identityBindingNodeIdLength {
            return .refuse(.malformed, "expected node id")
        }
        let payload = [UInt8](frame.payload)
        let totalMin = magic.count + signatureBytes + unsignedMin
        guard payload.count >= totalMin,
              payload.count <= totalMin + bodyBudgetMax
        else { return .refuse(.malformed, "frame length") }
        let signature = Data(payload[(magic.count)..<(magic.count + signatureBytes)])
        let unsigned = Data(payload[(magic.count + signatureBytes)..<payload.count])
        let u = [UInt8](unsigned)
        guard u.count >= unsignedMin else { return .refuse(.malformed, "unsigned span") }
        guard u[offVersion] == payloadVersion else { return .refuse(.malformed, "payload version") }
        let bodyLen = readU16Be(u, offBodyLen)
        guard bodyLen <= bodyBudgetMax else { return .refuse(.bodyLength, "budget") }
        guard u.count == unsignedMin + bodyLen else { return .refuse(.bodyLength) }
        let createdAt = Int64(readU32Le(u, offCreatedLe))
        guard let timeQuality = TimeQuality(rawValue: Int(u[offTimeQuality])) else {
            return .refuse(.timeQuality)
        }
        guard (createdAt == 0) == (timeQuality == .unknown) else {
            return .refuse(.unknownTimePairing)
        }
        let nonce = Data(u[offNonce..<offNonce + nonceBytes])
        let bindingBytes = Data(u[offBinding..<offBinding + identityBindingSerializedLength])
        // -- the binding: parse, re-seal, and verify its own seal ----------------
        guard let binding = try? IdentityBindingV1.parse(bindingBytes) else {
            return .refuse(.identityBinding, "parse")
        }
        guard binding.version == identityBindingVersion else {
            return .refuse(.identityBinding, "version")
        }
        let preimage = IdentityBindingV1.signaturePreimage(
            generation: binding.generation,
            signingPublicKey: binding.signingPublicKey,
            staticDhPublicKey: binding.staticDhPublicKey)
        guard let publicKey = try? Curve25519.Signing.PublicKey(
                rawRepresentation: binding.signingPublicKey),
              publicKey.isValidSignature(binding.signature, for: preimage)
        else { return .refuse(.identityBinding, "binding signature") }
        // -- the node identity is DERIVED, never trusted ------------------------
        let derivedNode = IdentityBindingV1.deriveNodeId(signingPublicKey: binding.signingPublicKey)
        if let claim = expectedNodeId, derivedNode != claim {
            // the authenticated key is not the key of the claimed person
            return .refuse(.identityBinding, "person")
        }
        // -- the hash binding: re-derive msg_id over the untouched unsigned span -
        let msgRe = deriveMessageId(senderNodeId: derivedNode,
                                    createdAtEpochSeconds: createdAt,
                                    messageNonce: nonce, unsigned: unsigned)
        guard msgRe == frame.msgId else { return .refuse(.messageIdMismatch) }
        // -- the signature: possession of the embedded key over the transcript ---
        guard let signer = try? Curve25519.Signing.PublicKey(
                rawRepresentation: binding.signingPublicKey),
              signer.isValidSignature(signature, for: signatureTranscript(messageId: msgRe,
                                                                          unsigned: unsigned))
        else { return .refuse(.signature) }
        let body = Data(u[offBody..<u.count])
        // The body's UTF-8 shape was bound into the hash before signing; a byte
        // that broke the shape would have broken the hash first. The re-check
        // is defense in depth for the consumer of VerifiedSos.
        guard SignedMessageV1.isWellFormedUtf8([UInt8](body)) else {
            return .refuse(.malformed, "utf-8")
        }
        return .authenticated(VerifiedSos(
            senderNodeId: derivedNode,
            signingPublicKey: binding.signingPublicKey,
            staticDhPublicKey: binding.staticDhPublicKey,
            generation: binding.generation,
            createdAtEpochSeconds: createdAt,
            timeQuality: timeQuality,
            messageNonce: nonce,
            bodyUtf8: body,
            unsignedPayload: unsigned,
            frame: frame))
    }

    /// The node identity a signing public key binds to (the T13 equation).
    public static func nodeIdOfSigningKey(_ signingPublicKey: Data) -> Data {
        return IdentityBindingV1.deriveNodeId(signingPublicKey: signingPublicKey)
    }
}
