import Foundation

// Hand-written runtime helper -- NOT a codegen artifact. The Swift twin of
// android/.../wire/v2/MessageId.kt. Stage 3 Phase C pins both runtimes to the
// locked crypto/gmp21_vectors.json fixture (generated by crypto/gmp21.py) so
// the 16-byte msg_id is byte-identical across platforms.

/// GMP/2.1 message-id derivation (ADR-001 §3.3).
///
///     msg_id = BLAKE2s-128(sender_node_id ‖ created_at_le ‖ payload)   (16 bytes)
///
/// `created_at` is a uint32 epoch-second count serialised LITTLE-ENDIAN in the
/// msg_id preimage (ADR-001 §3.3 spells `created_at_le`; §3.4's `uint32_be(round)`
/// confirms `_le`/`_be` are byte-order specifiers). The 32-byte header itself
/// stays big-endian (§4); this little-endian encoding is internal to the hash
/// input. Byte-for-byte parity with Android is pinned by MessageIdTests against
/// crypto/gmp21_vectors.json.
public enum MessageId {

    public static let nodeIdBytes = 16
    public static let msgIdBytes = 16

    /// BLAKE2s-128 over (sender_node_id[16] ‖ created_at_le[4] ‖ payload).
    public static func derive(
        senderNodeId: Data,
        createdAtEpochSeconds: Int64,
        payload: Data
    ) -> Data {
        precondition(senderNodeId.count == nodeIdBytes, "sender_node_id must be 16 bytes")
        var input = Data(capacity: senderNodeId.count + 4 + payload.count)
        input.append(senderNodeId)
        input.append(uint32Le(createdAtEpochSeconds))
        input.append(payload)
        return Blake2s.hash(input, digestLength: msgIdBytes)
    }

    /// Little-endian uint32 of an epoch-second count (ADR-001 §3.3 created_at_le).
    public static func uint32Le(_ epochSeconds: Int64) -> Data {
        let v = UInt32(truncatingIfNeeded: epochSeconds)
        return Data([UInt8(v & 0xFF),
                     UInt8((v >> 8) & 0xFF),
                     UInt8((v >> 16) & 0xFF),
                     UInt8((v >> 24) & 0xFF)])
    }

    /// Big-endian uint32 (header fields, §4).
    public static func uint32Be(_ epochSeconds: Int64) -> Data {
        let v = UInt32(truncatingIfNeeded: epochSeconds)
        return Data([UInt8((v >> 24) & 0xFF),
                     UInt8((v >> 16) & 0xFF),
                     UInt8((v >> 8) & 0xFF),
                     UInt8(v & 0xFF)])
    }
}