import Foundation

// Hand-written runtime helper -- NOT a codegen artifact. The Swift twin of
// android/.../wire/v2/MessageId.kt. Stage 3 Phase C / Stage 4 C6.7.1 pins both runtimes
// to the locked crypto/gmp21_vectors.json fixture (generated by crypto/gmp21.py) so
// the 16-byte msg_id is byte-identical across platforms.

/// GMP/2.1 logical message-id derivation (ADR-001 §3.3, C6.7.1).
///
///     msg_id = BLAKE2s-128(b"GMP2-MSGID" ‖ sender_node_id[16] ‖ created_at_le[4] ‖ message_nonce[16] ‖ plaintext)
///
/// `created_at` is a uint32 epoch-second count serialised LITTLE-ENDIAN in the
/// msg_id preimage (ADR-001 §3.3 created_at_le). The 32-byte header itself
/// stays big-endian (§4); this little-endian encoding is internal to the hash
/// input. Byte-for-byte parity with Android is pinned by MessageIdTests against
/// crypto/gmp21_vectors.json.
public enum MessageId {

    public static let nodeIdBytes = 16
    public static let msgIdBytes = 16
    public static let messageNonceBytes = 16
    public static let domainSeparatorText = "GMP2-MSGID"
    public static let domain = Data(domainSeparatorText.utf8)

    /// BLAKE2s-128 over (b"GMP2-MSGID" ‖ sender_node_id[16] ‖ created_at_le[4] ‖ message_nonce[16] ‖ plaintext).
    public static func derive(
        senderNodeId: Data,
        createdAtEpochSeconds: Int64,
        messageNonce: Data,
        plaintext: Data
    ) -> Data {
        precondition(senderNodeId.count == nodeIdBytes, "sender_node_id must be 16 bytes")
        precondition(messageNonce.count == messageNonceBytes, "message_nonce must be 16 bytes")
        var input = Data(capacity: domain.count + senderNodeId.count + 4 + messageNonce.count + plaintext.count)
        input.append(domain)
        input.append(senderNodeId)
        input.append(uint32Le(createdAtEpochSeconds))
        input.append(messageNonce)
        input.append(plaintext)
        return Blake2s.hash(input, digestLength: msgIdBytes)
    }

    /// Convenience overload with LogicalMessageIdentity.
    public static func derive(
        senderNodeId: Data,
        identity: LogicalMessageIdentity,
        plaintext: Data
    ) -> Data {
        derive(
            senderNodeId: senderNodeId,
            createdAtEpochSeconds: identity.createdAtEpochSeconds,
            messageNonce: identity.messageNonce,
            plaintext: plaintext
        )
    }

    /// Convenience overload for payload parameter name.
    public static func derive(
        senderNodeId: Data,
        createdAtEpochSeconds: Int64,
        messageNonce: Data,
        payload: Data
    ) -> Data {
        derive(
            senderNodeId: senderNodeId,
            createdAtEpochSeconds: createdAtEpochSeconds,
            messageNonce: messageNonce,
            plaintext: payload
        )
    }

    /// Generate a 16-byte CSPRNG message nonce for a new logical send.
    public static func generateNonce() -> Data {
        var nonce = Data(count: messageNonceBytes)
        let status = nonce.withUnsafeMutableBytes { ptr in
            SecRandomCopyBytes(kSecRandomDefault, messageNonceBytes, ptr.baseAddress!)
        }
        precondition(status == errSecSuccess, "SecRandomCopyBytes failed to generate message nonce")
        return nonce
    }

    /// Little-endian uint32 of an epoch-second count (ADR-001 §3.3 created_at_le).
    public static func uint32Le(_ epochSeconds: Int64) -> Data {
        let v = UInt32(truncatingIfNeeded: epochSeconds)
        return Data([UInt8(v & 0xFF),
                     UInt8((v >> 8) & 0xFF),
                     UInt8((v >> 16) & 0xFF),
                     UInt8((v >> 24) & 0xFF)])
    }

    /// Big-endian uint32 (header fields, §4).
    public static func uint32Be(_ epochSeconds: Int64) -> Data {
        let v = UInt32(truncatingIfNeeded: epochSeconds)
        return Data([UInt8((v >> 24) & 0xFF),
                     UInt8((v >> 16) & 0xFF),
                     UInt8((v >> 8) & 0xFF),
                     UInt8(v & 0xFF)])
    }
}