import Foundation
import Security

// Hand-written runtime helper -- NOT a codegen artifact. The Swift twin of
// android/.../router/ProofOfWork.kt. Stage 3 Phase C / Stage 4 C6.7.1 pins both runtimes to the
// locked crypto/gmp21_vectors.json fixture (generated by crypto/gmp21.py) so the
// 256-bit PoW digest and the mined nonce are byte-identical across platforms.

/// 20-bit BLAKE2s proof of work, carried inside the sealed, authenticated
/// payload (ADR-001 §3, C6.7.1). Under GMP/2.1 msg_id is a content hash and cannot be
/// mutated, so the search nonce moves into the sealed payload where it is
/// authenticated. PoW is a **recipient-side** check, not a relay gate: a relay
/// cannot unseal the payload, so it cannot verify the stamp; relay-side
/// anti-flood is the PeerGovernor token buckets. The recipient, after
/// SealedSender.open, verifies the nonce against the unsealed content.
///
/// CANONICAL PREIMAGE (ADR-001 §3.3, Stage 3 Phase C / Stage 4 C6.7.2):
///
///     BLAKE2s-256(ASCII("GMP2-POW") ‖ pow_nonce[8] ‖ sender_node_id[16] ‖ created_at_le[4] ‖
///                 message_nonce[16] ‖ priority_code[1] ‖ type_code[1] ‖ plaintext)
///
/// `created_at` is the same uint32 epoch-second count used in msg_id derivation
/// (§3.3 `created_at_le`), serialised LITTLE-ENDIAN so there is ONE canonical
/// encoding for created_at across every GMP/2.1 derivation. The sealed payload
/// stores created_at in the same little-endian form, so the recipient reconstructs
/// the preimage from the sealed bytes without any byte-order conversion.
///
/// `message_nonce` binds the PoW stamp to the unique logical message identity,
/// preventing PoW reuse across distinct logical sends.
///
/// `priority_code` binds the authenticated priority numeric code into the preimage,
/// preventing priority header downgrade attacks.
///
/// The byte-for-byte parity with Android (ProofOfWork.kt) and the Python reference
/// (crypto/gmp21.py) is pinned by ProofOfWorkTests against gmp21_vectors.json.
public enum ProofOfWork {

    public static let nonceBytes = 8
    /// ADR-001 §3: the production target is a 20-bit-zero BLAKE2s-256 prefix. */
    public static let targetBits = 20
    public static let domainSeparatorText = "GMP2-POW"
    public static let powDomain = Data(domainSeparatorText.utf8)

    /// True iff (ASCII("GMP2-POW") ‖ powNonce ‖ senderNodeId ‖ createdAtLe ‖ messageNonce ‖ priorityCode ‖ typeCode ‖ plaintext)
    /// hashes to a BLAKE2s-256 digest whose top `targetBits` bits are zero.
    ///
    /// `createdAtLe` is the 4-byte LITTLE-ENDIAN created_at carried inside the
    /// sealed payload; the recipient passes the sealed bytes straight through.
    /// `targetBits` defaults to `targetBits` (20, ADR-pinned). A lower value is
    /// exposed solely so unit tests can exercise the mine/verify path without
    /// paying for a ~1M-hash search; production always calls the default.
    public static func verify(
        powNonce: Data,
        senderNodeId: Data,
        createdAtLe: Data,
        messageNonce: Data,
        priorityCode: UInt8,
        typeCode: UInt8,
        plaintext: Data,
        targetBits: Int = ProofOfWork.targetBits
    ) -> Bool {
        precondition(powNonce.count == nonceBytes, "pow_nonce must be \(nonceBytes) bytes")
        precondition(senderNodeId.count == 16, "sender_node_id must be 16 bytes")
        precondition(createdAtLe.count == 4, "created_at must be 4 bytes")
        precondition(messageNonce.count == MessageId.messageNonceBytes, "message_nonce must be 16 bytes")
        precondition(targetBits >= 1 && targetBits <= 32, "targetBits out of range")
        let h = digest(powNonce: powNonce, senderNodeId: senderNodeId,
                       createdAtLe: createdAtLe, messageNonce: messageNonce,
                       priorityCode: priorityCode, typeCode: typeCode, plaintext: plaintext)
        return topBitsZero(h, targetBits: targetBits)
    }

    /// BLAKE2s-256 of the canonical PoW preimage. Exposed (parity with the Python
    /// reference `crypto/gmp21.py` `pow_digest`) so the locked KAT in
    /// `crypto/gmp21_vectors.json` can be asserted BYTE-FOR-BYTE by the platform
    /// tests, not just via the boolean `verify`. The digest is the source of truth
    /// that proves the preimage bytes are identical across Python / Android / iOS.
    public static func digest(
        powNonce: Data,
        senderNodeId: Data,
        createdAtLe: Data,
        messageNonce: Data,
        priorityCode: UInt8,
        typeCode: UInt8,
        plaintext: Data
    ) -> Data {
        precondition(powNonce.count == nonceBytes, "pow_nonce must be \(nonceBytes) bytes")
        precondition(senderNodeId.count == 16, "sender_node_id must be 16 bytes")
        precondition(createdAtLe.count == 4, "created_at must be 4 bytes")
        precondition(messageNonce.count == MessageId.messageNonceBytes, "message_nonce must be 16 bytes")
        var input = Data(capacity: powDomain.count + nonceBytes + 16 + 4 + messageNonce.count + 2 + plaintext.count)
        input.append(powDomain)
        input.append(powNonce)
        input.append(senderNodeId)
        input.append(createdAtLe)
        input.append(messageNonce)
        input.append(priorityCode)
        input.append(typeCode)
        input.append(plaintext)
        return Blake2s.hash(input, digestLength: 32)
    }

    /// Find an 8-byte nonce satisfying the `targetBits` target for the given
    /// unsealed content. At the production 20-bit target this is ~1M BLAKE2s, so
    /// this async function must be called OFF the main actor. It starts from a
    /// cryptographically random nonce and big-endian-increments, remaining
    /// cooperatively cancellable via `Task.checkCancellation()` so a user leaving
    /// the screen does not strand a CPU.
    public static func mine(
        senderNodeId: Data,
        createdAtLe: Data,
        messageNonce: Data,
        priorityCode: UInt8,
        typeCode: UInt8,
        plaintext: Data,
        targetBits: Int = ProofOfWork.targetBits
    ) async throws -> Data {
        precondition(targetBits >= 1 && targetBits <= 32, "targetBits out of range")
        precondition(senderNodeId.count == 16, "sender_node_id must be 16 bytes")
        precondition(createdAtLe.count == 4, "created_at must be 4 bytes")
        precondition(messageNonce.count == MessageId.messageNonceBytes, "message_nonce must be 16 bytes")
        var powNonce = randomNonce()
        while true {
            try Task.checkCancellation()
            let h = digest(powNonce: powNonce, senderNodeId: senderNodeId,
                           createdAtLe: createdAtLe, messageNonce: messageNonce,
                           priorityCode: priorityCode, typeCode: typeCode, plaintext: plaintext)
            if topBitsZero(h, targetBits: targetBits) {
                return powNonce
            }
            increment(&powNonce)
        }
    }

    /// True iff the top `targetBits` bits of `h` are all zero.
    static func topBitsZero(_ h: Data, targetBits: Int) -> Bool {
        var remaining = targetBits
        var i = 0
        while remaining >= 8 {
            if h[i] != 0 { return false }
            remaining -= 8
            i += 1
        }
        if remaining > 0 {
            let mask = UInt8((0xFF << (8 - remaining)) & 0xFF)
            if h[i] & mask != 0 { return false }
        }
        return true
    }

    /// Big-endian increment of an 8-byte nonce; wraps at 2^64 (astronomically never).
    static func increment(_ b: inout Data) {
        var i = b.count - 1
        while i >= 0 {
            if b[i] == 0xFF { b[i] = 0; i -= 1 } else {
                b[i] &+= 1
                return
            }
        }
    }

    private static func randomNonce() -> Data {
        var bytes = [UInt8](repeating: 0, count: nonceBytes)
        let status = SecRandomCopyBytes(kSecRandomDefault, nonceBytes, &bytes)
        precondition(status == errSecSuccess, "SecRandomCopyBytes failed")
        return Data(bytes)
    }
}