// Hand-written runtime helper -- NOT a codegen artifact.
// ci/check_parity.py Invariant A regenerates the wire codecs only; this file is
// the runtime realisation of ADR-001 §3's msg_id derivation and is outside the
// codegen contract. Stage 3 Phase C / Stage 4 C6.7 pins the byte-for-byte iOS twin
// against the locked crypto/gmp21_vectors.json fixture (generated by crypto/gmp21.py).
package io.godstone.mesh.wire.v2

import org.bouncycastle.crypto.digests.Blake2sDigest
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.SecureRandom

/**
 * GMP/2.1 logical message-id derivation (ADR-001 §3.3, C6.7.1).
 *
 *     msg_id = BLAKE2s-128(ASCII("GMP2-MSGID") ‖ sender_node_id[16] ‖ created_at_le[4] ‖ message_nonce[16] ‖ plaintext)
 *
 * The sender generates an immutable [LogicalMessageIdentity] when authoring a new
 * logical message, computes msg_id, and places it in the 16-byte header field.
 * Retries re-transmit the exact persisted FrameV2; newly authored sends generate
 * a fresh [LogicalMessageIdentity] to guarantee unique logical message identities even for
 * identical content, identical timestamps, or multiple simultaneous recipients.
 *
 * `message_nonce` is sealed inside the authenticated payload prefix (ADR-001 §3.3.4):
 *     sealed_inner = message_nonce[16] ‖ pow_nonce[8] ‖ created_at_le[4] ‖ plaintext
 *
 * The recipient re-derives msg_id after unsealing via [derive] to authenticate the
 * binding between sender, creation time, message nonce, and plaintext.
 *
 * The byte-for-byte parity is pinned by MessageIdTest against crypto/gmp21_vectors.json.
 */
object MessageId {

    const val NODE_ID_BYTES = 16
    const val MSG_ID_BYTES = 16
    const val NONCE_BYTES = 16

    const val DOMAIN_SEPARATOR_TEXT = "GMP2-MSGID"
    private val MSG_ID_DOMAIN_BYTES = DOMAIN_SEPARATOR_TEXT.toByteArray(Charsets.US_ASCII)

    /**
     * BLAKE2s-128 over:
     *     ASCII("GMP2-MSGID") ‖ sender_node_id[16] ‖ created_at_le[4] ‖ message_nonce[16] ‖ plaintext
     */
    fun derive(
        senderNodeId: ByteArray,
        createdAtEpochSeconds: Long,
        messageNonce: ByteArray,
        plaintext: ByteArray
    ): ByteArray {
        require(senderNodeId.size == NODE_ID_BYTES) { "sender_node_id must be 16 bytes" }
        require(messageNonce.size == NONCE_BYTES) { "message_nonce must be 16 bytes" }
        val d = Blake2sDigest(null, MSG_ID_BYTES, null, null)
        d.update(MSG_ID_DOMAIN_BYTES, 0, MSG_ID_DOMAIN_BYTES.size)
        d.update(senderNodeId, 0, senderNodeId.size)
        val leBytes = uint32Le(createdAtEpochSeconds)
        d.update(leBytes, 0, leBytes.size)
        d.update(messageNonce, 0, messageNonce.size)
        d.update(plaintext, 0, plaintext.size)
        val out = ByteArray(MSG_ID_BYTES)
        d.doFinal(out, 0)
        return out
    }

    /** Convenience overload using an immutable [LogicalMessageIdentity]. */
    fun derive(
        senderNodeId: ByteArray,
        identity: LogicalMessageIdentity,
        plaintext: ByteArray
    ): ByteArray = derive(senderNodeId, identity.createdAtEpochSeconds, identity.messageNonce, plaintext)

    /** Generate a 16-byte CSPRNG message nonce for a new logical send. */
    fun generateNonce(rng: SecureRandom = SecureRandom()): ByteArray =
        ByteArray(NONCE_BYTES).also { rng.nextBytes(it) }

    /** Little-endian uint32 of an epoch-second count (ADR-001 §3.3 created_at_le). */
    fun uint32Le(epochSeconds: Long): ByteArray =
        ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN)
            .putInt(epochSeconds.toInt()).array()

    /** Big-endian uint32 encoding (header fields, §4). */
    fun uint32Be(epochSeconds: Long): ByteArray =
        ByteBuffer.allocate(4).putInt(epochSeconds.toInt()).array()
}