// Hand-written runtime helper -- NOT a codegen artifact.
// ci/check_parity.py Invariant A regenerates the wire codecs only; this file is
// the runtime realisation of ADR-001 §3's msg_id derivation and is outside the
// codegen contract. Stage 3 Phase C pins the byte-for-byte iOS twin against the
// locked crypto/gmp21_vectors.json fixture (generated by crypto/gmp21.py).
package io.godstone.mesh.wire.v2

import org.bouncycastle.crypto.digests.Blake2sDigest
import java.nio.ByteBuffer

/**
 * GMP/2.1 message-id derivation (ADR-001 §3.3).
 *
 *     msg_id = BLAKE2s-128(sender_node_id ‖ created_at_le ‖ payload)   (16 bytes)
 *
 * The sender computes msg_id when it builds a frame and places it in the 16-byte
 * header field. Relays and the recipient use the header msg_id directly for
 * dedup and bloom anti-entropy — they do NOT recompute it (a relay cannot see
 * the sealed sender, and re-derivation is a recipient integrity check, not a
 * relay gate). The recipient may re-derive after unsealing to authenticate the
 * binding between sender, creation time and payload.
 *
 * `created_at` is a uint32 epoch-second count. ADR-001 §3.3 spells the input
 * `created_at_le` and §3.4 spells the bloom input `uint32_be(round)`; the
 * contrast is deliberate — `_le` and `_be` are byte-order specifiers, not "the
 * logical element". The created_at epoch-second count is therefore serialised
 * LITTLE-ENDIAN in the msg_id preimage. (The 32-byte header itself remains
 * big-endian throughout per §4; this little-endian encoding is internal to the
 * msg_id hash input only.) The byte-for-byte parity is pinned by
 * MessageIdTest against crypto/gmp21_vectors.json.
 */
object MessageId {

    /** BLAKE2s-128 over (sender_node_id[16] ‖ created_at_le[4] ‖ payload). */
    fun derive(senderNodeId: ByteArray, createdAtEpochSeconds: Long, payload: ByteArray): ByteArray {
        require(senderNodeId.size == 16) { "sender_node_id must be 16 bytes" }
        val d = Blake2sDigest(null, 16, null, null)
        d.update(senderNodeId, 0, senderNodeId.size)
        d.update(uint32Le(createdAtEpochSeconds), 0, 4)
        d.update(payload, 0, payload.size)
        val out = ByteArray(16)
        d.doFinal(out, 0)
        return out
    }

    /** Little-endian uint32 of an epoch-second count (ADR-001 §3.3 created_at_le). */
    fun uint32Le(epochSeconds: Long): ByteArray =
        ByteBuffer.allocate(4).order(java.nio.ByteOrder.LITTLE_ENDIAN)
            .putInt(epochSeconds.toInt()).array()

    /** Big-endian uint32 encoding (header fields, §4). */
    fun uint32Be(epochSeconds: Long): ByteArray =
        ByteBuffer.allocate(4).putInt(epochSeconds.toInt()).array()
}