#!/usr/bin/env python3
"""Emit crypto/port_vectors.json -- vectors the KOTLIN and SWIFT test targets consume.

    python -m crypto.port_vectors

WHY THIS EXISTS.

crypto/test_conformance.py step 1 asserts:

    hashlib.blake2s(b"abc").hexdigest() == rfc["blake2s_256_abc"]

That checks CPython's stdlib against RFC 7693. CPython's BLAKE2s is not in
doubt. The implementation that IS in doubt -- the hand-rolled Blake2s.swift that
the entire Noise handshake sits on -- is never executed by any control in this
repository. The RFC vectors were pointed at the wrong implementation.

The same gap covers the Noise transcript (Invariant D validates the Python
reference against a fixture that reference generated) and the safety gate
(Invariant G6 compared four constants and missed an IDF equation that differed
by 18x).

This file emits one JSON that the mobile test targets read directly, so a
platform port is checked against the pinned values instead of being assumed to
match them.
"""
from __future__ import annotations
import hashlib, json, math, pathlib

OUT = pathlib.Path(__file__).resolve().parent / "port_vectors.json"

def build() -> dict:
    # BLAKE2s -- for Blake2s.swift and BouncyCastle's Blake2sDigest.
    blake = {
        "abc": hashlib.blake2s(b"abc").hexdigest(),
        "empty": hashlib.blake2s(b"").hexdigest(),
        "blake2s_128_abc": hashlib.blake2s(b"abc", digest_size=16).hexdigest(),
        "blake2s_64_abc": hashlib.blake2s(b"abc", digest_size=8).hexdigest(),
        # 64-byte input exercises the exact-one-block boundary, where an
        # off-by-one in the last-block flag hides.
        "block_boundary_64": hashlib.blake2s(b"A" * 64).hexdigest(),
        "block_boundary_65": hashlib.blake2s(b"A" * 65).hexdigest(),
    }

    # Safety gate -- constants AND the IDF equation. The V3 iOS defect was in
    # the equation while every constant matched.
    n = 27
    idf = {str(d): round(math.log((n - d + 0.5) / (d + 0.5) + 1.0), 6)
           for d in (1, 3, 10, 20, 26)}
    gate = {
        "anchor_recall_floor": 0.60,
        "colocation_floor": 0.50,
        "domain_coherence_floor": 0.40,
        "caveat_margin": 0.15,
        "min_anchor_len": 3,
        "stem_prefix_len": 5,
        "idf_n": n,
        "idf_by_df": idf,
        "_note": "idf = ln((n - df + 0.5) / (df + 0.5) + 1.0). The WHOLE quotient "
                 "plus 1.0 is inside the log. Swift closes log() early if the "
                 "outer parentheses are dropped, which is defect A-20.",
        # Stemming: an early gate draft refused "how long should I boil water"
        # because boil and boiling were different terms.
        "stems": {"boiling": "boil", "purification": "purif", "running": "run",
                  "doses": "dose", "minutes": "minut"},
    }

    # Noise XX -- message sizes with empty payloads. The V3 iOS implementation
    # produced [32, 80, 48] here, which is defect A-19.
    noise = {
        "protocol_name": "Noise_XX_25519_ChaChaPoly_BLAKE2s",
        "message_sizes": [32, 96, 64],
        "_note": "msg2 = e(32) + AEAD(s)(48) + AEAD(payload)(16). "
                 "msg3 = AEAD(s)(48) + AEAD(payload)(16). Omitting either "
                 "payload yields [32, 80, 48] and cannot interoperate.",
        "handshake_nonce_rule": "resets to 0 on MixKey, otherwise increments; "
                                "msg3 encrypts s at n=1",
        "transport_nonce": "4 zero bytes || 8 bytes LITTLE-endian counter",
    }

    return {
        "_comment": "GENERATED by crypto/port_vectors.py. The values are mirrored in "
                    "Kotlin and Swift port tests; ci/integration.py requires those "
                    "tests to exist. A control must observe the port, not only a model.",
        "blake2s": blake,
        "safety_gate": gate,
        "noise_xx": noise,
    }

def main() -> int:
    d = build()
    OUT.write_text(json.dumps(d, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}")
    print(f"  blake2s vectors   {len(d['blake2s'])}")
    print(f"  gate idf points   {len(d['safety_gate']['idf_by_df'])}")
    print(f"  noise xx sizes    {d['noise_xx']['message_sizes']}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
