import Foundation
import CryptoKit
import GodstoneCore

/// Noise_XX_25519_ChaChaPoly_BLAKE2s.
///
/// V4 REWRITE. The V3 implementation was not merely unreachable -- it was
/// wire-non-conformant and could not have completed a handshake against
/// noise-java even with every call site wired. Measured against the repository's
/// own pinned vectors:
///
///     pinned spec message sizes : [32, 96, 64]
///     V3 NoiseSession.swift     : [32, 80, 48]
///
/// Three defects, all fixed here:
///
///  (a) MESSAGES 2 AND 3 OMITTED THEIR PAYLOAD. XX message 2 is `e, ee, s, es`
///      followed by an encrypted payload; V3 returned `e + encryptedStatic` and
///      stopped. Message 3 is `s, se` plus a payload; V3 returned the static
///      only. Hence 80 and 48 instead of 96 and 64.
///
///  (b) MESSAGE 2 WAS PARSED AS ONE CIPHERTEXT. `decryptAndHash(msg2.suffix(from: 32))`
///      handed 64 bytes to a single AEAD open, yielding a 48-byte "static key".
///      X25519 requires 32, so the parse threw before any DH occurred.
///
///  (c) THE HANDSHAKE NONCE WAS PINNED TO ZERO. Both encryptAndHash and
///      decryptAndHash built `ChaChaPoly.Nonce(data: Data(count: 12))`. In Noise
///      the handshake nonce resets to 0 on MixKey and otherwise INCREMENTS. In
///      message 3 the initiator encrypts `s` under the `es` key at n = 1,
///      because message 2's payload decrypt already consumed n = 0.
///
/// None of this was visible to Invariant D, which validates the PYTHON
/// reference against a fixture generated by that same reference and never
/// executes Swift. See docs/adr/ADR-002 and ci/mutations.py.
///
/// The prologue binds the handshake to the protocol name and both node hints,
/// which kills downgrade and cross-protocol attacks before they start.
internal struct HandshakeReadResult: Equatable, Sendable {
    let payload: Data
    let authenticatedRemoteStaticKey: Data?

    init(payload: Data, authenticatedRemoteStaticKey: Data? = nil) {
        self.payload = payload
        self.authenticatedRemoteStaticKey = authenticatedRemoteStaticKey
    }
}

public final class NoiseSession {

    public enum Role { case initiator, responder }

    /// Handshake cipher. `n` resets to zero on every MixKey and increments on
    /// every use -- that increment is defect (c) above.
    private struct CipherState {
        var k: SymmetricKey?
        var n: UInt64 = 0

        /// Noise s.12.3: 32 bits of zeros then LITTLE-endian n.
        func nonce() throws -> ChaChaPoly.Nonce {
            var v = n.littleEndian
            return try ChaChaPoly.Nonce(data: Data(count: 4) + Data(bytes: &v, count: 8))
        }
    }

    private let role: Role
    private let staticKey: Curve25519.KeyAgreement.PrivateKey
    private var ephemeral: Curve25519.KeyAgreement.PrivateKey

    private var chainingKey: Data
    private var handshakeHash: Data
    private var cipher = CipherState()

    private var sendKey: SymmetricKey?
    private var receiveKey: SymmetricKey?
    private var sendNonce: UInt64 = 0
    private var receiveNonce: UInt64 = 0

    // T07: monotonic session budget (see SessionBudget below).
    private let establishedMono: UInt64 = DispatchTime.now().uptimeNanoseconds
    private var receiveCount: UInt64 = 0
    private var retiredReason: String?
    internal var recordBudgetForTest: UInt64?
    internal var ageBudgetForTest: Double?
    internal var establishedMonoForTest: UInt64?

    private var remoteEphemeral: Data?
    public private(set) var remoteStaticKey: Data?
    public private(set) var isEstablished = false

    private static let protocolName = "Noise_XX_25519_ChaChaPoly_BLAKE2s"
    private static let tagLen = 16
    private static let dhLen = 32
    // T07 session budget: 2^20 records per direction, 30 minutes.
    public static let recordBudget: UInt64 = 1 << 20
    public static let timeBudgetSeconds: TimeInterval = 30 * 60

    public init(role: Role,
                staticKey: Curve25519.KeyAgreement.PrivateKey,
                localHint: Data,
                remoteHint: Data) {
        self.role = role
        self.staticKey = staticKey
        self.ephemeral = Curve25519.KeyAgreement.PrivateKey()

        var prologue = Data("GMP2".utf8)
        // Canonical ordering: initiator hint first, both sides agree.
        if role == .initiator {
            prologue.append(localHint); prologue.append(remoteHint)
        } else {
            prologue.append(remoteHint); prologue.append(localHint)
        }

        // InitializeSymmetric(protocol_name): pad to HASHLEN, else hash.
        let name = Data(NoiseSession.protocolName.utf8)
        let h0: Data = name.count <= 32
            ? name + Data(count: 32 - name.count)
            : Blake2s.hash(name, digestLength: 32)
        self.chainingKey = h0
        self.handshakeHash = Blake2s.hash(h0 + prologue, digestLength: 32)
    }

    // MARK: - Symmetric state

    private func mixHash(_ data: Data) {
        handshakeHash = Blake2s.hash(handshakeHash + data, digestLength: 32)
    }

    private func mixKey(_ secret: SharedSecret) {
        let material = secret.withUnsafeBytes { Data($0) }
        let (ck, k) = Hkdf.split(chainingKey: chainingKey, material: material)
        chainingKey = ck
        // n RESETS here. This is the whole of defect (c).
        cipher = CipherState(k: SymmetricKey(data: k), n: 0)
    }

    private func encryptAndHash(_ plaintext: Data) throws -> Data {
        guard let k = cipher.k else {
            mixHash(plaintext)
            return plaintext
        }
        let box = try ChaChaPoly.seal(plaintext, using: k,
                                      nonce: cipher.nonce(),
                                      authenticating: handshakeHash)
        cipher.n += 1
        let out = box.ciphertext + box.tag
        mixHash(out)
        return out
    }

    private func decryptAndHash(_ ciphertext: Data) throws -> Data {
        guard let k = cipher.k else {
            mixHash(ciphertext)
            return ciphertext
        }
        guard ciphertext.count >= NoiseSession.tagLen else {
            throw MeshError.handshakeFailed
        }
        // AAD is h BEFORE this ciphertext is mixed in.
        let aad = handshakeHash
        let box = try ChaChaPoly.SealedBox(
            nonce: cipher.nonce(),
            ciphertext: ciphertext.dropLast(NoiseSession.tagLen),
            tag: ciphertext.suffix(NoiseSession.tagLen))
        let plain = try ChaChaPoly.open(box, using: k, authenticating: aad)
        cipher.n += 1
        mixHash(ciphertext)
        return plain
    }

    /// Writer-relative DH resolution. Getting es/se backwards is silent: both
    /// sides still produce 32 bytes, they just disagree, and the failure only
    /// surfaces as a tag mismatch one message later.
    private func dhEE() throws -> SharedSecret {
        try ephemeral.sharedSecretFromKeyAgreement(
            with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteEphemeral!))
    }
    private func dhES() throws -> SharedSecret {
        role == .initiator
            ? try ephemeral.sharedSecretFromKeyAgreement(
                with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteStaticKey!))
            : try staticKey.sharedSecretFromKeyAgreement(
                with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteEphemeral!))
    }
    private func dhSE() throws -> SharedSecret {
        role == .initiator
            ? try staticKey.sharedSecretFromKeyAgreement(
                with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteEphemeral!))
            : try ephemeral.sharedSecretFromKeyAgreement(
                with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: remoteStaticKey!))
    }

    // MARK: - Handshake  (XX:  -> e   <- e, ee, s, es   -> s, se)

    /// Message 1, initiator: `-> e`  (32 bytes with an empty payload)
    public func writeMessage1(payload: Data = Data()) throws -> Data {
        var out = ephemeral.publicKey.rawRepresentation
        mixHash(out)
        out += try encryptAndHash(payload)
        return out
    }

    /// Message 1, responder reads: `-> e`
    @discardableResult
    internal func readMessage1(_ msg1: Data) throws -> HandshakeReadResult {
        let m = Data(msg1)
        guard m.count >= NoiseSession.dhLen else { throw MeshError.handshakeFailed }

        remoteEphemeral = m.prefix(NoiseSession.dhLen)
        mixHash(remoteEphemeral!)
        let payload = try decryptAndHash(m.suffix(from: NoiseSession.dhLen))
        return HandshakeReadResult(payload: payload, authenticatedRemoteStaticKey: nil)
    }

    /// Message 2, responder writes: `e, ee, s, es` + payload
    public func writeMessage2(payload: Data = Data()) throws -> Data {
        guard role == .responder, remoteEphemeral != nil else { throw MeshError.handshakeFailed }
        var out = ephemeral.publicKey.rawRepresentation
        mixHash(out)
        mixKey(try dhEE())                                             // ee
        out += try encryptAndHash(staticKey.publicKey.rawRepresentation) // s
        mixKey(try dhES())                                             // es
        out += try encryptAndHash(payload)                             // payload
        return out
    }

    /// Message 2, responder: reads `e`, writes `e, ee, s, es` + payload.
    /// 96 bytes with empty payloads. V3 produced 80.
    public func readMessage1AndWrite2(_ msg1: Data,
                                      payload: Data = Data()) throws -> Data {
        _ = try readMessage1(msg1)
        return try writeMessage2(payload: payload)
    }

    /// Message 2, initiator: reads message 2, parses remote static key & payload.
    /// Does NOT write HS3 and does NOT call split().
    internal func readMessage2(_ msg2: Data) throws -> HandshakeReadResult {
        let m = Data(msg2)
        let encStaticLen = NoiseSession.dhLen + NoiseSession.tagLen   // 48
        guard m.count >= NoiseSession.dhLen + encStaticLen else {
            throw MeshError.handshakeFailed
        }

        remoteEphemeral = m.prefix(NoiseSession.dhLen)
        mixHash(remoteEphemeral!)
        mixKey(try dhEE())                                             // ee

        let encStatic = m.subdata(in: NoiseSession.dhLen ..< (NoiseSession.dhLen + encStaticLen))
        let decryptedStatic = try decryptAndHash(encStatic)            // s
        guard decryptedStatic.count == NoiseSession.dhLen else {
            throw MeshError.handshakeFailed
        }
        remoteStaticKey = decryptedStatic
        mixKey(try dhES())                                             // es
        let payload = try decryptAndHash(m.suffix(from: NoiseSession.dhLen + encStaticLen))
        return HandshakeReadResult(payload: payload, authenticatedRemoteStaticKey: decryptedStatic)
    }

    /// Message 3, initiator writes: `s, se` + payload.
    public func writeMessage3(payload: Data = Data()) throws -> Data {
        guard role == .initiator, remoteStaticKey != nil, remoteEphemeral != nil, !isEstablished else {
            throw MeshError.handshakeFailed
        }
        var out = try encryptAndHash(staticKey.publicKey.rawRepresentation)  // s
        mixKey(try dhSE())                                             // se
        out += try encryptAndHash(payload)                             // payload
        split()
        return out
    }

    /// Message 3, responder side.
    @discardableResult
    internal func readMessage3(_ msg3: Data) throws -> HandshakeReadResult {
        let m = Data(msg3)
        let encStaticLen = NoiseSession.dhLen + NoiseSession.tagLen
        guard m.count >= encStaticLen else { throw MeshError.handshakeFailed }

        let decryptedStatic = try decryptAndHash(m.prefix(encStaticLen))   // s
        guard decryptedStatic.count == NoiseSession.dhLen else {
            throw MeshError.handshakeFailed
        }
        remoteStaticKey = decryptedStatic
        mixKey(try dhSE())                                             // se
        let payload = try decryptAndHash(m.suffix(from: encStaticLen))
        split()
        return HandshakeReadResult(payload: payload, authenticatedRemoteStaticKey: decryptedStatic)
    }

    private func split() {
        let (k1, k2) = Hkdf.split(chainingKey: chainingKey, material: Data())
        // Never the same key in both directions: that makes nonce reuse fatal.
        sendKey    = SymmetricKey(data: role == .initiator ? k1 : k2)
        receiveKey = SymmetricKey(data: role == .initiator ? k2 : k1)
        sendNonce = 0
        receiveNonce = 0
        isEstablished = true
    }

    /// Handshake hash, equal on both sides once the handshake completes.
    /// Exposed so the port-vector test can assert it.
    public var transcriptHash: Data { handshakeHash }

    // MARK: - Transport

    private static func transportNonce(_ n: UInt64) throws -> ChaChaPoly.Nonce {
        var v = n.littleEndian
        return try ChaChaPoly.Nonce(data: Data(count: 4) + Data(bytes: &v, count: 8))
    }

    public func encrypt(_ plaintext: Data) throws -> Data {
        if let reason = retiredReason {
            throw SessionExpired(reason: reason)
        }
        guard let key = sendKey else { throw MeshError.handshakeFailed }
        if let reason = enforceSendBudget() {
            throw SessionExpired(reason: reason)
        }
        // T06: the wire nonce is explicit: uint64_be(nonce) prefix.
        let nonce = sendNonce
        let box = try ChaChaPoly.seal(plaintext, using: key,
                                      nonce: NoiseSession.transportNonce(nonce))
        sendNonce += 1
        // Internal ChaCha nonce stays zero32 || uint64_le(n);
        // the wire carries uint64_be(n) || ciphertext || tag.
        return TransportCiphertextV1.encode(nonce: nonce,
                                            ciphertextAndTag: box.ciphertext + box.tag)
    }

    /// T06: typed outcome of one authenticated-open session operation
    /// (parity with Android `NoiseSession.CryptoOpenResult`).
    public enum CryptoOpenResult {
        case authenticated(Data)
        case rejected
        case expired
    }

    private let replayWindow = ReplayWindow()
    private let replayLock = NSLock()

    /// T06: one session operation = parse -> preview -> authenticate ->
    /// commit. The wire nonce is the explicit uint64_be prefix
    /// (TransportCiphertextV1); the internal ChaChaPoly nonce stays
    /// zero32 || uint64_le(n). A failed authenticate commits nothing.
    public func openWithResult(_ ciphertext: Data) throws -> CryptoOpenResult {
        guard let key = receiveKey else { throw MeshError.handshakeFailed }
        if let reason = enforceReceiveBudget() {
            return .expired
        }
        guard ciphertext.count >= 8 + NoiseSession.tagLen else {
            return .rejected
        }
        let framed = TransportCiphertextV1.decode(ciphertext)
        guard let (nonceRaw, body) = framed else { return .rejected }
        let parsed = UnsignedNonce.parse(
            Data(repeating: 0, count: 0) + withUnsafeBytes(of: nonceRaw.bigEndian)
                { Data($0) })
        guard case .valid(let nonce) = parsed else { return .expired }
        replayLock.lock()
        defer { replayLock.unlock() }
        let plan = replayWindow.preview(nonce)
        guard case .accept(let accepted, let forwardShift, let index) = plan
        else { return .expired }
        let box = try? ChaChaPoly.SealedBox(
            nonce: NoiseSession.transportNonce(accepted),
            ciphertext: body.dropLast(NoiseSession.tagLen),
            tag: body.suffix(NoiseSession.tagLen))
        guard let sealed = box,
              let plain = try? ChaChaPoly.open(sealed, using: key)
        else { return .rejected }
        replayWindow.commit(.accept(nonce: accepted,
                                    forwardShift: forwardShift,
                                    index: index))
        receiveCount &+= 1
        return .authenticated(plain)
    }

    /// Backward-compatible wrapper: hard failure on any non-authenticated
    /// outcome, preserving the pre-T06 contract for existing callers.
    public func decrypt(_ ciphertext: Data) throws -> Data {
        switch try openWithResult(ciphertext) {
        case .authenticated(let plain): return plain
        case .rejected, .expired: throw MeshError.handshakeFailed
        }
    }

    // MARK: - T07 deterministic session retirement

    /// T07: monotonic session budget, established at trusted establishment:
    /// 2^20 authenticated records per direction or 30 minutes, whichever
    /// comes first. Retirement is terminal: key material and readiness are
    /// cleared, the relation closes, and a fresh trusted Noise session must
    /// be established. No counter resets under an existing key and there is
    /// no rekey-in-place API.
    public struct SessionBudget: Equatable {
        public let establishedMono: UInt64
        public let sendCount: UInt64
        public let receiveCount: UInt64
    }

    /// T07: the session is past its agreed budget and is retired.
    public struct SessionExpired: Error {
        public let reason: String
    }

    private func budgetAgeSeconds() -> TimeInterval {
        let start = establishedMonoForTest ?? establishedMono
        let now = DispatchTime.now().uptimeNanoseconds
        return TimeInterval(now &- start) / 1_000_000_000.0
    }

    private func budgetLimit() -> UInt64 {
        recordBudgetForTest ?? NoiseSession.recordBudget
    }

    /// T07 terminal retirement: clear readiness and key material.
    private func retire(_ reason: String) {
        if retiredReason == nil { retiredReason = reason }
        sendKey = nil
        receiveKey = nil
        isEstablished = false
    }

    private func enforceSendBudget() -> String? {
        if let reason = retiredReason { return reason }
        let limit = recordBudgetForTest ?? NoiseSession.recordBudget
        if sendNonce + 1 > limit {
            retire("send budget: 2^20 authenticated records reached")
            return "send budget exceeded (records)"
        }
        if budgetAgeSeconds() > (ageBudgetForTest ?? NoiseSession.timeBudgetSeconds) {
            retire("send budget: 30 minutes elapsed")
            return "send budget exceeded (time)"
        }
        return nil
    }

    private func enforceReceiveBudget() -> String? {
        if let reason = retiredReason { return reason }
        let limit = recordBudgetForTest ?? NoiseSession.recordBudget
        if receiveCount + 1 > limit {
            retire("receive budget: 2^20 authenticated records reached")
            return "receive budget exceeded (records)"
        }
        if budgetAgeSeconds() > (ageBudgetForTest ?? NoiseSession.timeBudgetSeconds) {
            retire("receive budget: 30 minutes elapsed")
            return "receive budget exceeded (time)"
        }
        return nil
    }

    /// T06 test hooks: bind fixture transport keys (documented constants,
    /// never real secrets) so the exporter/verifier exercises the real
    /// session codec without a live handshake.
    func installSendKeyForTest(_ key: SymmetricKey) {
        sendKey = key
        isEstablished = true
    }

    func installReceiveKeyForTest(_ key: SymmetricKey) {
        receiveKey = key
        isEstablished = true
    }

    public func destroy() {
        sendKey = nil
        receiveKey = nil
        chainingKey = Data()
        handshakeHash = Data()
        remoteEphemeral = nil
        remoteStaticKey = nil
    }
}
