package io.godstone.mesh.wire.v2

import org.bouncycastle.crypto.digests.Blake2sDigest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals

/**
 * GMP/2.1 msg_id byte-parity (ADR-001 §3.3, Stage 3 Phase C).
 *
 * The expected `msg_id` hex literals below are transcribed verbatim from
 * crypto/gmp21_vectors.json, which is generated by the independent Python
 * reference crypto/gmp21.py (hashlib.blake2s, RFC 7693). A byte-identical
 * Kotlin `derive()` proves Android agrees with the pinned spec spelling
 * `msg_id = BLAKE2s-128(sender ‖ created_at_le ‖ payload)` -- little-endian
 * created_at -- not just with itself. The iOS twin is MessageIdTests.swift.
 *
 * The mutation case proves the byte order is the discriminator: the same
 * inputs with created_at encoded BIG-endian yield a different digest
 * (e10707c3...), so a regression that flips `uint32Le` back to `uint32Be`
 * fails the positive cases AND is named here.
 */
class MessageIdTest {

    private fun hex(b: String): ByteArray =
        ByteArray(b.length / 2) { i ->
            ((Character.digit(b[i * 2], 16) shl 4) or
                Character.digit(b[i * 2 + 1], 16)).toByte()
        }

    private val senderA = hex("000102030405060708090a0b0c0d0e0f")
    private val senderB = hex("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")

    // --- transcribed from crypto/gmp21_vectors.json msg_id.cases ---

    @Test
    fun `msg_id empty payload zero time reproduces locked vector`() {
        assertEquals(
            "fe9c55924a94692c6721d13c3d06ca5a",
            MessageId.derive(senderA, 0, ByteArray(0)).joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `msg_id help epoch 1 reproduces locked vector`() {
        assertEquals(
            "b0fcd6858d4a0e24b434dfcf273ff20c",
            MessageId.derive(senderA, 1, "help".toByteArray()).joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `msg_id sos payload real epoch reproduces locked vector`() {
        assertEquals(
            "ea5260efb0ab65829f02042a7237a2cb",
            MessageId.derive(senderB, 1700000000, "SOS payload".toByteArray())
                .joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `msg_id is 16 bytes`() {
        assertEquals(16, MessageId.derive(senderA, 1, "help".toByteArray()).size)
    }

    /**
     * Mutation: created_at encoded BIG-endian must produce the locked BE digest
     * e10707c3..., which differs from the LE digest b0fcd685... If `derive` is
     * flipped back to big-endian, this test fails (the BE path now matches the
     * LE-positive case's inputs) AND the `help epoch 1` positive case fails.
     */
    @Test
    fun `big-endian created_at produces a different locked digest`() {
        val beDigest = blake2s128(senderA + MessageId.uint32Be(1) + "help".toByteArray())
        assertEquals(
            "e10707c3ca4f77761420396d83b2a367",
            beDigest.joinToString("") { "%02x".format(it) },
        )
        assertNotEquals(
            "b0fcd6858d4a0e24b434dfcf273ff20c",
            beDigest.joinToString("") { "%02x".format(it) },
        )
    }

    private fun blake2s128(data: ByteArray): ByteArray {
        val d = Blake2sDigest(null, 16, null, null)
        d.update(data, 0, data.size)
        val out = ByteArray(16)
        d.doFinal(out, 0)
        return out
    }
}