package io.godstone.mesh.wire.v2

import org.bouncycastle.crypto.digests.Blake2sDigest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * GMP/2.1 msg_id byte-parity and logical message identity (ADR-001 §3.3, C6.7.1).
 *
 * The expected `msg_id` hex literals below are transcribed verbatim from
 * crypto/gmp21_vectors.json, which is generated by the independent Python
 * reference crypto/gmp21.py (hashlib.blake2s, RFC 7693). A byte-identical
 * Kotlin `derive()` proves Android agrees with the pinned spec spelling:
 *     msg_id = BLAKE2s-128(b"GMP2-MSGID" ‖ sender ‖ created_at_le ‖ message_nonce ‖ plaintext)
 *
 * The iOS twin is MessageIdTests.swift.
 */
class MessageIdTest {

    private fun hex(b: String): ByteArray =
        ByteArray(b.length / 2) { i ->
            ((Character.digit(b[i * 2], 16) shl 4) or
                Character.digit(b[i * 2 + 1], 16)).toByte()
        }

    private val senderA = hex("000102030405060708090a0b0c0d0e0f")
    private val senderB = hex("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    private val nonceZero = hex("00000000000000000000000000000000")
    private val nonceOnes = hex("01010101010101010101010101010101")
    private val nonceKat = hex("00112233445566778899aabbccddeeff")

    // --- transcribed from crypto/gmp21_vectors.json msg_id.cases ---

    @Test
    fun `msg_id empty payload zero time zero nonce reproduces locked vector`() {
        assertEquals(
            "0cd32fa4ac79a506b3f04008fed71e59",
            MessageId.derive(senderA, 0, nonceZero, ByteArray(0)).joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `msg_id help epoch 1 nonce all ones reproduces locked vector`() {
        assertEquals(
            "b288201494ca28ee63da7c49433abcbe",
            MessageId.derive(senderA, 1, nonceOnes, "help".toByteArray()).joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `msg_id sos payload real epoch kat nonce reproduces locked vector`() {
        assertEquals(
            "6e16a5bf98f03ed1320281a55cd490ae",
            MessageId.derive(senderB, 1700000000, nonceKat, "SOS payload".toByteArray())
                .joinToString("") { "%02x".format(it) },
        )
    }

    @Test
    fun `msg_id is 16 bytes`() {
        assertEquals(16, MessageId.derive(senderA, 1, nonceOnes, "help".toByteArray()).size)
    }

    /**
     * Mutation: created_at encoded BIG-endian must produce the locked BE digest
     * 65a85cef..., which differs from the LE digest b2882014...
     */
    @Test
    fun `big-endian created_at produces a different locked digest`() {
        val domainBytes = MessageId.DOMAIN_SEPARATOR_TEXT.toByteArray(Charsets.US_ASCII)
        val beDigest = blake2s128(
            domainBytes + senderA + MessageId.uint32Be(1) + nonceOnes + "help".toByteArray()
        )
        assertEquals(
            "65a85cef9612f20bdcd938bc416b27f8",
            beDigest.joinToString("") { "%02x".format(it) },
        )
        assertNotEquals(
            "b288201494ca28ee63da7c49433abcbe",
            beDigest.joinToString("") { "%02x".format(it) },
        )
    }

    /**
     * Distinct nonces for identical content, time, and sender MUST yield distinct msg_ids.
     */
    @Test
    fun `distinct nonces for identical sender content time produce distinct msg_ids`() {
        val id1 = MessageId.derive(senderA, 1, nonceOnes, "help".toByteArray())
        val id2 = MessageId.derive(senderA, 1, nonceZero, "help".toByteArray())
        assertEquals(
            "ca00c29df07276c186b57ac028a3d31c",
            id2.joinToString("") { "%02x".format(it) },
        )
        assertNotEquals(id1.toList(), id2.toList())
    }

    /**
     * Missing domain separator produces a different digest.
     */
    @Test
    fun `missing domain separator produces a different digest`() {
        val noDomainDigest = blake2s128(
            senderA + MessageId.uint32Le(1) + nonceOnes + "help".toByteArray()
        )
        val withDomain = MessageId.derive(senderA, 1, nonceOnes, "help".toByteArray())
        assertNotEquals(withDomain.toList(), noDomainDigest.toList())
    }

    /**
     * C6.7.8: Retry stability - 100 re-derivations with the same parameters yield the exact same msg_id.
     */
    @Test
    fun `retry stability preserves exact same msg_id across 100 evaluations`() {
        val baseline = MessageId.derive(senderA, 123456789L, nonceKat, "same message content".toByteArray())
        for (i in 1..100) {
            val retry = MessageId.derive(senderA, 123456789L, nonceKat, "same message content".toByteArray())
            assertTrue(baseline.contentEquals(retry), "Retry $i diverged from baseline msg_id")
        }
    }

    /**
     * C6.7.10: Alice vs Bob concurrent sends at same timestamp with same content receive distinct msg_ids.
     */
    @Test
    fun `alice vs bob concurrent sends at same second receive distinct msg_ids`() {
        val timestamp = 1710000000L
        val content = "meet at medical station".toByteArray()
        val identityAlice = LogicalMessageIdentity.of(timestamp, hex("01010101010101010101010101010101"))
        val identityBob = LogicalMessageIdentity.of(timestamp, hex("02020202020202020202020202020202"))

        val msgIdForAlice = MessageId.derive(senderA, identityAlice, content)
        val msgIdForBob = MessageId.derive(senderA, identityBob, content)

        assertNotEquals(msgIdForAlice.toList(), msgIdForBob.toList())
    }

    @Test
    fun `logical message identity validates uint32 range and defensive copies nonce`() {
        val nonce = ByteArray(16) { 0x42 }
        val ident = LogicalMessageIdentity.of(100L, nonce)

        // Mutating source array must not mutate ident
        nonce[0] = 0x99.toByte()
        assertEquals(0x42.toByte(), ident.messageNonce[0])

        // Mutating read-out array must not mutate ident
        val readNonce = ident.messageNonce
        readNonce[0] = 0x99.toByte()
        assertEquals(0x42.toByte(), ident.messageNonce[0])
    }

    @Test
    fun `logical message identity toString redacts message nonce`() {
        val nonce = ByteArray(16) { 0x42 }
        val ident = LogicalMessageIdentity.of(100L, nonce)
        val s = ident.toString()
        assertTrue(s.contains("createdAt=100"))
        assertTrue(s.contains("nonce=<redacted>"))
        assertFalse(s.contains("424242"))
    }

    private fun blake2s128(data: ByteArray): ByteArray {
        val d = Blake2sDigest(null, 16, null, null)
        d.update(data, 0, data.size)
        val out = ByteArray(16)
        d.doFinal(out, 0)
        return out
    }
}