package io.godstone.mesh.wire.v2

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull

/**
 * Golden wire-vector conformance for the generated GMP/2.1 `FrameV2` codec.
 *
 * These vectors are pinned from `wire/golden_vectors.json`, which is GENERATED by
 * `wire/codegen.py` from `wire/wire_v2.yaml` using the independent Python
 * reference codec (`wire/gen/wire_v2_codec.py`). The expected `encoded` bytes
 * and the negative `frame` bytes below are NOT self-generated from the Kotlin
 * codec under test — they are the Python-reference output, transcribed as hex
 * literals (mirroring the inline-literal style of `PortVectorTest`). A
 * byte-identical Kotlin `encode()` (positive) and a fail-closed `decode()` /
 * `SosFrameValidator` refusal (negative) prove the two codecs agree with the
 * spec, not just with themselves.
 *
 * This is ADR-008 patch 15 (frame-validation-and-vectors) and satisfies ADR-001
 * acceptance criterion 3 (cross-platform golden vectors) on Android. The iOS
 * mirror is `ios/Godstone/Tests/GodstoneMeshTests/WireV2VectorTests.swift`.
 *
 * The `golden_vectors.json` fixture is the single source of truth; if these
 * literals ever disagree with it, `python3 -m wire.codegen` + the Python
 * conformance runner is the resolution path, not editing this test.
 *
 * Coverage: 4 positive encode cases (HELLO, MESSAGE, DIGEST, SOS — every
 * golden positive), 4 wire-level negative cases (legacy type 0x02, v1 frame,
 * bad CRC, hop_count over MAX_TTL — `decode()` returns null), and 2 SOS
 * structural negative cases (missing payload magic, missing required flags —
 * `decode()` returns a parsed frame that `SosFrameValidator` refuses).
 */
class WireV2VectorTest {

    private fun hexToBytes(hex: String): ByteArray =
        ByteArray(hex.length / 2) { i ->
            ((Character.digit(hex[i * 2], 16) shl 4) or
                Character.digit(hex[i * 2 + 1], 16)).toByte()
        }

    private fun bytesToHex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }

    // ---- positive: encode() reproduces the pinned Python-reference bytes ----
    // Expected `encoded` values are transcribed verbatim from
    // wire/golden_vectors.json `cases[*].encoded` (codegen Python reference).

    @Test
    fun `encode_hello reproduces golden vector`() {
        val f = FrameV2(
            type = TypeV2.HELLO,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12, hopCount = 0, flags = FrameV2.SEALED,
            payload = hexToBytes("7061796c6f61642d48454c4c4f"), // "payload-HELLO"
        )
        assertEquals(
            "47530211000102030405060708090a0b0c0d0e0fdeadbeef0c000001000d5cbf7061796c6f61642d48454c4c4f",
            bytesToHex(f.encode()),
        )
    }

    @Test
    fun `encode_message reproduces golden vector`() {
        val f = FrameV2(
            type = TypeV2.MESSAGE,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12, hopCount = 0, flags = FrameV2.SEALED,
            payload = hexToBytes("7061796c6f61642d4d455353414745"), // "payload-MESSAGE"
        )
        assertEquals(
            "47530218000102030405060708090a0b0c0d0e0fdeadbeef0c000001000fc2ab7061796c6f61642d4d455353414745",
            bytesToHex(f.encode()),
        )
    }

    @Test
    fun `encode_digest reproduces golden vector`() {
        val f = FrameV2(
            type = TypeV2.DIGEST,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12, hopCount = 0, flags = FrameV2.SEALED,
            payload = hexToBytes("7061796c6f61642d444947455354"), // "payload-DIGEST"
        )
        assertEquals(
            "47530212000102030405060708090a0b0c0d0e0fdeadbeef0c000001000e53767061796c6f61642d444947455354",
            bytesToHex(f.encode()),
        )
    }

    @Test
    fun `encode_sos reproduces golden vector`() {
        // SOS payload shape (wire_v2.yaml sos_requirements): "SOS1" + 64-byte
        // signature slot (zero placeholder in the golden vector) + "help".
        val f = FrameV2(
            type = TypeV2.SOS,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12, hopCount = 0, flags = FrameV2.ACK_REQ or FrameV2.RELAY_OK,
            payload = hexToBytes(
                "534f5331" + "00".repeat(64) + "68656c70", // "SOS1" + 64 zero bytes + "help"
            ),
        )
        assertEquals(
            "475302f0000102030405060708090a0b0c0d0e0fdeadbeef0c000030004834c0534f5331" +
                "00".repeat(64) + "68656c70",
            bytesToHex(f.encode()),
        )
    }

    // ---- round-trip: decode() inverts encode() for each positive case ----

    @Test
    fun `decode round-trips every positive golden vector`() {
        val vectors = listOf(
            Triple(TypeV2.HELLO, 1, "47530211000102030405060708090a0b0c0d0e0fdeadbeef0c000001000d5cbf7061796c6f61642d48454c4c4f"),
            Triple(TypeV2.MESSAGE, 1, "47530218000102030405060708090a0b0c0d0e0fdeadbeef0c000001000fc2ab7061796c6f61642d4d455353414745"),
            Triple(TypeV2.DIGEST, 1, "47530212000102030405060708090a0b0c0d0e0fdeadbeef0c000001000e53767061796c6f61642d444947455354"),
            Triple(TypeV2.SOS, 0x30, "475302f0000102030405060708090a0b0c0d0e0fdeadbeef0c000030004834c0" +
                "534f5331" + "00".repeat(64) + "68656c70"),
        )
        for ((type, flags, hex) in vectors) {
            val f = FrameV2.decode(hexToBytes(hex))
            assertNotNull(f, "decode returned null for $type golden vector")
            assertEquals(type, f.type, "type mismatch for $type")
            assertEquals(flags, f.flags, "flags mismatch for $type")
            // Re-encoding the decoded frame must reproduce the exact bytes.
            assertEquals(hex, bytesToHex(f.encode()), "round-trip not byte-identical for $type")
        }
    }

    // ---- negative: wire-level decode rejects malformed headers (decode==null) ----
    // Frames transcribed verbatim from wire/golden_vectors.json
    // `negative_cases[*].frame`. These are malformed at the HEADER level, so
    // decode() must fail-closed to null BEFORE any payload is parsed.

    @Test
    fun `reject_legacy_type_0x02 is rejected at the wire layer`() {
        // type byte 0x02 is not in TypeV2 (v1 Android DIGEST / v1 iOS SOS); must
        // hit the unknown-type branch, never be read as a distress broadcast.
        assertNull(FrameV2.decode(hexToBytes(
            "47530202000102030405060708090a0b0c0d0e0fdeadbeef0c000001000d25547061796c6f61642d48454c4c4f")))
    }

    @Test
    fun `reject_v1_frame is rejected at the wire layer`() {
        // version byte 0x01 (GMP/1); checked before anything else.
        assertNull(FrameV2.decode(hexToBytes(
            "47530111000102030405060708090a0b0c0d0e0fdeadbeef0c000001000d31037061796c6f61642d48454c4c4f")))
    }

    @Test
    fun `reject_bad_crc is rejected at the wire layer`() {
        // single-bit corruption inside msg_id must fail the header CRC.
        assertNull(FrameV2.decode(hexToBytes(
            "47530211000102030405f90708090a0b0c0d0e0fdeadbeef0c000001000d5cbf7061796c6f61642d48454c4c4f")))
    }

    @Test
    fun `reject_hop_count_over_max is rejected at the wire layer`() {
        // hop_count above MAX_TTL is malformed and must not wrap on relay.
        assertNull(FrameV2.decode(hexToBytes(
            "47530211000102030405060708090a0b0c0d0e0fdeadbeef0c110001000df2b47061796c6f61642d48454c4c4f")))
    }

    // ---- negative: SOS structural rejection (decode!=null, validator refuses) ----
    // These are WELL-FORMED frames at the wire layer (header parses), so
    // decode() returns a parsed FrameV2. The SOS validator must refuse them:
    // a parse error or a non-distress frame must not be able to fabricate a
    // distress call (ADR-001 §6).

    @Test
    fun `reject_sos_missing_payload_magic parses as a frame but is refused by the SOS validator`() {
        // SOS frame with flags set but payload = "help" (no SOS1 magic, no
        // 64-byte signature slot). Decodes fine; the SOS structural gate
        // refuses it (payload too short to hold magic + signature).
        val f = FrameV2.decode(hexToBytes(
            "475302f0000102030405060708090a0b0c0d0e0fdeadbeef0c0000300004bd8868656c70"))
        assertNotNull(f, "well-formed frame must parse at the wire layer; the SOS gate is structural, not parse-level")
        assertEquals(SosFrameValidator.Verdict.PAYLOAD_TOO_SHORT, SosFrameValidator.validate(f))
    }

    @Test
    fun `reject_sos_missing_flags parses as a frame but is refused by the SOS validator`() {
        // SOS frame with a well-formed SOS payload ("SOS1" + 64 zeros + "help")
        // but flags = 0 (missing ACK_REQ | RELAY_OK). Decodes fine; the SOS
        // structural gate refuses it (required flags absent).
        val f = FrameV2.decode(hexToBytes(
            "475302f0000102030405060708090a0b0c0d0e0fdeadbeef0c0000000048f165" +
                "534f5331" + "00".repeat(64) + "68656c70"))
        assertNotNull(f, "well-formed frame must parse at the wire layer")
        assertEquals(SosFrameValidator.Verdict.MISSING_REQUIRED_FLAGS, SosFrameValidator.validate(f))
    }

    // ---- positive SOS validator: a well-formed SOS payload is accepted ----

    @Test
    fun `sos validator accepts the golden sos vector`() {
        val f = FrameV2(
            type = TypeV2.SOS,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12, hopCount = 0, flags = FrameV2.ACK_REQ or FrameV2.RELAY_OK,
            payload = hexToBytes("534f5331" + "00".repeat(64) + "68656c70"),
        )
        assertEquals(SosFrameValidator.Verdict.OK, SosFrameValidator.validate(f))
    }

    @Test
    fun `sos validator rejects a non-sos type`() {
        val f = FrameV2(
            type = TypeV2.HELLO,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12, hopCount = 0, flags = FrameV2.ACK_REQ or FrameV2.RELAY_OK,
            payload = hexToBytes("534f5331" + "00".repeat(64) + "68656c70"),
        )
        assertEquals(SosFrameValidator.Verdict.WRONG_TYPE, SosFrameValidator.validate(f))
    }

    // ---- C6.7.4: FrameV2 immutable value semantics & negative mutation tests ----

    @Test
    fun `constructor input mutation does not alter FrameV2 state`() {
        val inputMsgId = hexToBytes("000102030405060708090a0b0c0d0e0f")
        val inputTag = hexToBytes("deadbeef")
        val inputPayload = hexToBytes("7061796c6f61642d4d455353414745")
        val frame = FrameV2(
            type = TypeV2.MESSAGE,
            msgId = inputMsgId,
            routingTag = inputTag,
            ttl = 12,
            hopCount = 0,
            flags = FrameV2.SEALED,
            payload = inputPayload
        )

        // Mutate original constructor input arrays
        inputMsgId[0] = 0xFF.toByte()
        inputTag[0] = 0x00.toByte()
        inputPayload[0] = 0x55.toByte()

        // Frame must retain original values
        assertEquals(0x00.toByte(), frame.msgId[0])
        assertEquals(0xDE.toByte(), frame.routingTag[0])
        assertEquals(0x70.toByte(), frame.payload[0])
    }

    @Test
    fun `getter array mutation does not leak or alter FrameV2 state`() {
        val frame = FrameV2(
            type = TypeV2.MESSAGE,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12,
            hopCount = 0,
            flags = FrameV2.SEALED,
            payload = hexToBytes("7061796c6f61642d4d455353414745")
        )

        val exportedMsgId = frame.msgId
        val exportedTag = frame.routingTag
        val exportedPayload = frame.payload

        exportedMsgId[0] = 0xAA.toByte()
        exportedTag[0] = 0xBB.toByte()
        exportedPayload[0] = 0xCC.toByte()

        // Subsequent getter reads must return clean copies of the original data
        assertEquals(0x00.toByte(), frame.msgId[0])
        assertEquals(0xDE.toByte(), frame.routingTag[0])
        assertEquals(0x70.toByte(), frame.payload[0])
    }

    @Test
    fun `copy method does not alias mutable arrays between original and copy`() {
        val original = FrameV2(
            type = TypeV2.MESSAGE,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12,
            hopCount = 0,
            flags = FrameV2.SEALED,
            payload = hexToBytes("7061796c6f61642d4d455353414745")
        )

        val copy = original.copy(ttl = 11, hopCount = 1)
        kotlin.test.assertTrue(original !== copy)
        assertEquals(original.msgId.toList(), copy.msgId.toList())

        // Mutate array from copy
        val copyPayload = copy.payload
        copyPayload[0] = 0x11.toByte()

        // Original and copy must remain unaffected
        assertEquals(0x70.toByte(), original.payload[0])
        assertEquals(0x70.toByte(), copy.payload[0])
    }

    @Test
    fun `content-based equals and hashCode work across distinct allocations`() {
        val a = FrameV2(
            type = TypeV2.MESSAGE,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12,
            hopCount = 0,
            flags = FrameV2.SEALED,
            payload = hexToBytes("7061796c6f61642d4d455353414745")
        )
        val b = FrameV2(
            type = TypeV2.MESSAGE,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12,
            hopCount = 0,
            flags = FrameV2.SEALED,
            payload = hexToBytes("7061796c6f61642d4d455353414745")
        )

        kotlin.test.assertTrue(a !== b, "Must be distinct allocations")
        assertEquals(a, b, "Identical content must be equal")
        assertEquals(a.hashCode(), b.hashCode(), "Identical content must have identical hashCode")

        // Single byte mutations in byte arrays make them unequal
        val diffMsgId = a.copy(msgId = hexToBytes("ff0102030405060708090a0b0c0d0e0f"))
        kotlin.test.assertNotEquals(a, diffMsgId)

        val diffTag = a.copy(routingTag = hexToBytes("cafebabe"))
        kotlin.test.assertNotEquals(a, diffTag)

        val diffPayload = a.copy(payload = hexToBytes("0061796c6f61642d4d455353414745"))
        kotlin.test.assertNotEquals(a, diffPayload)

        // Scalar differences make them unequal
        kotlin.test.assertNotEquals(a, a.copy(ttl = 5))
        kotlin.test.assertNotEquals(a, a.copy(hopCount = 1))
        kotlin.test.assertNotEquals(a, a.copy(flags = 0))
        kotlin.test.assertNotEquals(a, a.copy(type = TypeV2.HELLO))
    }

    @Test
    fun `encode output is stable against attempted external mutation`() {
        val inputMsgId = hexToBytes("000102030405060708090a0b0c0d0e0f")
        val inputTag = hexToBytes("deadbeef")
        val inputPayload = hexToBytes("7061796c6f61642d4d455353414745")
        val frame = FrameV2(
            type = TypeV2.MESSAGE,
            msgId = inputMsgId,
            routingTag = inputTag,
            ttl = 12,
            hopCount = 0,
            flags = FrameV2.SEALED,
            payload = inputPayload
        )

        val encodedBefore = bytesToHex(frame.encode())

        // Attempt mutations
        inputMsgId[0] = 0x99.toByte()
        frame.msgId[0] = 0x88.toByte()
        frame.payload[0] = 0x77.toByte()

        val encodedAfter = bytesToHex(frame.encode())
        assertEquals(encodedBefore, encodedAfter)
    }

    @Test
    fun `decoded frame equals original frame by content`() {
        val frame = FrameV2(
            type = TypeV2.MESSAGE,
            msgId = hexToBytes("000102030405060708090a0b0c0d0e0f"),
            routingTag = hexToBytes("deadbeef"),
            ttl = 12,
            hopCount = 0,
            flags = FrameV2.SEALED,
            payload = hexToBytes("7061796c6f61642d4d455353414745")
        )

        val decoded = FrameV2.decode(frame.encode())
        assertNotNull(decoded)
        assertEquals(frame, decoded)
        assertEquals(frame.hashCode(), decoded.hashCode())
    }
}